### ISSUE TITLE
Any `def` string in code block prevents block detection

### ISSUE THREAD

**Issue by rndstr** [chjj/marked#1006]
When there is a `def` at the beginning of any line within a code block, it is not recognized as such.

Sample inputs

A
```
`
def`
```

B

    ```ruby
    def foo(x)
      return 3
    end
    ```
## Expectation

The code block should be recognized as code block.

## Result

The code block is not recognized and just rendered as paragraphs.

A
```
<p>`</p>
    <p>def
    `</p>
```
B
```
<p>`
    ruby</p>
    <p>def foo(x)
      return 3
    end
    `</p>
```

## More information
This broke by commit https://github.com/chjj/marked/pull/976/commits/98ac7a43958014832788b9d01580f394c84bfb27
which seemed to have originated in https://github.com/chjj/marked/pull/974
and was supposed to fix https://github.com/chjj/marked/issues/465

**Comment by Feder1co5oave** [comment]
I think we need to revert and review #974 as soon as possible. I don't recall how that could have slipped my checking.
This can be quite tricky since we changed the whole test system, so expect to manually resolve some conflicts.

**Comment by KostyaTretyak** [comment]
Agree, should do revert  https://github.com/chjj/marked/commit/98ac7a43958014832788b9d01580f394c84bfb27 and https://github.com/chjj/marked/pull/974/commits/a477d1d0e285e1b0aed91ea9048bc66e85324b2a  commits. They are incorrect.

**Comment by joshbruce** [comment]
@Feder1co5oave and @KostyaTretyak: Agreed.

I know of three ways to do that - and seem to only be able to do one of them myself. (Note: Beleive it or not, I've never had to a reversion.)

1. Copy-paste and submit a new PR...not revert.
2. https://help.github.com/articles/reverting-a-pull-request/ - in theory, there should be a button at the bottom of the PRs to allow reversion - there is not.
3. Using git via terminal - https://git-scm.com/docs/git-revert.html - not comfortable enough to do that one myself for a live project in production.

**Comment by KostyaTretyak** [comment]
@joshbruce, please do the following via terminal from root the project:

```bash
git checkout master
git revert a477d1d --no-edit
git push origin master
```

It should go through without problems. And now I will pull request for revert `98ac7a4`.

**Comment by Feder1co5oave** [comment]
@KostyaTretyak can you not open a PR to revert both commits? That would be neater.

**Comment by KostyaTretyak** [comment]
Well, I [fixed](https://github.com/chjj/marked/pull/1007) my mistake, but now you need to fix the tests.

**Comment by KostyaTretyak** [comment]
Interestingly, CommonMark Spec is [such a rule](http://spec.commonmark.org/dingus/?text=%5Bfoo%5D%0A%0A%3E%20%5Bfoo%5D%3A%20%2Furl%0A), but it seems that in our case [it does not work](http://spec.commonmark.org/dingus/?text=%3E%20hello%0A%3E%20%5B1%5D%3A%20hello%0A%0A*%20*%20*%0A%0A%3E%20hello%0A%5B2%5D%3A%20hello%0A%0A%0A*%20hello%0A*%20%5B3%5D%3A%20hello%0A%0A%0A*%20hello%0A%5B4%5D%3A%20hello%0A%0A%0A%3E%20foo%0A%3E%20bar%0A%5B1%5D%3A%20foo%0A%3E%20bar%0A%0A) for some reason (see tab HTML and `[1]: foo` at bottom).

**Comment by KostyaTretyak** [comment]
And [this is not works too](http://spec.commonmark.org/dingus/?text=%5Bfoo%5D%0A%0A%3E%20first%20row%0A%3E%20%5Bfoo%5D%3A%20%2Furl%0A%3E%20third%20row)

**Comment by Feder1co5oave** [comment]
It's because [link definitions cannot interrupt a paragraph](http://spec.commonmark.org/0.28/#example-178).

**Comment by Feder1co5oave** [comment]
WAIT

I cannot reproduce the issue reported by @rndstr 

~~~
$ bin/marked
```ruby
def foo(x)
  return 3
end
```
^D
<pre><code class="lang-ruby">def foo(x)
  return 3
end
</code></pre>
~~~

Guys, this is about _codeblocks_, #974 was about _blockquotes_, very different beasts.

**Comment by Feder1co5oave** [comment]
Whereas *this* is a problem:
~~~
$ bin/marked
`
def ?`

`
ciao?`

^D

<p>`</p>
<p>def ?`</p>
<p><code>ciao?</code></p>
~~~

**Comment by Feder1co5oave** [comment]
Looks like this is a problem with the `paragraph` block rule.

**Comment by KostyaTretyak** [comment]
Now marked works this way:

```md
`
def ?`

```

Output:

```html
<p>`</p>
<p>def ?`</p>
```

With this pull request marked output:

```html
<p><code>def ?</code></p>
```

**Comment by joshbruce** [comment]
All right, I'm gonna just hold off until we answer a couple of things:

- [ ] This issue is unrelated to the commits being reverted (a new issue).
- [ ] Fixing this is something we should correct before performing the 0.3.10 release, which includes #991, which is related the highest priority XSS-related defects.

**Comment by KostyaTretyak** [comment]
This issue is unexpected related to #1007.

**Comment by Feder1co5oave** [comment]
Yes it is correlated, because regexp are built via a cascade of replaces. By changing the `blockquote` regexp, the `paragraph` one is now changed too, and it breaks

    `
    def`

into two separate paragraphs, so that the `code` inline rule cannot parse correctly the item.
I'm working around this issue. Still, my recent review of your #974 is still very valid and we need to take a look at the `blockquote` rule too, which is one of the most complicated ones, alas.

**Comment by KostyaTretyak** [comment]
> Still, my recent review of your #974 is still very valid

Agree. I did #974 when I studied `marked` just a couple of days.

**Comment by KostyaTretyak** [comment]
However, in two of your three comments, you were wrong with the rules. Now we know that my test edits were correct, but I was incorrect when I deleted rule with blockquote from `marked.js`.

**Comment by rndstr** [comment]
Okay, so  #1007 and 0.3.12 brought this back to the pre-0.3.9 behaviour.

Not sure I follow your discussion, feel free to close this (and re-open whatever #974 was meant to fix).

**Comment by joshbruce** [comment]
@rndstr: Thanks for the information. Gonna go ahead and close this per your comment.

Think we've completed all the issues related to XSS vulnerabilities; so, we can get to the other parser issues.
