### ISSUE TITLE
multiline HTML comments are not detected

### ISSUE THREAD

**Issue by ManfredSteiner** [chjj/marked#1016]
## Expectation

Multiline HTML comments should be handled as single line HTML comments. The `Renderer().html` function should be called. See also [multiline comments](https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.4).

## Result

At the moment (v0.3.7), single line HTML comments leads to a call of `Renderer().html` function with the comment in the parameter, but multiline comments are not detected as HTML fragment. Also html comments behind an image are not detected, an empty line must be inserted between image and comment.

Used options:  
`gfm: true, tables: true, breaks: true, pedantic: true, sanitize: false, smartLists: true, smartypants: false`

**Comment by ManfredSteiner** [comment]
A look into the `parser.parse(src)` gives the answer. Here an example, a single line 

`![image-text](image-link "image-title")<!-- html comment -->`

... will be tokenized as paragraph. The html part is now part of the paragraph item. The function `Renderer().paragraph` will be called. Inside this function the html part is detected and handled as tag, but the `Renderer().html function` is not called. A solution may be to define a sanitizer in options because this function is called when the tag is handled.

**Comment by ManfredSteiner** [comment]
Using the sanitizer is a possible work-arround. This is an example in typescript...

```
import * as marked from 'marked';
...
const x = marked.lexer(src, options);
const y = marked.parser(x, { sanitize: true, sanitizer: (html: string) => {
    // handle here the html tag
    return html;
} });
```

**Comment by Feder1co5oave** [comment]
Always remember to provide clear input-output samples when posting.
The only sample you provided (`![image-text](image-link "image-title")<!-- html comment -->`) does not work because html comments are parsed by marked in the same way that other html tags are parsed, i.e. as a block element. Also, html cannot interrupt a paragraph. So there should always be an empty line between content and html tags:

```markdown
![image-text](image-link "image-title")

<!-- html comment -->
```
~~~html
<p><img src="image-link" alt="image-text" title="image-title"></p>
<!-- html comment -->
~~~

**Comment by ManfredSteiner** [comment]
@Feder1co5oave, I don't know why more examples should be needed, there is one, you mentioned it. If you only take a view on if marked is rendering proper, you can say that it's working perfect. But if you insert some HTML elements in source, and callback function for html is available (`Renderer().html`) you would expect, that this callback function is executed. But in this special example it is not, caused by the reasons mentioned above (only handled as paragraph). One weakness of markdown is the missing definition / feature how to supply some more information inside the source (not rendered but available for more sophisticated systems). This missing leads to different solutions in different renderers. For example in Pandoc you use a { ... } behind a element. That's not handled in marked because it' s not an official markdown solution... 
I try to to solve that opportunity with html comments, because normally they don't cover the visible result. And therefore it would be an advantage not to insert some line feeds, which are only needed by the renderer, but covering the visible result (inserting some breaks).
But as I mentioned above, there is a work arround, using the sanitizer. With this solution all html elements are covered by a callback function. That's why I have closed this issue.

**Comment by joshbruce** [comment]
Just throwing copper on this.

I think this may also be one of those moments where defining scope might help. Markdown, from my perspective, is a way to write plain text that can be transformed by a parser into almost anything...not just HTML. Therefore, the more HTML-specific use cases we add to Markdown and Marked, the more tightly coupled the two become.

For example, I use iA Writer to write a lot of documents. The rendering engine there, may or may not, convert it to HTML to display the formatting of the text. Instead, it uses Markdown syntax to display the native macOS experience and styling of text.

Again, this may be a bit more high-level and abstract. And, the more HTML we put in our Markdown - the less portable it becomes, imho.
