### ISSUE TITLE
some links from Arch Wiki are broken after rendering

### ISSUE THREAD

**Issue by jiyinyiyong** [chjj/marked#102]
I used `marked` in my personal blog. Several links was rendered incrrectly.

There are really some incredible links on the Chinese version, such as:

```
https://wiki.archlinux.org/index.php/GNOME_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#.E9.80.9A.E8.BF.87.E4.BF.AE.E6.94.B9_settings.ini_.E6.94.B9.E5.8F.98_GTK3_.E4.B8.BB.E9.A2.98
```

And the rendering result on my blog:

https://raw.github.com/jiyinyiyong/blog2/master/posts/linux/arch-reinstall.md
http://blog.jiyinyiyong.info/linux/arch-reinstall.md

which was fine when I post that in a Github Issue:

https://github.com/jiyinyiyong/blog2/issues/1

**Comment by joshbruce** [comment]
#27 - while not strictly an extras feature, more of a "you should possibly move to markdown-it"
