### ISSUE TITLE
Strikethrough doesn't work

### ISSUE THREAD

**Issue by asharpe** [chjj/marked#1038]
## Expectation

I expect that the output would contain <s>deleted</s> (or equivalent markup).  eg.

```
$ ./bin/marked <<<'-deleted-'
<p><s>deleted</s></p>
```

## Result

```
$ ./bin/marked <<<'-deleted-'
<p>-deleted-</p>
```

## What was attempted

See also the result

```
$ ./bin/marked <<<' -deleted- '
<p> -deleted- </p>
```

**Comment by joshbruce** [comment]
What Markdown spec is this from? 

(Don’t remember seeing it in CommonMark or GFM. Closest I recall is CriticMark but we aren’t actively supporting it.)

**Comment by asharpe** [comment]
It doesn't appear to be in any spec that I can find!

Thanks for replying and apologies for the noise

**Comment by joshbruce** [comment]
@asharpe - No worries. Glad I wasn't hallucinating. ;)
