### ISSUE TITLE
Why is my h1 id is `-`，Chinese?

### ISSUE THREAD

**Issue by rhatyang** [chjj/marked#1042]
markdown: 
```md
### 原理
```
html:
```html
<h3 id="-">原理</h3>
```

why this id is `-`?

**Comment by joshbruce** [comment]
@rhatyang: Pretty sure it has to do with encoding of characters. Also thinking we will deprecating this behavior in the future as it is not explicitly called out in a spec (could be wrong). Therefore, recommend making a second pass to generate the ideas once the markup (HTML) has been generated.
