### ISSUE TITLE
Can I control the image or video size by this markdown?

### ISSUE THREAD

**Issue by tangdou1** [chjj/marked#1049]

**Comment by joshbruce** [comment]
@tangdou1: Not sure what you're asking exactly. Marked is not a flavor of Markdown - we are just a processor of Markdown.

We are focused primarily on two Markdown specifications: CommonMark and GFM (which is just CommonMark with some extra things).

Neither of these specifications allow for image or video size. Further, neither of these specifications support video. So, I don't believe you are looking for Marked.

Recommend determining your Markdown Flavor (https://github.com/commonmark/CommonMark/wiki/Markdown-Flavors) first. Then finding a processor that supports that flavor. Not sure which Markdown flavors, if any, have this capability.

http://spec.commonmark.org/0.28/#images
https://github.github.com/gfm/#images
