### ISSUE TITLE
Using marked `higlight` option from CLI?

### ISSUE THREAD

**Issue by JeanMertz** [chjj/marked#110]
Is it possible to generate highlighted fenced code blocks using the `--gfm` option and have it parse syntax highlighting?

I noticed `man marked` mentioning nothing about `--highlight` option. I did install `highlight.js` using `npm` so maybe it is possible somehow?

**Comment by matthewp** [comment]
I was thinking about what if you could provide options in a javascript file, that way you could write some code but still use the cli. You could do something like:

### options.js
```js
var highlight = require("highlight.js");

module.exports = {
  highlight: function(){
    return ...
  }
};
```

```
echo my-thing.md | marked --options path/to/options.js
```

**Comment by joshbruce** [comment]
#27
