### ISSUE TITLE
gfm style line breaks break html badly

### ISSUE THREAD

**Issue by midnightmonster** [chjj/marked#115]
With gfm line breaks enabled, code like this:

```
<table>
<tr><td>Hello</td></tr>
</table>
```

Will generate `<br>` tags at the end of each line, which creates invalid HTML and ugly rendering as the browser moves those extra line breaks _somewhere_.

github's actual github flavored markdown doesn't appear to have this unfortunate behavior.

**Comment by joshbruce** [comment]
#985
