### ISSUE TITLE
Include or link to CSS stylesheet in generated HTML

### ISSUE THREAD

**Issue by josdejong** [chjj/marked#119]
I was wondering whether there is a way to include a CSS stylesheet or a link to it in the HTML file generated from a markdown file. Looking at the available options this seems not to be implemented right now. 

Any thoughts on this?

**Comment by heyallan** [comment]
@yuchi Why do you use ending style tag?

**Comment by yuchi** [comment]
@heyallan this is a pretty old issue. What's your question more specifically?

**Comment by heyallan** [comment]
@yuchi Nevermind. Sorry. And thanks.

**Comment by dinglittle** [comment]
why it's closed 

what can I do , wan't render a html use styleSheet

**Comment by UziTech** [comment]
@dinglittle marked only converts markdown to html. If you want to add a stylesheet you will have to append it to the output.
