### ISSUE TITLE
Going down from a higher level of quoting

### ISSUE THREAD

**Issue by Mithgol** [chjj/marked#121]
This code works fine:

```
> First level of the quote.

>> Second level of the quote.

> First level again.
```

This code does also work fine:

```
> First level of the quote.
>
>> Second level of the quote.
>
> First level again.
```

This code has an issue:

```
> First level of the quote.
>> Second level of the quote.
> First level again.
```

(the last line is considered second level despite its single angular quote).

Note: GFM has the same issue.

**Comment by joshbruce** [comment]
Closing due to age and doubts about current applicability.
