### ISSUE TITLE
Would anyone consider implementing attribute lists ?

### ISSUE THREAD

**Issue by velsa** [chjj/marked#135]
Those greatly extend markdown functionality via single markup element.
For more details, see this extension: [Attribute Lists](http://pythonhosted.org/Markdown/extensions/attr_list.html)

**Comment by joshbruce** [comment]
Agree with @NoelDavies (also see #956). Not part of markdown and I think goes beyond the purpose of markdown:

Plain, human-readable, text converted to HTML; or, other output.

Closing.
