### ISSUE TITLE
Beauty spots: Dashes and Correct Quotes.

### ISSUE THREAD

**Issue by jashkenas** [chjj/marked#137]
I've absolutely been loving Marked lately. Its API is a pleasure to work with, and the ability to "lex" Markdown streams is incredibly handy.

But I am missing a thing or two from other Markdown parsers -- It would be great if Marked could be extended to convert `--` into an em-dash, and turn straight quotes surrounding words into correct curly quotes. So that you could write like this:

```
"Bollocks" -- he interrupted,
```

... and have it come out typographically correct.

**Comment by joshbruce** [comment]
Closing as merge was performed.
