### ISSUE TITLE
Host marked on CDNJS?

### ISSUE THREAD

**Issue by paranoiacblack** [chjj/marked#148]
Hi @chjj, would you mind it if marked was hosted by CDNJS (https://github.com/cdnjs/cdnjs#cdnjs-script-repository)? I think this would make it more accessible for different development playgrounds like Plunker or jsFiddle. I'm also working on a project licensed under the APGLv3 license (https://github.com/galah-group/galah) and we'd like to avoid licensing and attribution issues from packaging your library with the project when, in reality, we just want to pull it from a reliable source similar to jQuery.

Let me know if you have problems with this approach, and if there aren't, I could make the pull request to CDNJS for you if you want.

**Comment by chrisvfritz** [comment]
This is done, isn't it?

**Comment by paranoiacblack** [comment]
Sorry, not sure how I missed that this was closed.

**Comment by styfle** [comment]
@markedjs/marked 
I updated the repo url on CDNJS to our new org in this PR: https://github.com/cdnjs/cdnjs/pull/12580
