### ISSUE TITLE
Not separating code block

### ISSUE THREAD

**Issue by cadorn** [chjj/marked#150]
If I have two consecutive code blocks (delimited by a line of < 4 spaces indent) they get joined into one (periods denote spaces):

```
...CODE BLOCK 1

...CODE BLOCK 2
```

This is interpreted as if I wrote:

```
...CODE BLOCK 1
...
...CODE BLOCK 2
```

I realize github also joins these and that may be the desired behaviour in many cases but I need this to be parsed more strictly.

If the current behaviour is considered a feature and not a bug I wonder if we can add an option to parse more strictly. If this is not welcome how would I go about overriding the parsing or post-processing to add this for myself?

**Comment by joshbruce** [comment]
Closing as stale.
