### ISSUE TITLE
Setting Options with Grunt

### ISSUE THREAD

**Issue by Snugug** [chjj/marked#153]
I'm currently attempting to use Marked with Grunt/Grunt-Contrib-Jade and I seem unable to set my Marked options properly. How can I go about setting my options? The error is `ReferenceError: marked is not defined`

**Comment by joshbruce** [comment]
@scottgonzalez: Are you still around? See #956 

Curious about some of the history of this project and you seem like you might be a good person to talk with.

Closing as stale.
