### ISSUE TITLE
gfm + break differences to GitHub's rendering

### ISSUE THREAD

**Issue by Daiz** [chjj/marked#162]
With `gfm` and `break` enabled, there's some differences between marked and GitHub's own rendering. For example, the following:

```
test
* foo
* bar
```

Turns into this on GitHub:

> test
> - foo
> - bar

But in marked, it turns into this:

> test
> _foo_ bar

Now, putting an empty line between test and the first list entry solves the issue, but I think it'd make sense for this to work like it does on GitHub (at least when you have `gfm` and `break` enabled).

**Comment by joshbruce** [comment]
Believe marked is using the canonical markdown.pl as its reference, not GitHub Markdown; so, there will be differences.

It might be interesting, however, if people could switch base renderers.

Closing as stale.
