### ISSUE TITLE
Enable task lists (from GFM)

### ISSUE THREAD

**Issue by JoseTomasTocino** [chjj/marked#170]
GFM lets you create [Task Lists](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments) using the following syntax:

```
- [ ] First item
- [x] Checked item
```

Which renders the following:
- [ ] First item
- [x] Checked item

It would be great to have that feature in marked.

**Comment by joshbruce** [comment]
Closing as duplicate/similar
