### ISSUE TITLE
Table in div

### ISSUE THREAD

**Issue by cjloong** [chjj/marked#171]
Hi

I am finding 2 scenarios:-

1) Scenario 1
BEGIN:

<div class="scenario">

## Scenario
User can write specifications using tables.

|     ID   | Given    | When     | Then     | Actual |
| :------: | -------: | :------- | -------- | ------ |
| Cell 1   | Cell 2   | Cell 3   | Cell 4   |        |
| Cell 5   | Cell 6   | Cell 7   | Cell 8   |        |

</div>

ending with any text
END

2) Scenario2
Same as above but replace the "ending with any text" with a ##Heading.
This will not render the table correctly. The version I am playing around is master (as of yesterday)

**Comment by joshbruce** [comment]
Closing as stale. Please submit again, if you would like, are still using marked, and still experiencing the issue.

Also, see #956
