### ISSUE TITLE
parsing code is wrong?

### ISSUE THREAD

**Issue by spruce** [chjj/marked#172]
Hey,
I just tried to parse some things like 

``````
some text
 ``` #!/bin/sh

unset $(git rev-parse --local-env-vars)
cd ~/bar.com
git pull
 \``` (without that slash)
some text
``````

with [bitter](https://github.com/iizukanao/bitter), but I think it's more a problem of marked, because it showed no line as code. when I added back slashed to the end it parsed it correctly, but then there was a backslash at every line in the output-html

**Comment by joshbruce** [comment]
Closing as stale. Please resubmit if you are still using marked and experiencing the issue.
