### ISSUE TITLE
Marked help on Windows throws

### ISSUE THREAD

**Issue by poke** [chjj/marked#183]
Running marked with the `--help` or `-h` option fails on Windows with the following error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:975:11)
    at Process.ChildProcess._handle.onexit (child_process.js:766:34)
```

This happens because of [line 26](https://github.com/chjj/marked/blob/v0.2.9/bin/marked#L26) in `/bin/marked`:

```
  spawn('man',
    [__dirname + '/../man/marked.1'],
    options);
```

Here, marked tries to open up `man` which is a unix tool for reading help, and which is _not_ available on Windows.

I’d suggest either replacing this by some built-in way, or switching to some command line parser instead which already offers command line help (for example [node-optimist](https://github.com/substack/node-optimist)).

**Comment by joshbruce** [comment]
Closing as stale. Please resubmit, if necessary.

**Comment by poke** [comment]
Why was this closed exactly? Nothing has changed since I opened this issue.

**Comment by joshbruce** [comment]
Hey @poke, trying to catch up with the project, please see #956.

Is it still an issue for you after updating to marked 0.3.7?

**Comment by poke** [comment]
Ah, I see! Good to see the project gaining new momentum! :)

I haven’t used marked for quite a while, so I cannot comment on how it works right now. However, if I trust my past self (I kind of do) then the problem was that marked’s help ended up calling `man` to display the help (instead of doing that itself). And the [line that does that](https://github.com/chjj/marked/blob/v0.3.7/bin/marked#L26) is still in the current source. So I would make a *very safe guess*, that this problem is still current.

That being said, it’s really low-priority, so putting this very far back in the backlog is likely an appropriate action here.

**Comment by joshbruce** [comment]
@poke: Thanks. Part of going through the issues back-to-front is to also figure out how many people are still paying attention to this library. On NPM it's a very popular package; however, it's also been around for quite some time. So, thank you for the details and arriving at the same conclusion.

I will leave this issue closed because it is still referenced in 956, which also acts as a sort of consolidation approach.
