### ISSUE TITLE
Table parsing omits last row/last cell if only whitespace

### ISSUE THREAD

**Issue by chrisparnin** [chjj/marked#188]
Given the following markdown:

```
|                       | Do not Want | Sometimes | Always |
| --------------------- | ----------- | --------- | ------ | 
| Feature A |  |  |  |
| Feature B |  |  |  |
```

The following should be produced:

|  | Do not Want | Sometimes | Always |
| --- | --- | --- | --- |
| Feature A |  |  |  |
| Feature B |  |  |  |

Instead, the cells array omits the last column.

```
[ 'Feature A', '', '', '' ]
[ 'Feature B', '', '' ]
```

**Comment by joshbruce** [comment]
See #980
