### ISSUE TITLE
Parse more token types

### ISSUE THREAD

**Issue by jeromegn** [chjj/marked#194]
Such as images `![alt](url)`. I know they are considered a paragraph right now, but it would be nice to be able to intercept them and modify them

For instance, Github automatically parses them to return the raw URL from the repo for that image. Would be a nice feature for DocumentUp.

How about emojis? ;)

Basically those are two feature requests in DocumentUp. I might give it a shot myself, but I'm pretty busy at the moment and you know your codebase better! (Also, lack of tests is scaring me a little bit)

**Comment by wonderchang** [comment]
+1, need image token type, too.

**Comment by joshbruce** [comment]
Closing for now as may not fit with current actively pursued and supported specifications.

See #956 for details.
