### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by martindale** [chjj/marked#203]
`[naughty link](javascript:alert('xss'&#41;)`

I believe #109 may be related.

**Comment by chriddyp** [comment]
Note that the `sanitize` config argument will fix this: https://github.com/chjj/marked#sanitize

**Comment by matt-** [comment]
This is resolved with the sanitize option after:  https://github.com/chjj/marked/pull/592

**Comment by d-damien** [comment]
Note that stripping html is not enough to secure markdown, as explain in Showdown's article :
