### ISSUE TITLE
Poor performance in Firefox for large(ish) blocks of Markdown?

### ISSUE THREAD

**Issue by gitgrimbo** [chjj/marked#209]
The test:

http://jsperf.com/marked-regex-performance

Takes minutes on Firefox 22, but hardly any time at all in IE9 and Chrome 28.0.1500.72 m.

That test uses a version of marked.js from strapdown.js, but I have modified it to give each test and code block of the `Lexer.prototype.token` method its own named function. With these named functions, Firebug profiling will show the hotspots accurately.

This second test uses the latest version of marked.js (e59d5d0bc425af214676e6627e4f4b1410832e28, as of time of writing), but the results are the same:

http://jsperf.com/marked-regex-performance/2

As the Firebug profiling results show (from test 1), it seems the regex performance is poor when the strings are large.

Results of test 1 from jsperf.com (which took a total of 171 seconds):

![marked-firefox-jsperf-test](https://f.cloud.github.com/assets/1020541/875574/185decb0-f8a6-11e2-9eb6-a5f8bb22cabe.png)

These are the results from a local test I did (with the same Markdown content as the above tests):

![marked-firefox-perf-test](https://f.cloud.github.com/assets/1020541/875520/50c053ce-f8a4-11e2-9a92-16ed32385570.png)

This issue raises some points as I see it:
- Is it 'normal' to have Markdown blocks as large as this? It is in my case, I am working on a large document.
- Is Firefox (22) at fault? Chrome 28 and IE9 seem fine.
- Can marked.js somehow divide-and-conquer the Markdown content before it parses it? This would help FF enormously (in my case), and I believe would also improve Chrome and IE times (although to a much less extent).
- I have toyed with the idea of using web workers for the parsing. This would help the responsiveness of FF, but should not have an effect on the overall time taken to parse a single, large Markdown block. For multiple large blocks there would/should be a benefit on a multi-core machine.

**Comment by joshbruce** [comment]
Closing as stale.
