### ISSUE TITLE
Can't run Multiple Lexers

### ISSUE THREAD

**Issue by martindale** [chjj/marked#215]
This is a (non-functional) example of what I was attempting:

``` javascript
var lexers = {
    chat: new marked.InlineLexer([], {sanitize: true, smartypants:true, gfm:true})
  , content: new marked.Lexer({sanitize: true, smartypants:true, gfm:true})
};
// disable images, but allow links
lexers.chat.rules.link = /^\[((?:\[[^\]]*\]|[^\]]|\](?=[^\[]*\]))*)\]\(\s*<?([^\s]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*\)/;
```

Unfortunately, the `Lexer` and `InlineLexer` classes don't behave the same way, so...

``` javascript
var lexers = {
    chat: new marked.InlineLexer([], {sanitize: true, smartypants:true, gfm:true})
  , content: marked
};
// disable images, but allow links
lexers.chat.rules.link = /^\[((?:\[[^\]]*\]|[^\]]|\](?=[^\[]*\]))*)\]\(\s*<?([^\s]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*\)/;
```

Should work, by exposing `lexer.content( )` as a direct mapping to the non-inline Marked parser.  Unfortunately, it doesn't -- the editing of the InlineLexer via changing the rules also impacts the second marked function.

As a workaround, I attempted:

``` javascript
var otherMarked = require('marked');
var lexers = {
    chat: new eval(marked.InlineLexer)([], {sanitize: true, smartypants:true, gfm:true})
  , content: otherMarked
};
// disable images, but allow links
lexers.chat.rules.link = /^\[((?:\[[^\]]*\]|[^\]]|\](?=[^\[]*\]))*)\]\(\s*<?([^\s]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*\)/;
```

...to no avail.  Perhaps we should unify the lexer structures and/or standardize how they are exposed?

**Comment by joshbruce** [comment]
Closing as stale. Please see #956 and please re-submit if you are still using and marked and the defect is still present.
