### ISSUE TITLE
Code blocks rendered only using <pre> and not with both <code> and <pre>

### ISSUE THREAD

**Issue by julianlam** [chjj/marked#224]
This may have been mentioned in [an earlier bug report](https://github.com/chjj/marked/issues/37), although I don't think it's directly related...

The [markdown spec](http://daringfireball.net/projects/markdown/syntax#precode) says that the contents in code blocks (those starting with four spaces - no mention of the gfm code fences, of course) should be wrapped in `<pre><code>`, but marked is currently wrapping our codeblocks in a single `<pre>`.

Not really an issue, except when coupled with Twitter Bootstrap, you get something that looks like this:

![](https://github-camo.global.ssl.fastly.net/7e9e44ec6e207c30d3a9854e6cd939b4b4ed39df/687474703a2f2f692e696d6775722e636f6d2f64464a675571662e706e67)

**Comment by joshbruce** [comment]
Closing as stale. See #956 

Please let me know if you are still using marked and are having this issue.
