### ISSUE TITLE
Nested blockquotes are not rendered properly

### ISSUE THREAD

**Issue by anselmh** [chjj/marked#225]
Hi,

I recently switched to marked.js for one of my projects. There are a lot of nested quotes which unfortunately are not rendered properly by marked.js.

Input:

```
>> Nested 2nd level Quote with some text
>> in here over multiple lines.
> now following first-level quote which is 
> a reply to the second level quote
> but is rendered as second level.
```

Output:

```
<blockquote>
     <blockquote>All Content regardless of their nesting described after line 1 appears in here.
     </blockquote>
<blockquote>
```

Any chance you can fix this soon or does someone know how to achieve the correct result here?

**Comment by joshbruce** [comment]
See #956 

Closing as stale
