### ISSUE TITLE
HTML block parsing in consistency

### ISSUE THREAD

**Issue by roydukkey** [chjj/marked#236]
Here is what I don't understand: Why does marked parse some features in HTML blocks and not others?
#### Example 1

```
 <div>
 ## Markdown header
 *Markdown header*
 **Markdown header**
 </div>
```

**Outputs**

```
 <div>
 ## Markdown header
 <em>Markdown header</em>
 <strong>Markdown header</strong>
 </div>
```
#### Example 2

```
 <div>
 ## Markdown header
 *Markdown header*
 **Markdown header**
 </div>
 <script>
 var nubbin;
 </script>
```

**Output**

```
 <p><div></p>
 <h2 id="markdown-header">Markdown header</h2>
 <p><em>Markdown header</em>
 <strong>Markdown header</strong>
 </div></p>
 <script>
 var nubbin;
 </script>
```

I would like, most, to see these issues being fixed, allowing HTML blocks to be truly untouched. Then, begin further discussion on other topics like #66, #133, #115.

**Comment by donleyp** [comment]
Is there a way to disable this "extension"?

**Comment by joshbruce** [comment]
See #956

Closing as stale, please open a new issue with reference is you are still using marked and have the same request. Thank you.

@UziTech: Here's one of those moments I'm curious about regarding the continued use of marked "in the wild". Marked looks unkempt according to the cross-project PR referenced above. Having said that, the PR is still open after a year. And that project is starting show signs of either be stale, completely stable, or unused.

Given what I assume to be low usage numbers for Elm, in general, I would not be surprised. Anyway, just considering the possibilities of false positives for marked's prevalence in the wild on active projects.
