### ISSUE TITLE
Add pedantic sub configuration

### ISSUE THREAD

**Issue by roydukkey** [chjj/marked#239]
How do you feel about allowing pedantic configuration at sub-level? This wouldn't affect the current allotment for `pedantic: true` but would allow additional options:

```
 pedantic: {
      ignoreHtml: true,
      outdent: true,
      code: true,
      inline: true
 }
```

What do you think are appropriate option names?

In reference to #236.

**Comment by joshbruce** [comment]
@UziTech: I'm trying to cull down about a page of issues a day. Mostly closing things I think are stale. Reopening others if need be.

I'm gonna that here per the focus being on catching up then figuring out what to do next.

For this one, I don't know what pedantic is...I'm not sure if conflicts with the focus being on the CommonMark and GFM specifications. This also just seems like an exposure of something already there...pedantic detailed configuration, yeah?
