### ISSUE TITLE
Add support for description lists

### ISSUE THREAD

**Issue by adius** [chjj/marked#254]
http://kramdown.rubyforge.org/syntax.html#definition-lists

(In html4 it was called definition list, in html5 its called description list)

**Comment by nschneid** [comment]
+1 I find that definition lists are incredibly useful!

**Comment by ljl** [comment]
+1

**Comment by joshbruce** [comment]
We are currently targeting two Markdown specifications. If you can find where the syntax of these two specifications allow `dl`, please open a new issue with this reference. See #956 - Thank you.

**Comment by Crystal-RainSlide** [comment]
Now this may be implemented as a [extension](https://marked.js.org/using_pro) ([template](https://github.com/markedjs/marked-extension-template)) of Marked.

There is https://github.com/xiaoliwang/markedjs-extra for some reference, but it's pretty old.

Also see issue https://github.com/markedjs/marked/issues/27.
