### ISSUE TITLE
Feature request: Checkboxes and radioboxes

### ISSUE THREAD

**Issue by iegik** [chjj/marked#263]
Sometimes need show some configuration visually, there is checked/unchecked options:

```
[ ] some text
[x] some text
```

should produce:

```
<input type="checkbox" /> some text
<input type="checkbox" checked /> some text
```

Also can do the same for "Radio boxes":

```
( ) some text
(o) some text
```

should produce:

```
<input type="radio" /> some text<br/>
<input type="radio" checked /> some text
```

**Comment by gkoberger** [comment]
+1 to this

**Comment by joshbruce** [comment]
See #956 

Focusing on CommonMark and GFM specifications. Don't believe form inputs are part of either of those specifications (GFM task-lists - checkboxes - are an extension, not our focus at this time).
