### ISSUE TITLE
Feature request: Textarea

### ISSUE THREAD

**Issue by iegik** [chjj/marked#265]
Following #263 and #264, we can also implement textarea!
Here is a simple table:

```
| Some      | Text
|---------- | -------
| some      | text

<table>
  <thead>
    <tr><th>Some</th><th>Text</th></tr>
  </thead>
  <tbody>
    <tr>some<td></td><td>text</td></tr>
  </tbody>
</table>
```

and here is the textarea field:

```
| ----------
| Some text

<textarea>Some text</textarea>
```

As you see the only different is, that table has headers and more than one column :)

**Comment by joshbruce** [comment]
See #956 

Focusing on CommonMark and GFM specifications. Don't believe form inputs are part of either of those specifications (GFM task-lists - checkboxes - are an extension, not our focus at this time).
