### ISSUE TITLE
Implement markdown extra features

### ISSUE THREAD

**Issue by dmmalam** [chjj/marked#27]
Thanks for the excellent md parser!

There are a bunch of various extensions to markdown
eg
http://freewisdom.org/projects/python-markdown/Extra
http://michelf.com/projects/php-markdown/extra/
http://maruku.rubyforge.org/proposal.html

While not all are exactly critical, things like super/subscript, tables, definition lists, abbreviations can go a long way to make writing md documents easier. 

Also simple transformations (like texttile http://rpc.textpattern.com/help/?item=intro) can make the text much more readable
For example
... -> …
' ' -> ‘ ’
" " -> “ ”
-- -> –
(c) -> ©
(r) -> ®
and so on .

Ideally the goal should be to never write pure html for any typographical feature.

**Comment by SenshiSentou** [comment]
Just wanted to ask if custom extensions have since been implemented. I would specifically like to add sub- and superscript support to my project.

**Comment by joshbruce** [comment]
@SenshiSentou: I cannot answer this directly as I'm fairly new around here. See #956

Having said that, I don't know enough about markdown-it to determine if it has the same vision; or, if marked has (or could have) a fundamentally different approach to achieving that mission.

@UziTech: Thoughts??

**Comment by UziTech** [comment]
At this point I feel like anyone who wants these extensions should move to markdown-it and this package should be only about GFM and CommonMark and bug fixes.

If this is maintained further it would probably be best to create an extension system instead of adding all of these features to marked directly.

**Comment by UziTech** [comment]
Marked does provide access to the [lexer and parser](https://github.com/chjj/marked#pro-level) for anyone who wants to create a wrapper with any of these options.

**Comment by joshbruce** [comment]
@UziTech: Just to make sure I'm picking up what you're putting down:

GFM = GitHub Flavored Markdown
CommonMark = http://commonmark.org an attempt at standardizing the syntax, but guarding extension based on demand...some components of MultiMarkdown, for example.

Is that about right?

If so, I concur with this assessment. Maybe markdown-it would actually use Marked as its parser/compiler...offering all the bells and whistles.

**Comment by UziTech** [comment]
Ya basically at this time we should focus on getting the number of issues down and making sure `marked` works well for all the packages that already depend on it and put off adding any new functionality.

**Comment by joshbruce** [comment]
Closing see previous conversation.

**Comment by Crystal-RainSlide** [comment]
Now this may be implemented as a [extension](https://marked.js.org/using_pro) ([template](https://github.com/markedjs/marked-extension-template)) of Marked.

There is https://github.com/xiaoliwang/markedjs-extra for some reference, but it's pretty old.
