### ISSUE TITLE
Fix code in tables

### ISSUE THREAD

**Issue by iegik** [chjj/marked#285]
```
| Column 1 | Column2     | Column 3 |
| -------- | ----------- | -------- |
| text     | `some|code` | text     |
```

| Column 1 | Column2 | Column 3 |
| --- | --- | --- |
| text | `some|code` | text |

**Comment by joshbruce** [comment]
See #980

**Comment by Feder1co5oave** [comment]
I'm not sure if the `|` inside the codespan should be escaped or not, here.
