### ISSUE TITLE
Links (ahref) not parsed properly

### ISSUE THREAD

**Issue by AmarPrabhu** [chjj/marked#297]
The default test cases for links fails with unexpected results:
11. double_link.text failed at offset 46. Near: `:<ahref="http://example.com/"><ahref="http://example.com/">h`.

Got:
`:<ahref="http://example.com/"><ahref="http://example.com/">h`

Expected:
`:<ahref="http://example.com/">http://example.com/</a>.</p><p`

**Comment by joshbruce** [comment]
Closing as stale. Please open a new ticket, if need be.

See #956
