### ISSUE TITLE
don't add GFM line breaks inside non-paragraph content

### ISSUE THREAD

**Issue by chrisvasz** [chjj/marked#299]
When rendering a document with GFM line breaks turned on, the following

```
# hello

<ul>
  <li>1</li>
  <li>2</li>
</ul>

# world
```

renders as

```
<h1 id="hello">hello</h1>
<ul><br>  <li>1</li><br>  <li>2</li><br></ul>

<h1 id="world">world</h1>
```

According to this line from the [GFM help page](https://help.github.com/articles/github-flavored-markdown) (emphasis added):

> GFM treats newlines in **paragraph-like content** as real line breaks, which is probably what you intended.

... the `<br>` tags should only be added in "paragraph-like content".

**Comment by joshbruce** [comment]
#985
