### ISSUE TITLE
GFM: Absolutify relative links in markup files

### ISSUE THREAD

**Issue by robertkowalski** [chjj/marked#320]
Hi,

in https://github.com/isaacs/npm-www/issues/517 @sindresorhus is mentioning support from GFM for relative image paths (https://github.com/blog/1395-relative-links-in-markup-files)

In npm-www we are taking the `readme.md`, which is often hosted on GitHub, too and are rendering markdown for the detail page of the package from it. Sometimes the readme makes use of the relative-img-path-feature from GitHub (see issue).

Turns out, that supporting converts (from relative paths to absolute ones) for images which are embedded html is not that easy: the custom html renderer is ignoring the img tag (https://github.com/chjj/marked/blob/master/lib/marked.js#L50) and they are included in the `paragraph`-callback with all other tags.

In order to support relative img paths from GFM on npm-www it would be nice to have a  easy way to convert the paths at the rendering stage or before.

**Comment by joshbruce** [comment]
See #956 

See #958 - Please help on that PR, if you still wish to see this make into an actual release, we can't merge and release 0.3.9 without fixing what's going on there.
