### ISSUE TITLE
don't create IDs for headers by default

### ISSUE THREAD

**Issue by jonathanong** [chjj/marked#326]
since we can create custom renderers now, i don't see the point of including this by default. the default renderer should be minimal and simple, and it would close plenty of issues surrounding this issue.

**Comment by ArmorDarks** [comment]
I also think it should be switched off by default, since it injects unexpected ids into markup and seems like pretty much opinionated option.

Besides, it doesn't work with non-latin headers, which results in quite horrible ids

**Comment by the0neWhoKnocks** [comment]
+1

It's far too easy to create issues on a page with dynamically generated ids. At the least, if it's not going to removed, it should be automatically prefixed with `marked-` or `md-`. Something to set it apart from other ids that may already be on the page. If a plugin or framework is asserting it's opinions on a dev, it should at least do so transparently & in a non-conflicting manor.

Aside from that, and not being able to easily add new custom token rules (not just overriding current ones); this is some fine code and has saved me time implementing a new MD editor. So thank you for your efforts, they are appreciated.

**Comment by brunowego** [comment]
+1

**Comment by fedesilvaponte** [comment]
+1

**Comment by Dafrok** [comment]
+1

**Comment by luketeaford** [comment]
Would love this feature -- the ID should be optional because there are many scenarios where it is obtrusive.

**Comment by ahuglajbclajep** [comment]
This is easy to achieve.
If node >=4.0.0,
```js
const marked = require('marked');

const renderer = new marked.Renderer();
renderer.heading = (text, level) => `<h${level}>${text}</h${level}>`;
marked.setOptions({renderer});
```
Have a nice Markdown life!

**Comment by joshbruce** [comment]
See #956 

If you are still interested in this, comment.

**Comment by alberto56** [comment]
Just sharing how I obtain IDs in the browser

```
            const renderer = new marked.Renderer();
            renderer.heading = function(text, level) {
              const id = text.text.toLowerCase().replace(/[^a-zA-Z0-9]+/g, '-');
              return `<h${text.depth} id="${id}">${text.text}</h${text.depth}>`;
            }
            marked.setOptions({renderer});
```
