### ISSUE TITLE
Handling of <pre> content is not uniform

### ISSUE THREAD

**Issue by sklise** [chjj/marked#337]
The following:

```
<pre>
width: 100%; /* comment */
</pre>
```

is rendered by marked as:

```
width: 100%; /* comment */
```

However, if the `pre` tag is inside another block element:

```
<div>

<pre>
width: 100%; /* comment */
</pre>

</div>
```

the output is:

```
<div>

<pre>
width: 100%; /<em> comment </em>/
</pre>

</div>
```

So it seems that `<pre>` tags are not ignored when inside another block element.

Definitely an extreme edge case when writing markdown, but also an inconsistency.

**Comment by joshbruce** [comment]
#983

**Comment by Feder1co5oave** [comment]
I cannot reproduce this on current master v0.3.12:
~~~
$ bin/marked 
<pre>
width: 100%; /* comment */
</pre>
^D
<pre>
width: 100%; /* comment */
</pre>
~~~
