### ISSUE TITLE
A marked tokens should have line / character number

### ISSUE THREAD

**Issue by andrewtch** [chjj/marked#338]
For any connection back from generated HTML to markdown (check ghost.org markdown editor, for example) a line number and character number of markdown token should be passed to the renderer. 

I'll make a pull request implementing this in some days.

**Comment by akfish** [comment]
Wow! After almost 2 years, I did nothing about it! NOTHING! 
Maybe I'll sit around for another 2 years.

**Comment by andrewtch** [comment]
...I was just cleaning the issues on github, so much reaction ....

**Comment by akfish** [comment]
Well, I was just amazed by how lazy I've been. And now I'm going back to my sitting-around with all my half-not-done projects.
