### ISSUE TITLE
Support image resizing

### ISSUE THREAD

**Issue by SimonCropp** [chjj/marked#339]
is there any support for changing the size of an image. or do we have to drop back to html?

**Comment by timlevett** [comment]
+1

**Comment by eugeniop** [comment]
+1

**Comment by ponyesteves** [comment]
+1

**Comment by isiahmeadows** [comment]
In my particular case, where I already had to modify the renderer to properly highlight a code block ([known issue](https://github.com/chjj/marked/pull/418)), I just added another method to do just this.

```js
// Super simple sanitizer
function sanitize(str) {
    return str.replace(/&<"/g, function (m) {
        if (m === "&") return "&amp;"
        if (m === "<") return "&lt;"
        return "&quot;"
    })
}

/**
 * Make Marked support specifying image size in pixels in this format:
 *
 * ![alt](href = x WIDTH "title")
 * ![alt](href = HEIGHT x "title")
 * ![alt](href = HEIGHT x WIDTH "title")
 *
 * Note: whitespace from the equals sign to the title/end of image is all
 * optional. Each of the above examples are equivalent to these below,
 * respectively:
 *
 * ![alt](href =xWIDTH "title")
 * ![alt](href =HEIGHTx "title")
 * ![alt](href =HEIGHTxWIDTH "title")
 *
 * Example usage:
 *
 * ![my image](https://example.com/my-image.png =400x600 "My image")
 */
renderer.image = function (href, title, alt) {
    var exec = /\s=\s*(\d*)\s*x\s*(\d*)\s*$/.exec(href)
    var res = '<img href="' + sanitize(href) + '" alt="' + sanitize(alt)
    if (exec && exec[1]) res += '" height="' + exec[1]
    if (exec && exec[2]) res += '" width="' + exec[2]
    return res + '">'
}
```

It takes advantage of the fact Marked parses images this way:

```md
![img](http://foo.com/img.png =100x300)
![img](http://foo.com/img.png =100x300 "foo")
```

```html
<p><img src="http://foo.com/img.png =100x300" alt="img"></p>
<p><img src="http://foo.com/img.png =100x300" alt="img" title="foo"></p>
```

Do note that you can't flip the two:

```md
![img](http://foo.com/img.png "foo" =100x300)
```

```html
<p><img src="http://foo.com/img.png &quot;foo&quot; =100x300" alt="img"></p>
```

---

Although, most definitely +1 @SimonCropp on a "useful renderer overrides" list.

@chjj What do you think of both of these (my idea and the "useful renderer overrides" list)?

**Comment by mustafakasap** [comment]
+1

**Comment by mustafakasap** [comment]
Direct HTML coding is not working in MAC VSCode also.

this is what I tried: 
<img src="./imgs/1.5.i001.png" alt="Drawing" style="width: 200px;"/>

**Comment by vithar** [comment]
https://github.com/chjj/marked/pull/535

**Comment by uptownhr** [comment]
@isiahmeadows i thought i was going crazy! I know this is months old but your code used href for image! Thanks for the code either way. Works like a charm after you change href to src.

**Comment by isiahmeadows** [comment]
Oops... Oh well. Sorry about that!

**Comment by joshbruce** [comment]
See #956 

Closing as complete or stale

**Comment by carloslfu** [comment]
Is this feature implemented?

**Comment by isiahmeadows** [comment]
@carloslfu [Does my workaround work for you?](https://github.com/markedjs/marked/issues/339#issuecomment-172230403)

**Comment by fieldju** [comment]
> @carloslfu [Does my workaround work for you?](https://github.com/markedjs/marked/issues/339#issuecomment-172230403)

@isiahmeadows 

```typescript
import marked from 'marked';

const renderer = new marked.Renderer();

function sanitize(str: string) {
  return str.replace(/&<"/g, function (m) {
    if (m === "&") return "&amp;"
    if (m === "<") return "&lt;"
    return "&quot;"
  })
}

renderer.image = function (src, title, alt) {
  const exec = /\s=\s*(\d*)\s*x\s*(\d*)\s*$/.exec(src)
  let res = '<img src="' + sanitize(src) + '" alt="' + sanitize(alt)
  if (exec && exec[1]) res += '" height="' + exec[1]
  if (exec && exec[2]) res += '" width="' + exec[2]
  return res + '">'
}

marked.setOptions({
    renderer: renderer
  })

log.info(marked.parse(`![img](../assets/image/some-image.png =100x100)`))
log.info(marked.parse('![img](http://foo.com/img.png =100x300)'))
```

yields

```
<p>![img](../assets/image/some-image.png =100x100)</p>
<p>![img](<a href="http://foo.com/img.png">http://foo.com/img.png</a> =100x300)</p>
```

Am I missing something here, because you work around doesn't seem to be working as I expected?

**Comment by isiahmeadows** [comment]
@carloslfu That's a different bug, which has nothing to do with this. Instead, for you, Marked isn't even expanding images in the first place. I'd suggest file another bug (if one doesn't already exist) and include that snippet. Also, be sure to include your Marked version.

(I'm not a contributor to this project, just a user.)

**Comment by UziTech** [comment]
@fieldju You could use the title but you have to put quotes around the dimensions

```js
import marked from 'marked';

const renderer = new marked.Renderer();

function sanitize(str: string) {
  return str.replace(/&<"/g, function (m) {
    if (m === "&") return "&amp;"
    if (m === "<") return "&lt;"
    return "&quot;"
  })
}

renderer.image = function (src, title, alt) {
  const exec = /=\s*(\d*)\s*x\s*(\d*)\s*$/.exec(title)
  let res = '<img src="' + sanitize(src) + '" alt="' + sanitize(alt)
  if (exec && exec[1]) res += '" height="' + exec[1]
  if (exec && exec[2]) res += '" width="' + exec[2]
  return res + '">'
}

marked.setOptions({
    renderer: renderer
  })

log.info(marked.parse('![img](../assets/image/some-image.png "=100x100")'))
log.info(marked.parse('![img](http://foo.com/img.png "=100x300")'))

// <p><img src="../assets/image/some-image.png" alt="img" height="100" width="100"></p>
// <p><img src="http://foo.com/img.png" alt="img" height="100" width="300"></p>
```

**Comment by isiahmeadows** [comment]
@UziTech I've not had that problem, and that code is a snippet taken directly from production (my personal blog).

**Comment by UziTech** [comment]
@isiahmeadows what version of marked are you using? it looks like the link regex changed in v0.4.0 to not allow spaces in the url

[demo](https://marked.js.org/demo/?outputType=html&text=!%5Bimg%5D(..%2Fassets%2Fimage%2Fsome-image.png%20%3D100x100)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.4.0)

**Comment by isiahmeadows** [comment]
@UziTech Okay, so looks like I'll need to modify things locally, then. I was on 0.3.x when I wrote that. 🙂

**Comment by fieldju** [comment]
@UziTech @isiahmeadows, I tested things locally and any of the recent versions this work around doesn't work.

I had to go back to a version from 2 years ago to get this to work.

Does anyone know how to re-size images with the current'ish releases?

**Comment by UziTech** [comment]
@fieldju [this](https://github.com/markedjs/marked/issues/339#issuecomment-479347433) works with the current version

**Comment by fieldju** [comment]
> @fieldju [this](https://github.com/markedjs/marked/issues/339#issuecomment-479347433) works with the current version

ok, thanks that did work!

**Comment by Oxfos** [comment]
In my code I added a '*' in the regex (to make the 'x' and what comes after optional):
`const exec = /=\s*(\d*)\s*x*\s*(\d*)\s*$/.exec(title)`
This allows submitting only one img size dimension (height, if you keep @UziTech code), the other dimension being set automatically to 'auto' which renders the native image size ratios.

**Comment by peterpeterparker** [comment]
Thx for the solution 👍 

I made the following change to the regex to accept units (because I need units), to support only a parameter if needed and to separate values with comma

```
const exec = /=\s*(\d*(?:px|em|ex|ch|rem|vw|vh|vmin|vmax|%))\s*,*\s*(\d*(?:px|em|ex|ch|rem|vw|vh|vmin|vmax|%))*\s*$/.exec(title);
```

can be use with

```
![](notifications.jpg "=100px,20px")
![](notifications.jpg "=100rem,20vh")
![](notifications.jpg "=100px")
![](notifications.jpg)
```

**Comment by albfan** [comment]
This solutions still put the `=heightxwidth` in img src so  I tweak it a little:

```
    const renderer = new marked.Renderer();

    function sanitize(str) {
      return str.replace(/&<"/g, function (m) {
        if (m === "&") return "&amp;"
        if (m === "<") return "&lt;"
        return "&quot;"
      })
    }

    renderer.image = function (src, title, alt) {
      const parts = /(.*)\s+=\s*(\d*)\s*x\s*(\d*)\s*$/.exec(src)
      let res = '<img src="' + sanitize(src) + '" alt="' + sanitize(alt)
      if (parts) {
        res = '<img src="' + sanitize(parts[1]) + '" alt="' + sanitize(alt)
        if (parts[2]) res += '" height="' + parts[2]
        if (parts[3]) res += '" width="' + parts[3]
      }
      return res + '">'
    }

    marked.setOptions({
      renderer: renderer
    })
```

**Comment by caub** [comment]
Trying with marked@^4

But it's not even entering the renderer: https://runkit.com/caub/629a771c7669d70009acded9

What's wrong?

```js
const marked = require('marked');

marked.use({
  renderer: {
    image(src, title, alt) {
      console.log('---', src, alt, title);
      const [width, height] = title.startsWith('=') ? title.slice(1).split('x').map(v => v.trim()).filter(Boolean) : [];
      return `<img src="${src}" alt="${alt}"${width ? ` width="${width}"${height ? ` height="${height}"` : ''}` : ''}>`;
    }
  }
})

const text = `![foo](foo.jpg =100x80)`;
console.log(marked.parse(text));
```

**Comment by UziTech** [comment]
@caub it looks like that was fixed to act more like [CommonMark](https://spec.commonmark.org/dingus/?text=!%5Bfoo%5D(foo.jpg%20%3D100x80)) in v0.4.0

It does work to put quotes (`"`) around the title.

```markdown
![foo](foo.jpg "=100x80")
```

https://runkit.com/uzitech/629aca6bbf7fb700099e25fc
