### ISSUE TITLE
Ordered lists separated by a single space from unordered lists show up as unordered

### ISSUE THREAD

**Issue by xirzec** [chjj/marked#340]
```
* first thing
+ another thing
- yet another thing

1. meh
1. foo
1. bar
```

Generates HTML that looks like:

![actual](https://f.cloud.github.com/assets/639216/2033968/235cecce-8924-11e3-8d3b-76e4187bf423.png)

Whereas it should look like:

![expected](https://f.cloud.github.com/assets/639216/2033974/2ae3cdf0-8924-11e3-9047-b788b0ca0208.png)

**Comment by joshbruce** [comment]
#982
