### ISSUE TITLE
Heading-less Tables

### ISSUE THREAD

**Issue by calvinjuarez** [chjj/marked#349]
Any chance of having a way to make heading-less tables?

|  |  |
| --- | --- |
| this is the best | we can do atm |

---

As far as a proposed solution, I'd say the best way would be to omit the heading row but keep the alignment definition row, like this:

``` markdown
--- | ---
table | data
```

**Comment by joshbruce** [comment]
See #980

**Comment by Feder1co5oave** [comment]
This is not supported by gfm, and we try to comply only with it at the moment
