### ISSUE TITLE
how to extend marked

### ISSUE THREAD

**Issue by bvallelunga** [chjj/marked#359]
I would like to do like github has with `@person`. How do I extend marked to look for the `@person`? Thanks for all the help and awesome module.

**Comment by activey** [comment]
+10000

**Comment by adam-lynch** [comment]
You could override all renderer methods. Then inside each, parse the mentions, then call the original renderer methods and return its result.

**Comment by tunnckoCore** [comment]
@activey use @markdown-it or `jonschlinkert/remarkable` or `bevacqua/megamark` (is awesome!), `ForbesLindesay/supermarked` and etc

`marked` is almost dead. Markdown-it is upstream from half year or so. It is highly customizeable, and have plugins in npm https://www.npmjs.com/browse/keyword/markdown-it

**Comment by activey** [comment]
Oh, thanks for the info :D

**Comment by joshbruce** [comment]
Closing as stale, resolved, and out of scope at present. See #956
