### ISSUE TITLE
github style --

### ISSUE THREAD

**Issue by bootstraponline** [chjj/marked#360]
`--` is rendered in a certain way on github.com and marked doesn't parse it.

Examples:
## 
## 
##

**Comment by joshbruce** [comment]
Closing as not descriptive enough and no reference to the two specfiications supported by Marked. See #956

**Comment by bootstraponline** [comment]
It's listed in GFM under `4.1Thematic breaks`

- https://github.github.com/gfm/.

I provided an example in the description. `--`

**Comment by joshbruce** [comment]
The example in the comment was two hashes - which would be a level-two header.

Does Marked now render the triple-hyphen as an HR tag?

Please use something like:

## Given this Markdown:

`---`

## Expected

`<hr>`

## Got

`-<em>-</em>` (or whatever)

**Comment by bootstraponline** [comment]
I don't remember. I opened this issue four years ago. If marked produces the same HTML as github for breaks, as documented at that link, then we're good.

**Comment by joshbruce** [comment]
Fair. And, honestly, I don't know. I'm not the most familiar with the library...just trying to help coordinate things in the community. An ambassador, so to speak.

**Comment by bootstraponline** [comment]
Cool. I appreciate your efforts to improve the library.
