### ISSUE TITLE
Document browser support

### ISSUE THREAD

**Issue by jameshfisher** [chjj/marked#367]
The documentation does not say anything about browser support. As such, I initially dismissed marked as an option for my project.

However, apparently it does have browser support:
- https://github.com/chjj/marked/issues/62
- https://github.com/chjj/marked/blob/master/lib/marked.js#L783-791

but this is useless unless this is advertised.

Additionally, minified versions of the library should be available for use in the browser.

**Comment by joshbruce** [comment]
Seems to have been resolved by merge. Closing.
