### ISSUE TITLE
highlight not defined

### ISSUE THREAD

**Issue by wvandaal** [chjj/marked#375]
I'm experiencing a subtle bug when using marked in conjunction with highlight.js. I am using your double-escaping workaround for code highlighting to great effect: [optional escape #6](https://github.com/chjj/marked/issues/6), but when I attempt to begin a markdown string with code, as opposed to the other semantic tags, I get an `Uncaught ReferenceError: highlight is not defined`. Here is the code that I am using:

```
$(function(){
  var _marked;

  // Set highlighting options for marked
  marked.setOptions({
    highlight: function (code) {
      return hljs.highlightAuto(code).value;
    }
  });

  _marked = marked;

  // Rewrite marked to prevent double-escaping of code blocks
  window.marked = function(text) {
    var tokens = _marked.lexer(text),
        l      = tokens.length;

    for (var i = 0, tok = tokens[i]; i < l; i++) {
      if (tok.type === "code") {
        tok.text = highlight(tok.text, tok.lang);
        tok.escaped = true;
      }
    }

    return _marked.parser(tokens); 
  };
});
```

As an example,  the following markdown will be rendered properly, and without incident:

``````
# Some header
```
puts 'hello'
```
``````

whereas this throws an error:

``````
```
puts 'hello'
```
``````

Any thoughts on what the problem might be here?

**Comment by joshbruce** [comment]
#983
