### ISSUE TITLE
How do I make a new renderer and lexer rule?

### ISSUE THREAD

**Issue by winduptoy** [chjj/marked#379]
@chjj The README doesn't specify how to add a new rule. Here's what I've tried:

```
var renderer = new marked.Renderer();
renderer.threeDollars = function() {
    return 'Three Dollars';
}

var lexer = new marked.Lexer({smartypants: true, renderer: renderer});
lexer.rules.threeDollars = /\$\$\$/;

return marked.parser(lexer.lex(text));
```

When my text input is `$$$`, the output is not `Three Dollars`. When I log `lexer.lex(text)` my input is identified as a `paragraph`, not `threeDollars`. How do I make my new rule work and how do I order which rules take precedence over others?

Thanks for your help.

**Comment by joshbruce** [comment]
Closing as out of scope for now. See #956
