### ISSUE TITLE
Source Map - Feature request

### ISSUE THREAD

**Issue by am11** [chjj/marked#382]
[Source maps](https://github.com/madskristensen/WebEssentials2013/issues/830) are very useful for [browser debugging](https://wiki.mozilla.org/DevTools/Features/SourceMap) and [editor enhancements](https://github.com/madskristensen/WebEssentials2013/issues/830) when implementing source-to-source trans-compilers.

Unfortunately, there is no markdown compiler out there which generates V3 source-maps, as CSS (LESS & SASS) and JavaScript (CoffeeScript & TypeScript) preprocessors do.

Please implement this feature in **marked**, so editors and browsers can take advantage of it.

Thanks in anticipation.

**Comment by Feder1co5oave** [comment]
I leave this here hoping it'll be helpful sometime in the future.
Anyone wanting to implement this should better take a look at the [source map specification](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit) and  use a [source map generator library](https://github.com/mozilla/source-map).

**Comment by joshbruce** [comment]
See #956 

Closing as complete or stale
