### ISSUE TITLE
Browser crashes when resolve the following characters

### ISSUE THREAD

**Issue by why520crazy** [chjj/marked#386]
we use marked.js to convert markdown input，when input following characters：
"_Result
__________Calculate
__________TempFile
__________tmpForCompareFile TransFile
__________datFile
__________2"
，cause the browser to crash.

The reason is that the regular: em: /^\b_((?:__|[\s\S])+?)_\b|^*((?:**|[\s\S])+?)*(?!*)/,

**Comment by sashimizakana** [comment]
+1

**Comment by joshbruce** [comment]
Closing as stale.

**Comment by Feder1co5oave** [comment]
Can't reproduce this. Good.
