### ISSUE TITLE
here maybe a bug again when multiple underscores in words

### ISSUE THREAD

**Issue by saighost** [chjj/marked#387]
regex  in Marked：^\b((?:|[\s\S])+?)\b|^_((?:__|[\s\S])+?)_(?!*)

the test text ：<em>Result <strong></em><em>_</em><em>_</strong>Calculate <strong></em><em>_</em><em>_</strong>TempFile <strong></em><em>_</em><em>_</strong>tmpForCompareFile TransFile <strong></em><em>_</em><em>_</strong>datFile <strong></em><em>_</em>__</strong>2</p>

**Comment by Feder1co5oave** [comment]
I can't reproduce this, I guess it was fixed! @joshbruce
