### ISSUE TITLE
How to add language extensions?

### ISSUE THREAD

**Issue by JCMais** [chjj/marked#399]
Let's say that I have a new element type:

```
Hey [user:(username goes here)]
```

That becomes

```
Hey <a href="link-to-user-profile">username</a>
```

How to add it without modifying library files? Or it's not possible?

**Comment by activey** [comment]
Same question here, how to introduce a new markup element?

**Comment by dyatlov** [comment]
I guess  it should be something like this:

```javascript
marked.Lexer.rules['username'] = /@\w+/;
marked.renderer['username'] = function(text) { /* */ }
```

based on source code..
