### ISSUE TITLE
Option to insert ID in output for forward searches from editors.

### ISSUE THREAD

**Issue by cirosantilli** [chjj/marked#416]
Given a line of the markdown file, I want to an option to add to the output a span with an id at more or less the same position as the line:

```
<span id="CURRENT_POSITION">
```

so that from my text editor I can set up bindings that do:

```
marked --line %CURRENT_LINE%
firefox /tmp/marked/out.html#CURRENT_POSITION
```

Same for browser preview as you type like Dillinger.io.

Would PRs for this be considered?

**Comment by joshbruce** [comment]
Closing as stale - see #956
