### ISSUE TITLE
I hope marked can support customing tag,meaning we can make our new lexer rules

### ISSUE THREAD

**Issue by weekeight** [chjj/marked#425]
@chjj I search the issues in marked,and found the same quetion like #379 #383 etc
Is that true we can't add new lexer rules and do something we want using marked?But I think it is very important.
I wanna write something like {{{test.html}}} in markdown file,and do something especial about these pattern,is there any way to do this?
I don't know whether am I misunderstanding the issues I mentioned before.If I am right,can marked support this?thanks a lot!

**Comment by prototypic** [comment]
+1

**Comment by the0neWhoKnocks** [comment]
+1

**Comment by dr-dimitru** [comment]
+1

**Comment by joshbruce** [comment]
Closing as out of scope for now. See #956
