### ISSUE TITLE
Change the logic of generating the id of h tags

### ISSUE THREAD

**Issue by whzhyh** [chjj/marked#432]
Now the logic of generating the id of h tags is `raw.toLowerCase().replace(/[^\w]+/g, '-')`.

By using this method, if the header includes other none-English words, the id just is '-'. 

Then if we need the id to be used as anchors, this won't work.

Now I am using [marked-toc](https://github.com/jonschlinkert/marked-toc) to generate index of the headers, it uses [uslug](https://github.com/jeremys/uslug) to generate the anchors, the logic is `slugify(raw.toLowerCase(), {allowedChars: '-'})`.

I think that is a good solution. if you support this modification, I can do it and create a pull request. Thanks

**Comment by joshbruce** [comment]
#981
