### ISSUE TITLE
Can't get html blocks to work in 0.3.2

### ISSUE THREAD

**Issue by mcasimir** [chjj/marked#439]
```
npm list | grep marked
├── marked@0.3.2
```

Running this in node:

``` js
var marked = require('marked');
console.log(marked('<div>\n\n#Hi!\n\n</div>\n\n'));
```

Outputs:

```
<div>

#Hi!

</div>

```

There is some config I should setup to make marked parsing text nodes inside html?

**Comment by MichielDeMey** [comment]
I ran into the exact same issue. Haven't found a solution yet.

**Comment by joshbruce** [comment]
Please check using 0.3.9 version. Open new issue if still exists.
