### ISSUE TITLE
gfm

### ISSUE THREAD

**Issue by aackerman** [chjj/marked#44]
Part of the Github Flavored Markdown is to support output of links that will link to users, commit sha's, repo, and issues. This is my understanding, when reading through showdown.js which is included in 'github-flavored-markdown' available on NPM. Do you have any plan for the future to add these features to the parser?

**Comment by anubiann00b** [comment]
Can we close this? We don't want this in the core framework, and there's a package for this already.

**Comment by RangerMauve** [comment]
Autolinking would be useful. Especially since there being an option for `gfm` in the options kind of made me expect all of GFM to be supported.
