### ISSUE TITLE
Indented code block containing HTML incorrectly parsed as inline HTML

### ISSUE THREAD

**Issue by mappu** [chjj/marked#440]
Hi! Cool project.

I am trying to create documentation including inline HTML code samples, i expect the inline HTML samples to be formatted as code. However they are being included verbatim.

Repro is as follows:

```
var marked = require('marked');
console.log( marked("#Samples\nHere is an HTML code sample\n    <iframe src=''>\n    </iframe>\n") );
```

Produces

```
<h1 id="samples">Samples</h1>
<p>Here is an HTML code sample
<iframe src=''>
</iframe></p>
```

Expected `<pre><code>&gt;iframe src=''&lt;&gt;/iframe&lt;</code></pre>` or something similar...

Or is there meant to be an alternative way of creating a code block, rather than a four-space indent?

marked@0.3.2

**Comment by rymohr** [comment]
Related to #378

**Comment by Ryn830** [comment]
+ 1

**Comment by joshbruce** [comment]
#983

**Comment by Feder1co5oave** [comment]
Indented code blocks cannot interrupt paragraphs. So you need to put an empty line between the first paragraph and the code block:

~~~
$ bin/marked
# Samples
Here is an HTML code sample

    <iframe src=''>
    </iframe>
~~~
~~~
<h1 id="samples">Samples</h1>
<p>Here is an HTML code sample</p>
<pre><code>&lt;iframe src=&#39;&#39;&gt;
&lt;/iframe&gt;
</code></pre>
~~~
