### ISSUE TITLE
Line/column numbers in renderer

### ISSUE THREAD

**Issue by sidorares** [chjj/marked#441]
I'm generating javascript code from .md files and would like to build source map along the way. Is there any way to get line/column number at the moment when renderer handler is invoked?

**Comment by bpasero** [comment]
+1

**Comment by andr2** [comment]
Added a pull-request with partial resolution: https://github.com/chjj/marked/pull/680

**Comment by Twwy** [comment]
@andr2 
thanks
It's really useful.

**Comment by joshbruce** [comment]
#983
