### ISSUE TITLE
trailing CR in </pre> in: Renderer.prototype.code()

### ISSUE THREAD

**Issue by warren-bank** [chjj/marked#449]
minor fix/suggestion:
- dev (`lib/marked.js`):
  `search = '\n</code></pre>`
  
  `replace = '</code></pre>`
- prod (`marked.min.js`):
  `search = "\n</code></pre>`
  
  `replace = "</code></pre>`
- notes:
  - this occurs twice.
  - it has to do with how the html for code blocks are built.
  - the trailing CR is inside a `<pre>`, so it adds visible white-space.

**Comment by acooper-accusoft** [comment]
An extra newline before the closing `</code>` tag does add space in the browser. Here is an example:

```
<html>
  <style>pre { background-color: #eee; border: 1px solid blue; }</style>
  <body>
    <pre><code>Hello
    </code></pre>

    <pre><code>Hello</code></pre>
  </body>
</html>
```

![pre-newline](https://cloud.githubusercontent.com/assets/12171970/18521251/5f0480f4-7a79-11e6-899a-d232e8f19a6e.png)

The screenshot is from Chrome 52 on Mac. I see the same behavior in Safari 9.1.1.

I agree with the originally proposed suggestion: Remove the `\n` before `</code></pre>` in the built-in renderer.

**Comment by Feder1co5oave** [comment]
```html
<html>
  <style>pre { background-color: #eee; border: 1px solid blue; }</style>
  <body>
    <pre><code>Hello
    </code></pre>   <==== THIS

    <pre><code>Hello</code></pre>
  </body>
</html>
```

That's not just a trailing newline. That's a newline plus 4 blanks.
My chrome 52 on Linux still ignores a simple trailing newline in a `<pre><code>` block.
The default `marked` renderer does not add blanks to indent html. If you generated this with a custom renderer I think it is your responsibility.

**Comment by acooper-accusoft** [comment]
Thanks, my mistake. I had generated the HTML by hand and forgot to remove the indenting.

**Comment by Feder1co5oave** [comment]
No problem!

**Comment by joshbruce** [comment]
#983
