### ISSUE TITLE
IDs of headings with inline tokens (link, em, bold...)

### ISSUE THREAD

**Issue by Feder1co5oave** [chjj/marked#450]
I was working recently about headings' ids and I encountered something like:

``` markdown
### Heading with a [link](http://github.com/)

### Heading with some _italic text_

### Or some **strong**
(which doesn't really make any difference, here)

### Or even `code`

### What about ~~strikethrough~~
```

Here on github, clean segment links are generated, which only include the "raw" visible part of the heading text, as you can see in this [gist](https://gist.github.com/Feder1co5oave/68d3481c44da15720d74).

Now, `marked` with default options returns this:

``` html
<h3 id="heading-with-a-link-http-github-com-">Heading with a <a href="http://github.com/">link</a>!</h3>
<h3 id="heading-with-some-_italic-text_-">Heading with some <em>italic text</em>!</h3>
<h3 id="or-some-strong-">Or some <strong>strong</strong>...</h3>
<p>(which doesn&#39;t really make any difference, here)</p>
<h3 id="or-even-code-">Or even <code>code</code></h3>
<h3 id="what-about-strikethrough-">What about <del>strikethrough</del></h3>
<p>Hover the cursor on the titles to see the generated link.</p>
```

As you can see, the ids are quite "dirty", as they are generated from the raw markdown code of the heading (see [code](https://github.com/chjj/marked/blob/7be419324986c7a37c8d3e2fd580e925e236db52/lib/marked.js#L976)). Some markdown punctuation is crushed into dashes, but more complex tokens like links have additional text in them, which makes its way to the segment link.

I wonder if you would be interested in "fixing" this, as I believe it would require some many LOCs.
My idea was that we could create a function like `inline.output`, that only returns the textual part of the rendered markdown. The return value of this function would be passed as the `raw` argument of the heading renderer.
I am available to submit a PR in a week.

**Comment by F1LT3R** [comment]
+1

**Comment by joshbruce** [comment]
See #981
