### ISSUE TITLE
Tests failing in a fresh checkout

### ISSUE THREAD

**Issue by pdubroy** [chjj/marked#465]
I just cloned master and ran `node test`, and got the following failure:

```
#10. def_blocks.text failed at offset 20. Near: "<blockquote><p>hello</p><p><ahref="foo">1</a>:hell".


Got:
<blockquote><p>hello</p><p><ahref="foo">1</a>:hell


Expected:
<blockquote><p>hello[1]:hello</p></blockquote><hr>
```

Not sure if this is a known issue or not, but thought I'd open a bug in case you weren't aware of it.

**Comment by andre-artus** [comment]
Has any decision been made on this? 

I see two issues here:

1. Ref links should require two sets of square brackets. 
    As @guypursey pointed out the first instance of [1] is treated as a ref link to the second instance. 
    This should not happen on a single pair of brackets.

2. The test is broken (def_blocks.text, and def_blocks.html).
    Assuming that this test pair are intended to contain ref links then both the input (def_blocks.text) 
    and expected result (def_blocks.html) ought to be modified accordingly.

**Comment by KostyaTretyak** [comment]
It looks like you just need to delete [these lines](https://github.com/chjj/marked/blob/cd2f6f5b7091154c5526e79b5f3bfb4d15995a51/lib/marked.js#L42-L44) and fix the tests [like this](https://github.com/KostyaTretyak/marked-ts/commit/e325fbc87b3f81d64bdb930e10038b726a72bc57).

**Comment by joshbruce** [comment]
Closing as stale. "Fresh" was three years ago. Things have most likely changed a great deal.

See also #956 

And #958

Please do contribute solutions back to the main line.

**Comment by KostyaTretyak** [comment]
> Things have most likely changed a great deal.

But the fact that the current version marked (from master) does not pass this test in the same way. For three years, this simple test has been failing all the time...

**Comment by joshbruce** [comment]
Agreed. There are two failing tests in the PR referenced. If you know how to fix them (as it seems you do??), please do so and contribute back. I don't know enough about Marked to do it myself; otherwise, I would.

One person can't maintain this library. As evidenced by #956

**Comment by KostyaTretyak** [comment]
Done https://github.com/chjj/marked/pull/974

**Comment by Feder1co5oave** [comment]
From the commonmark spec, I see that link definitions are allowed inside blockquotes too:
http://spec.commonmark.org/0.28/#example-181

So wrt commonmark, the def_blocks test looks wrong to me.
