### ISSUE TITLE
simple [[wiki-links]] aren't parsed 

### ISSUE THREAD

**Issue by dcsan** [chjj/marked#471]
with gfm:true, we should get wiki links parsed? 
ie `[[tomatoes]]` would give a link. or is that a feature specific to the github wiki and not markdown?

```
$ cat test.md
this is a [[link]] mohkay.%

$ marked test.md
<p>this is a [[link]] mohkay.</p>
```

**Comment by yakivmospan** [comment]
+1 for @dcsan and @alanguir , would be great to Cover such a thing with out additional `Gollum` filtering level.

**Comment by yakivmospan** [comment]
For those who still need this, here is the code snippet that converts all of `[[..]]` into `[..](..)`:

```js
  /**
   * @private
   * @returns {String}
   */
  replaceGithubWikiLinks(markdown) {
    // github supports [[...]] declaration of links. find all of them
    return markdown.replace(/\[\[([^\]]+)\]\]/g, function(allPattern, link) {

      // inside of brekets link can be added as:
      // - page name only [[Calls]], [[Call-Log]];
      // - link title only [[Call Log]];
      // - link title and page name [[Call Log|Call-Log]], [[Log|Call Log]].

      // search for link title
      let linkTitle = link.replace(/\|([^\|]+)/, "")

      // search for page name
      let pageName = link.replace(/([^\|]+)\|/, "")

      if(!linkTitle){
        linkTitle = link
      }

      if (!pageName){
        pageName = link
      }

      // make sure page name has correct format
      link = pageName.replace(" ", "-")

      // convert [[<link title> | <page name>]] to [<link title>](<page name>)
      link = `[${linkTitle}](${pageName})`
      return link
    })
  }
```

Use it before passing into the renderer, Cheers.

**Comment by joshbruce** [comment]
See #956 

Closing as out of scope for the targeted specifications and resolved by the snippet above.

**Comment by dcsan** [comment]
useful snippet thanks for leaving here. @yakivmospan 
can you unpack it for me a little bit please?

in this:

>    return markdown.replace(/\[\[([^\]]+)\]\]/g, function(allPattern, link) {

markdown.replace method takes a regex and a function?
what is `allPattern` ? another method in this codebase or a parameter thats not used?

**Comment by yakivmospan** [comment]
Hey @dcsan, take a look at the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter). It shell clarify it for you.

Also [here](https://github.com/yakivmospan/github-wikito-converter/blob/develop/src/markdown.js#L131) you can see the full usage sample with some context.

**Comment by dcsan** [comment]
ah got it. i didn't realize that was just `String.replace()` ... thanks!

**Comment by yakivmospan** [comment]
@dcsan no prob, have fun with it !)
