### ISSUE TITLE
support for YAML front matter

### ISSUE THREAD

**Issue by elliottregan** [chjj/marked#485]
Like this: http://jekyllrb.com/docs/frontmatter/

**Comment by dvcrn** [comment]
It's been a year but github is currently parsing front matter into a table. Now that this is part of the official GFM parsing, I think we should put it into marked (into gfm) as well. 

e.g.: https://github.com/dvcrn/dvcrn.github.io/blob/master/_posts/2015-10-13-my_dream_editor.markdown

Front matter:
```
---
layout: post
title: "My Dream Editor"
date: "2015-10-13 16:05:17 +0900"
---
```

Output: 
![screen shot 2015-10-23 at 11 02 40 am](https://cloud.githubusercontent.com/assets/688326/10682814/9bbc04be-7975-11e5-96ba-7ca55ebc3ba9.png)

**Comment by adam-lynch** [comment]
@dvcrn if GitHub was, you wouldn't need to use an image as an example right? :stuck_out_tongue_winking_eye:

**Comment by elliottregan** [comment]
Nice catch! @dvcrn ! 

@adam-lynch click the other link. You can see it at the top of that page.

**Comment by adam-lynch** [comment]
Elliott, thanks :). Weird how they render markdown differently here hmm

**Comment by elliottregan** [comment]
They don't mention it in their docs, but they are definitely showing key-values, even complex ones with arrays, as a table. I still prefer JSON because it's easier to work with, but it makes sense for Github to display it Asa table.

**Comment by scottgonzalez** [comment]
> They don't mention it in their docs

It's probably just left out because it's unrelated to their markdown parser. See https://github.com/blog/1647-viewing-yaml-metadata-in-your-documents

**Comment by justinhelmer** [comment]
FYI if people are still looking, @adam-lynch's comment [here](https://github.com/chjj/marked/issues/485#issuecomment-58087903) is conceptually the way to go.

Also, [metalsmith](http://www.metalsmith.io/) is really great for this type of think, and includes a [metalsmith-markdown](https://github.com/segmentio/metalsmith-markdown) plugin that is built on top of [marked](https://github.com/chjj/marked). When used in combination with [metalsmith-layouts](https://github.com/superwolff/metalsmith-layouts), you can do some really cool things.

For example (in a `gulp` pipeline):

```js
function _metalsmith() {
  var files = ['source/**', '!source/layouts/**', '!source/partials/**'];

  return gulp
      .src(files)
      .pipe(metalsmith({
        use: [
          markdown(),                   // from `metalsmith-markdown` (`marked` wrapper)
          layouts({                     // from `metalsmith-layouts`
            engine: 'handlebars',       // any engine from consolidate.js
            default: 'page.html',
            directory: 'source/layouts',
            partials: 'source/partials',
            pattern: '**/*.html'
          })
        ]
      }))
      .pipe(gulp.dest('build'));
}
```

`metalsmith-layouts` is **automatically** looking for the `file.frontMatter` property set internally by [gulp-front-matter](https://github.com/lmtm/gulp-front-matter), and using it to render [handlebars](http://handlebarsjs.com/) data for a fixed set of `layouts`.

Example `markdown`:

```
---
layout:    documentation.html
title:     Documentation - 4.2.1
permalink: /documentation/4.2.1/
---
- some
- list

some content
```

Example `handlebars` template:

```html
<!DOCTYPE html>
<html>
  <body>
    <h1>{{title}}</h1>
    <main>{{{contents}}}</main>
  </body>
</html>
```

Outputs:

```html
<!DOCTYPE html>
<html>
  <body>
    <h1>Documentation - 4.2.1</h1>
    <main>
      <ul>
        <li>some</li>
        <li>list</li>
      </ul>
      <p>some content</p>
    </main>
  </body>
</html>
```

None of this would be possible without the work by @chjj and team, so thanks for that.

I originally came here looking for answers, so hopefully this helps the next guy/gal.

Cheers.

**Comment by joshbruce** [comment]
See #956 

Closing as out of scope for the two targeted specifications of Marked.

**Comment by elliottregan** [comment]
:( but that makes sense.

**Comment by up9cloud** [comment]
Memo for browser 😆 

```html
<div id="content"></div>
<script src="https://unpkg.com/marked/marked.min.js"></script>
<script src="https://unpkg.com/js-yaml@3/dist/js-yaml.js"></script>
<script src="https://unpkg.com/yaml-front-matter@4/dist/yamlFront.js"></script>
<script>
  let cached_lex = marked.Lexer.lex
  marked.Lexer.lex = function (text, options) {
    let parsed = yamlFront.loadFront(text)
    let cKey = '__content'
    let table = [
      [],
      [],
      []
    ]
    for (let k in parsed) {
      if (k === cKey) {
        continue
      }
      table[0].push(k)
      table[1].push('---')
      table[2].push(parsed[k])
    }
    let tableMd = table.map(row => row.join('|')).join('\n')
    return cached_lex(tableMd + '\n' + parsed[cKey], options)
  }
</script>
<script src="https://unpkg.com/jquery@3/dist/jquery.min.js"></script>
<script>
$(document).ready(function() {
  $.get('https://raw.githubusercontent.com/vuejs/vuejs.org/master/src/v2/examples/index.md', function(str) {
    $("#content").html(marked(str));
  });
});
</script>
```

**Comment by mcapodici** [comment]
I want to ignore frontmatter for my scenario.

Here is how I do it:

` md = md.replace(/^---$.*^---$/ms, '');`

**Comment by UziTech** [comment]
You can also use [front-matter](https://www.npmjs.com/package/front-matter) to get any edge cases.

```js
md = frontMatter(md).body;
```

**Comment by sernaferna** [comment]
I came across a case where I _do_ want the rendered output from my markdown to be handled differently based on the front matter. My use case is too niche to describe, but suppose we want to handle the case where we want to prefix some text to the beginning of headers, such that:

```markdown
---
headingPrefix: Chapter:
---
# Some things I was thinking
These are some things I was thinking...
```

would become

```html
<h1>Chapter: Some things I was thinking</h1>
<p>These are some things I was thinking...</p>
```

still contrived, but you get the point; the text in the optional front-matter would be used in rendering HTML from the markdown.

First the extension. To make this work, instead of just creating the extension we create a function that _returns_ the extension; the function can take parameter(s) for the information it needs:

```typescript
import { marked } from 'marked';

export const fixHeadings = (headingPrefix: string): Partial<Omit<marked.Renderer<false>, 'options'>> => {
  return {
    heading(text, level) {
      return `<h${level}>${headingPrefix} ${text}</h${level}>`;
    },
  };
};
```

Using the `front-matter` package we can handle attributes in the markdown front-matter similar to this:

```typescript
import { marked } from 'marked';
import fm from 'front-matter';
import { fixHeadings } from './fixheadings'

interface MarkdownOptions {
  headingPrefix: string;
  // other options that can be set in the front-matter
}

const defaultOptions: MarkdownOptions = {
  headingPrefix: 'Chapter:', // good to have a default, because the front-matter might not exist
};

export const renderedOutputFromMarkdown = (md: string): string => {
  const options = { ...defaultOptions };
  // by default, the markdown we want to parse is the entire input
  let markdownString = md;

  try {
    const fmResult = fm(md);
    // if there is front-matter the markdown to parse is reduced to just the `body` from `front-matter`
    markdownString = fmResult.body;
    if ((fmResult.attributes as any).headingPrefix) {
      options.headingPrefix = (fmResult.attributes as any).headingPrefix;
    }
  } catch {
    // do nothing; can easily throw exceptions, especially when fm being edited
  }
  marked.use({ renderer: fixHeadings(options.headingPrefix) });
  // other marked.use() options go here as well

  return marked.parse(markdownString);
};
```
