### ISSUE TITLE
bower.json misses main and ignore entries

### ISSUE THREAD

**Issue by mistertakai** [chjj/marked#496]
Installing 0.3.2 with bower, the following warning appears (and holds true):

```
bower marked#*            invalid-meta marked is missing "main" entry in bower.json
bower marked#*            invalid-meta marked is missing "ignore" entry in bower.json
```

This leads to mainBowerFiles not returning the main js file.

**Comment by joshbruce** [comment]
See #956 

Bower settings were recently updated. Closing as stale or overtaken by events.
