### ISSUE TITLE
HTML parsing issue?

### ISSUE THREAD

**Issue by greggman** [chjj/marked#507]
I ran into this issue. Here's some markdown

```
tstfoo

<div class="webgl_bottombar">
a = b * c;
var displayWidth  = gl.canvas.clientWidth  * realToCSSPixels;
var displayHeight = gl.canvas.clientHeight * realToCSSPixels;
</div>
```

And here's what gets generated

``` html
<p>tstfoo</p>
<div class="webgl_bottombar">
a = b <em> c;
var displayWidth  = gl.canvas.clientWidth  </em> realToCSSPixels;
var displayHeight = gl.canvas.clientHeight * realToCSSPixels;
</div>
```

Is that expected? I thought markdown was supposed to pull out the HTML so those `*` shouldn't become `<em>` marks.

Here's a test

```
var marked  = require('marked');

var content = [
'tstfoo',
'',
'<div class="webgl_bottombar">',
'a = b * c;',
'var displayWidth  = gl.canvas.clientWidth  * realToCSSPixels;',
'var displayHeight = gl.canvas.clientHeight * realToCSSPixels;',
'</div>',
].join("\n");

var html = marked(content);
console.log(html);
```

**Comment by rymohr** [comment]
Related to #378.

**Comment by greggman** [comment]
Here's another parsing issue

    var marked  = require('marked');

    marked.setOptions({
      pedantic: true,  // true or false this doesn't matter.
    });

    var content = [
    'some markdown',
    '',
    '<iframe src="someurl.html"></iframe>',
    '<a href="someurl.html">foo</a>',
    '',
    '    should be code',
    '',
    '<iframe src="someurl.html"></iframe>',
    '',
    'some markdown',
    '',
    ].join("\n");

    var html = marked(content);
    console.log(html);

The part `'    should be code` does not get turned into code. In fact adding some console.logs to marked.js I see that it sees

    <iframe src="someurl.html"></iframe>
    <a href="someurl.html">foo</a>
    
        should be code
    
    <iframe src="someurl.html"></iframe>

was one block of HTML instead of 2 blocks of HTML and a block of markdown in the middle.

Changing it to 

    <iframe src="someurl.html"></iframe>
    <a href="someurl.html">foo</a>

    some markdown
    
        should be code
    
    some more markdown

    <iframe src="someurl.html"></iframe>

doesn't help

**Comment by joshbruce** [comment]
#985
