### ISSUE TITLE
Performance on Safari

### ISSUE THREAD

**Issue by runrevben** [chjj/marked#509]
Hi, thanks for a brilliant piece of code! We're having a great time working with it.

We've hit a snag on Safari with performance. On Chrome a 804kb markdown file takes 500ms to parse and render. On safari the exact same code takes 2 and a half minutes.

$(document).ready(function(e) {
        var start = +new Date();  // log start timestamp

```
    //var marked = require('marked');
    var renderer = new marked.Renderer();
    var navigation_html = '<ul class="nav bs-docs-sidenav lc_docs_nav">';
    var current_level = 1;

    renderer.heading = function (text, level) {
      var escapedText = text.toLowerCase().replace(/[^\w]+/g, '-');

        if(level < 3){

            if(level == current_level){
                // We are on the same level so just create another li
                navigation_html += '</li><li><a href="#'+escapedText+'">'+text+'</a>';  
            } else if(level < current_level){
                // we've gone up a level so just close of the sub ul and add an li
                navigation_html += '</li></ul><li><a href="#'+escapedText+'">'+text+'</a>';
                current_level = level;
            } else {
                // we've gone down a level so create a sub ul
                navigation_html += '<ul class="nav"><li><a href="#'+escapedText+'">'+text+'</a>';
                current_level = level;
            }
        }
        return '<h' + level + ' id="' + escapedText + '">' +text + '</h' + level + '>';

    },

    $("#documentation").html(marked(tUserGuideData, { renderer: renderer }));
    var end =  +new Date();  // log end timestamp
    var diff = end - start;
    alert(diff);

    $("#lc_userguide_nav").html(navigation_html + "</ul>");
    $("#documentation").scrollspy('refresh')
    $("#lc_userguide_nav ul li:first").addClass("active");
    $("#documentation img").addClass("img-responsive");
```

   });

when the page loads it takes a local markdown file and puts it into a javascript variable "tUserGuideData". Once the document is ready, it parses and sets the markdown. I've added a custom renderer that extracts the h1 and h2 to build a custom nav. All of this is marked up using bootstrap. 

Happy to post the full code example as it's not online anywhere. I'm trying to render a user guide offline in a browser. 

Any thoughts would be appreciated.

**Comment by ehjay** [comment]
:+1: we are seeing performance issue on Safari as well. We aren't using long sequences of underscores or asterisks.

**Comment by ehjay** [comment]
:+1: we are seeing performance issue on Safari as well. We aren't using long sequences of underscores or asterisks.

**Comment by joshbruce** [comment]
Closing as stale. Multiple versions of Marked and Safari have been released since this issue was opened.
