### ISSUE TITLE
Back ticks in titles (incorrectly?) converted to hypens

### ISSUE THREAD

**Issue by bduncanj** [chjj/marked#510]
Smashing library, much thanks!

I may be abusing markdown a little, but I'm using code back ticks in my titles:

``` markdown
## Messages
### `system-alarm-start`
### `system-alarm-end`
```

This however produces HTML in which the backtick is replaced with a hyphen in the `id` attribute of the resulting header element:

``` html
<h2 id="messages">Messages</h2>
<h3 id="-system-alarm-start-"><code>system-alarm-start</code></h3>
<h3 id="-system-alarm-end-"><code>system-alarm-end</code></h3>
```

The problem is that I'm using [marked-toc](https://www.npmjs.org/package/marked-toc) to convert this into the following markdown TOC (and then HTML via marked) which of course is now incompatible as that package just ignores the back ticks in the headers:

``` markdown
* [Messages](#messages)
  * [`system-alarm-start`](#system-alarm-start)
  * [`system-alarm-end`](#system-alarm-end)
```

... and finally ...

``` html
<ul>
<li><a href="#messages">Messages</a><ul>
<li><a href="#system-alarm-start"><code>system-alarm-start</code></a></li>
<li><a href="#system-alarm-end"><code>system-alarm-end</code></a></li>
</ul>
</li>
</ul>
```

**Comment by F1LT3R** [comment]
+1 to fixing this out of the box

**Comment by franciscop** [comment]
+1. I'd go a bit further and  say that leading/trailing hyphens should be removed as well:

```md
# Hello!
# How to fix X?
```

```html
<h1 id="hello-">Hello!</h1>
<h1 id="how-to-fix-x-">How to fix X?</h1>
```

**Comment by joshbruce** [comment]
#981
