### ISSUE TITLE
How to add custom html tags

### ISSUE THREAD

**Issue by lordfriend** [chjj/marked#514]
I want to add some custom html tags like this:

`````` html
<example>
    <file name="index.html">
    ```html
      <div class="example">
      example code here
      </div>
    ```
    </file>
</example>
``````

but it seems `<example>` and `<file>` tag are not recognised as a valid html tag. marked think they are paragraph elements and add a couple of `<p>` around them

the compiled content is:

``` html
<p><example>
    <file name="index.html"></p>
    <pre><code class="lang-html">
      &lt;div class="example"&gt;
      example code here
      &lt;/div&gt;
    </code></pre>
    <p></file>
</example></p>
```

This behave make the `<example>` and `<file>` tag fail to work

**Comment by brunowego** [comment]
This is very inconvenient, I am creating a documentation for my project which involves displaying the element, however unfortunately is automatically added a paragraph around.

My Angular directive:

```html
<pf-panel>
    <pf-body>
        <p>Exemplo de painel com corpo.</p>
    </pf-body>
</pf-panel>
```

The results:

```html
<p><pf-panel>
    <pf-body>
        <p>Exemplo de painel com corpo.</p>
    </pf-body>
</pf-panel></p>
```

Perhaps not the purpose of this project ...

**Comment by brunowego** [comment]
@chjj if you have a little time, please take a look on this issue :+1:

**Comment by joshbruce** [comment]
#985

**Comment by ghdoergeloh** [comment]
Sorry to comment on this old issue, but I cannot find what happend to this issue/feature request.
I found some Issues like #283 and the PR #833 but that was not merged.
I still have the problem, that custom html tags are not recognised by the parser. Why aren't they handled like normal html?

**Comment by ghdoergeloh** [comment]
Okay, partially it is working:
```
> marked.parse('<div-test></div-test>') // didn't work
'<p><div-test></div-test></p>\n'

> marked.parse('<div-test>\n</div-test>') // worked
'<div-test>\n</div-test>'

> marked.parse('<div-test>test</div-test>') // didn't work
'<p><div-test>test</div-test></p>\n'

> marked.parse('<div-test>\ntest\n</div-test>') // worked
'<div-test>\ntest\n</div-test>'
```

**Comment by UziTech** [comment]
That is because there is a difference between an [HTML block](https://spec.commonmark.org/0.29/#html-blocks) and [inline HTML](https://spec.commonmark.org/0.29/#raw-html).

Any inline element will get wrapped by a `<p>` tag if it is not inside another block element. You can use [`parseInline`](https://marked.js.org/using_advanced#inline) to prevent wrapping if you only want inline blocks parsed.

**Comment by bent10** [comment]
It's super late to join this issue, but I'd like to share an alternative approach that utilizes [directive syntax](https://github.com/bent10/marked-extensions/tree/main/packages/directive) which might be suitable for your needs:

```js
import { Marked } from 'marked'
import { createDirectives, presetDirectiveConfigs } from 'marked-directive'

const markdown = `::::example{#foo.bar}
:::file{name="index.html"}
\`\`\`html
<div class="example">
  <p>example code here</p>
</div>
\`\`\`
:::
::::
`

const html = new Marked()
  .use(
    createDirectives([
      ...presetDirectiveConfigs,
      { level: 'container', marker: '::::' }
    ])
  )
  .parse(markdown)

console.log(html)
```

Yields:

```html
<example id="foo" class="bar">
  <file name="index.html">
    <pre><code class="language-html">&lt;div class=&quot;example&quot;&gt;
  &lt;p&gt;example code here&lt;/p&gt;
&lt;/div&gt;
</code></pre>
  </file>
</example>
```
