### ISSUE TITLE
Bug in parsing

### ISSUE THREAD

**Issue by eGavr** [chjj/marked#524]
I have such md-file

```md
blah
-

blah
=

```

I've received the tokens of the given markdown by method `marked.lexer`:

```js
[ { type: 'paragraph', text: 'bla\n-' },
  { type: 'paragraph', text: 'bla\n=' },
  links: {} ]
```

It seems that it is wrong, the right variant is:

```js
[ { type: 'heading', depth: 2, text: 'bla' },
  { type: 'heading', depth: 1, text: 'bla' },
  links: {} ]
```

isn't it?

**Comment by blb78** [comment]
wrong. 
The github rules, are not the official rules.

the elements number must be greater than 2.

**Comment by eGavr** [comment]
Okey, thanks, sorry to bother you.

**Comment by blb78** [comment]
you dont bother me.

and I made a mistake : the elements number must be greater than 1.
