### ISSUE TITLE
Option to turn HTML escaping off

### ISSUE THREAD

**Issue by adam-lynch** [chjj/marked#529]
I'd love this please. 
### My use case

I want to compile markdown for places where HTML isn't supported, just plain strings (like in Mac & Windows 8+ notifications for example). 

I've already created a custom marked renderer which "cleans" markdown. So I try convert it to the nicest possible plaintext representation I can; i.e. it leaves some things pretty much as they are (like `**strong**`), it converts inline codespans to `{code}` (or `{html}` if code is passed), etc.

It works well but I just noticed that single quotes are being converted to `&#39;`.

**Comment by joshbruce** [comment]
#985
