### ISSUE TITLE
first part turns into '<pre><code>'

### ISSUE THREAD

**Issue by ghost** [chjj/marked#534]
I have news, once in a list with all news and once where a single new is showed.

The news on the list has a small cut at 200 chars just like this:

```
$('.new_post_content').each(function() {
       var text = $(this).text();
       text = text.length > 200 ? ( text.substr(0, 200) + "..." ) : text;
       var marked_text = marked(text);
       $(this).html(marked_text);
});
```

All is working there, the single news is displayed like this:

```
$('.post-content').each(function() {
      var text = $(this).html();
      var marked_text = marked(text);
      $(this).html(marked_text);
});
```

On the single new the first paragraph is displayed with `<pre><code></code></pre>`.

What is the reason for this?

**Comment by jme783** [comment]
+1, I don't know why my MD is being wrapped with this as opposed to rendering correctly. Does anyone know why this is happening or what I can do to fix?

**Comment by dongli** [comment]
+1, I meet the similar problems.

**Comment by jonathantneal** [comment]
This is because your text likely has a lot of indentations, which would be interpreted as a code block.

```html
<div>
	Hello World
</div>
```

```js
// get inner html
innerHTML = div.innerHTML; // "\n\tHello World\n" will be interpreted as a code block

// try trimming the innerHTML
div.innerHTML = marked(innerHTML.trim());
```

Alternatively, you could detect the shortest indentation on any line, and use regex to replace that length of indentation on every line.

**Comment by joshbruce** [comment]
#983
