### ISSUE TITLE
type check

### ISSUE THREAD

**Issue by BClark-Grad-Project** [chjj/marked#543]
```
/node_modules/marked/lib/marked.js:1215
    throw e;
          ^
TypeError: Cannot call method 'replace' of undefined
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/home/brandon/Development/GradProject/site-template/node_modules/marked/lib/marked.js:137:6)
```

**Comment by mkopala** [comment]
It doesn't handle `null` and `undefined` well - it throws the error above.  I either:

* use a wrapper function to return an empty string if the input is null or not defined
* always pass an empty string to `marked` in such cases

**Comment by BClark-Grad-Project** [comment]
I accounted for it in my code, thought you may be interested in covering it on your side because it can break an applications operation.  Not sure what your scope coverage is.  

Close topic? Or mark for enhancement?

Brandon L. Clark
Graduate of CSU Fullerton | Software Engineering
P) 714.614.7951

Links of Interest
http://themindcompany.net | CRM & CMS Framework in Development
http://www.themindspot.com | The Mind Company Information Site

-----Original Message-----
