### ISSUE TITLE
Vulnerable to regular expression denial of service (ReDoS) when certain types of input are passed in to be parsed.

### ISSUE THREAD

**Issue by mauvm** [chjj/marked#555]
Not sure if already being addressed, but my [David DM](https://david-dm.org/mauvm/documark) shows "SECURITY VULNERABILITIES IN DEPENDENCIES" because of Marked v0.3.3.

It links to this article: https://nodesecurity.io/advisories/marked_redos (CVE-PENDING). Which states:

> Marked 0.3.3 and earlier is vulnerable to regular expression denial of service (ReDoS) when certain types of input are passed in to be parsed.

**Comment by JCMais** [comment]
see https://github.com/chjj/marked/issues/497

But idk if the author is still supporting this library, so you are better looking into alternatives.
