### ISSUE TITLE
How can I tune marked to process markup within HTML

### ISSUE THREAD

**Issue by varya** [chjj/marked#556]
Is this possible to process the markup within HTML? I have such a markdown code from one jekyll project:

```
# Title

<div markdown="1">

* item
* item
* item

</div>
```

I want to switch into marked. So I need to make code inside the tags with `markdown="1"` attribute processable. How can I do this?

**Comment by rymohr** [comment]
Might want to take a look at #378 and #236.

**Comment by adam-p** [comment]
You will probably need to extract the plaintext Markdown from the HTML first. That's what I do with [Markdown Here](https://github.com/adam-p/markdown-here) when getting the MD that the user has typed into an email. My HTML-to-text code is [here](https://github.com/adam-p/markdown-here/blob/master/src/common/jsHtmlToText.js), although there might be better out there.

**Comment by joshbruce** [comment]
#985
