### ISSUE TITLE
The renderer option allows you to render tokens in a custom manor

### ISSUE THREAD

**Issue by moof2k** [chjj/marked#559]
From README.md: The renderer option allows you to render tokens in a custom manor

> manor
> noun(also manor house)
> a large country house with lands; the principal house of a landed estate.
> 
> manner
> noun
> a way in which a thing is done or happens

Apologies if this was intentional/ironic.

**Comment by joshbruce** [comment]
Closing as non-issue. I do not believe it's ironic. Please submit PR with fix as we focus on getting things back under control around here. :)
