### ISSUE TITLE
Use CommonMark instead of loosely defined Markdown flavour

### ISSUE THREAD

**Issue by dumblob** [chjj/marked#563]
It seems that the precise specification of [CommonMark](http://commonmark.org/) already settled down, so I'm proposing sticking with it to be compatible with most of Markdown flavours and also be predictable.

CommonMark is backwards compatible with the original [Gruber's Markdown](http://daringfireball.net/projects/markdown/), so it should be just internal change.

**Comment by nikolas** [comment]
I agree - it would be great if marked supported CommonMark! Currently I'm using [Remarkable](https://github.com/jonschlinkert/remarkable) because it has a commonmark option.

**Comment by puzrin** [comment]
`marked`'s strong point is it's small size.

For commonmark parser you'd better search in "official" list of implementations: https://github.com/jgm/CommonMark/wiki/List-of-CommonMark-Implementations. If you need commonmark support, i see no problem to select appropriate project.

**Comment by noraj1337** [comment]
It seems a good idea to use [commonmark.js](https://github.com/jgm/commonmark.js), [markdown-it](https://github.com/markdown-it/markdown-it) or [remarkable](https://github.com/jonschlinkert/remarkable).

**Comment by howardroark** [comment]
I really enjoy how flexible this parser is.  Allows for a good amount of human error.  Which is what you want from a syntax designed for writers.

**Comment by joshbruce** [comment]
See #956
