### ISSUE TITLE
Add renderer for new tag

### ISSUE THREAD

**Issue by gercobrandwijk** [chjj/marked#564]
I know that the default renderer of the blockquote (so the > in markdown) is like this:

```
Renderer.prototype.blockquote = function(quote) {
  return '<blockquote>\n' + quote + '</blockquote>\n';
};
```

But sometimes I want another color for the blockquote, so I need another renderer for the blockquote. For example that the user can use >> in Markdown and that it renders it like this:

```
Renderer.prototype.blockquote2 = function(quote) {
  return '<blockquote class="red-color">\n' + quote + '</blockquote>\n';
};
```

Do can I achieve this? In a few other issues (#383, #425) but I cannot find a clear answer for this.
So, in short: how do I add a renderer for a new markdown tag (like in this case the >>).

Thanks in advance.

**Comment by gercobrandwijk** [comment]
Checken the parameter *quote* and check if this startswith a > (so it's >> in the markdown) is not possible, because markdown (of course) creates then nested blockquotes when you use >>. So the 'solution' in issue #425 (answer of user 7c00) is not going to work for me, I really need a solution where someone explains me how to use my custom tag >>. Like how it works with * (italic) en ** (bold).

**Comment by joshbruce** [comment]
Closing as out of scope for Marked based on current focus. See #956
