### ISSUE TITLE
Links incorrectly receive markup

### ISSUE THREAD

**Issue by bennyn** [chjj/marked#574]
I have seen that "marked" parses Markdown within links. This should not happen.

Here is my example:

``` javascript
var link = 'https://www.nike.com/events-registration/event?id=6245&languageLocale=de_de&cp=EUNS_KW_DE_&s_kwcid=AL!2799!3!46005237943!b!!g!!womens%20running';

var options =  {
  renderer: new marked.Renderer(),
  gfm: false,
  tables: false,
  breaks: false,
  pedantic: false,
  sanitize: true,
  smartLists: false,
  smartypants: false
};

var output = marked(link, options);
```

The **output** is:

``` html
<p>https://www.nike.com/events-registration/event?id=6245&amp;languageLocale=de<em>de&amp;cp=EUNS_KW_DE</em>&amp;s_kwcid=AL!2799!3!46005237943!b!!g!!womens%20running</p>
```

As you can see, the `languageLocale=de_de&cp` has been turned into `languageLocale=de<em>de&amp;cp`, so `de_de` became `de<em>de`, which is wrong.

**Comment by 1j01** [comment]
You could surround the link with `<http://angle.brackets>` or enable `gfm` for linkifying bare URLs.

**Comment by joshbruce** [comment]
#984

**Comment by Feder1co5oave** [comment]
@1j01 is right, this is by design

**Comment by joshbruce** [comment]
Removing from 984 as this is by design.
