### ISSUE TITLE
Is there a way to render markdown without the enclosing <p>?

### ISSUE THREAD

**Issue by PerfectCarl** [chjj/marked#576]
I have the same issue as the one in [Markdown in JS without enclosing paragraph](http://stackoverflow.com/questions/27663203/markdown-in-js-without-enclosing-p).

Do you if there is way to achieve that?

**Comment by bennyn** [comment]
Hey! It's pretty easy to do. I just answered the question on stackoverflow: http://stackoverflow.com/a/29559116/451634

Let me know if it worked or if you need further help.

Best from Berlin,
Benny

**Comment by PerfectCarl** [comment]
It works perfectly, thanks.
It feels a bit that it should be added as an option (or documented in the front page).

For reference my code was: 
```
  var markedRenderer = new marked.Renderer() ;
  markedRenderer.paragraph = function(text) {
    return text + '\n';
  };

  markedProvider.setOptions({
    renderer: markedRenderer,
    gfm: true,
...
  });
```
