### ISSUE TITLE
extending href format to allow optional attributes?

### ISSUE THREAD

**Issue by frumbert** [chjj/marked#577]
I'm currently using showdown as a markdown parser since its easier [at my skill level] to extend the parser to incorporate what I need: attribute support for links, and custom link types. This engine is however somewhat faster in my case, so I'm trying to port my customisations.

My link finder regexp isn't as sophisticated as in this engine. I'm currently battling with this:

```
/(\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()<?(.*?(?:\(.*?\).*?)?)>?[ \t]*((\")([^"]|.*?)\"[ \t]*)?(\{(.*?)\}[ \t]*)?\))/g
```

which is effectively matching the square brackets, then the href, the optional title, then an optional section wrapped in curly brackets. You can see I've got problems with single and double quotes. so it would match something like

```
[wikipedia](http://wikipedia.com/ "Open wikipedia" {"target":"_blank","class":"btn", "action":"tooltip"})
```

I treat the section inside curles as json, and apply it as attributes to the rendered link. In the example above, this would render as

```
<a href="http://wikipedia.com" title="Open wikipedia" target="_blank" class="btn" data-action="tooltip">wikipedia</a>
```

If it encounters a key that is outside a known list (class, target, width, height, etc) then the attribute is prefixed with `data-` so that I can also add data attributes to links (also worked on images) in the same way.

I've also added some new types of href, such as `?[import](http://somewhere.com/file.md)` which use a switch to look at the `alt` portion and treat it as a command. In this example, `import` uses xhr or fs to read a remote file and append it in place (I also allow iframe, oembed, and a few handy tools). So I can do common templates much easier. I _kind of_ have a handle on how this would be implemented, but am getting hung up trying to implement the support for optional braces in the link part, and the code where it matches the `!` for images.

Any thoughts or pointers would be appreciated!

**Comment by joshbruce** [comment]
Closing as out of scope based on two targeted specifications. See #956
