### ISSUE TITLE
The double underscores at the beginning of the word break the html layout

### ISSUE THREAD

**Issue by tavriaforever** [chjj/marked#583]
Hello!
My case: markdown + html parts 
``` html
__word <div>Some html text <a href="#">Some html link</a> or block</div> __elem
```

output:
```
<p><strong>word <div>Some html text <a href="#">Some html link</a> or block</div> </strong>elem</p>
```
Result: Parser replaced `__` to `<strong>` and didn't pay attention to what it has inside html pieces and it's not just one text. 
Probably I would agree that this is the correct behavior of `marked` module, if I am not checked this case on `Github`, where everything is displayed correctly

Thank you for your attention :smirk:

**Comment by formulahendry** [comment]
I have a code fix [here] (https://github.com/formulahendry/marked/commit/2f73f6ee82603b49ef4b54c0cc9805d89cf91b25). Hope the pull request could be merged. Unfortunately, this repo has not been updated for over 3 months :(

**Comment by tavriaforever** [comment]
Thank you very much! It fixed our case.
