### ISSUE TITLE
quoting in pre code blocks

### ISSUE THREAD

**Issue by tcurdt** [chjj/marked#590]
This code block

```
    def map
      "bla" >
    end
```

gets converted to

```
<pre><code>def map
  &quot;bla&quot;  &gt;
end
</code></pre
```

which should really be

```
<pre><code>def map
  "bla" >
end
</code></pre
```

**Comment by joshbruce** [comment]
#983

**Comment by Feder1co5oave** [comment]
Commonmark escapes quotes, markdown.pl didn't:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=++++def+map%0A++++++%22bla%22+%3E%0A++++end
