### ISSUE TITLE
Url automatic linking for urls beginning with 'www'

### ISSUE THREAD

**Issue by chanthus** [chjj/marked#593]
When urls are automatically linked, only the ones beginning with http:// or https:// are converted. Would it be possible to support www as well? Or Is there any way I can render them as anchor tags myself?

**Comment by danderu** [comment]
@chanthus hey, how did you fix this issue?

**Comment by chanthus** [comment]
I was using this library in an angular app, so before piping the markdown through _marked_, urls are piped through a filter that prefixes _http://_ which then makes _marked_ render them as proper links.
