### ISSUE TITLE
Add comment syntax

### ISSUE THREAD

**Issue by jkarttunen** [chjj/marked#594]
As described in http://stackoverflow.com/questions/4823468/store-comments-in-markdown-syntax

Would be convenient if some section could be completely ignored by parser.

**Comment by bryanjacquot** [comment]
+1

**Comment by liuhong1happy** [comment]
+1

**Comment by joshbruce** [comment]
See #956 

Closing as seems to be out of scope for the two targeted specifications. Please correct me if I'm incorrect on this (with reference from specification) and will reopen as new feature.
