### ISSUE TITLE
Support more syntax variants

### ISSUE THREAD

**Issue by nichtich** [chjj/marked#60]
The popularity of Markdown has lead to several syntax variants extending the original Markdown syntax. Marked currently supports [github_flavored_markdown](http://github.github.com/github-flavored-markdown/). In adition there is at least  [Pandoc's markdown](http://johnmacfarlane.net/pandoc/README.html#pandocs-markdown) and [StackExchange Markdown](http://stackoverflow.com/editing-help/). The latter should be easy to implement, to support `[tag:foo]` links. Pandoc markdown may be more difficult but more useful too. See [gitit](http://gitit.net) for a use case. Maybe additional syntax variants are something for a 1.0 release?

**Comment by joshbruce** [comment]
#27
