### ISSUE TITLE
Issue with cyrillic headers

### ISSUE THREAD

**Issue by ArmorDarks** [chjj/marked#604]
Hi

First of all, thanks for great parser and compiler!

Seems that cyrillic generated ids from markdown headers have some issues.

This

``` markdown
# Заголовок
```

becomes

``` html
<h1 id="-">Заголовок</h1>
```

while it have to be like this:

``` html
<h1 id="заголовок">Заголовок</h1>
```

I understand that it might sound a bit odd, but it's perfectly fine id. Link like `<a href='index.html#заголовок'>link</a>` works as expected (tested in Chrome, Mozilla and IE11).

**Comment by Jayin** [comment]
+1

**Comment by KostyaTretyak** [comment]
*+1*
It would be good if a link could be made like this
```
# Заголовок {#some-hash-link}
```

**Comment by scsmash3r** [comment]
I support this too. Will it ever be fixed? Or can there be an option to disable automatic id generation?

**Comment by KostyaTretyak** [comment]
I fix it, just read [README.md](https://github.com/chjj/marked#overriding-renderer-methods)

```javascript
  var renderer = new window.marked.Renderer();

  renderer.heading = function (text, level)
  {
    var patt = /\s?{([^}]+)}$/;
    var link = patt.exec( text );
    
    if(link && link.length && link[1])
    {
      text = text.replace(patt, '');
      link = link[1];
    }
    else
    {
      link = text.toLowerCase().replace(/[^\wА-яіІїЇєЄ]+/gi, '-');
    }

    return '<h' + level + ' id="' + link + '">' + text + '</h' + level + '>';
  };
```

**Comment by ArmorDarks** [comment]
oh, nice. How did I miss it. Thanks.

I thinks it would be better to use something like [urlify](https://github.com/Gottox/node-urlify), which will convert cyrillic chars to latin ones, instead of replacing it with null.

**Comment by joshbruce** [comment]
#981
