### ISSUE TITLE
Support RMarkdown

### ISSUE THREAD

**Issue by rgbkrk** [chjj/marked#606]
RMarkdown ends up putting an extra spin on the code fences:

<pre>
```{r, echo = FALSE}
sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30)

renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser data
  bins <- seq(min(x), max(x), length.out = input$bins + 1)

  # draw the histogram with the specified number of bins
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```
</pre>

Within marked, this ends up getting picked up as paragraph sections, where each empty line delineates the next paragraph.

![screenshot 2015-06-20 14 05 12](https://cloud.githubusercontent.com/assets/836375/8268808/1b02d348-1755-11e5-9bb3-78f2cd194f23.png)

Ended up noticing that by overriding paragraph (when I was really trying to build on the `code` renderer):

```
  var _paragraph = renderer.paragraph;

  renderer.paragraph = function(text) {
    console.log(text);
    _paragraph.call(this, text);
  };
```

**Comment by rgbkrk** [comment]
Note: RMarkdown also has YAML front matter which I can already extract out using solutions from #485.

**Comment by rgbkrk** [comment]
Here's the [Markdown Document Format](http://rmarkdown.rstudio.com/markdown_document_format.html)

**Comment by joshbruce** [comment]
See #956 

RMarkdown is not a targeted specification at this time.
