### ISSUE TITLE
Making codeblocks render as inline code

### ISSUE THREAD

**Issue by sangyoo91** [chjj/marked#609]
I want to make it so that codeblocks are rendered as inline code. Is it possible using marked?

**Comment by HeyImAlex** [comment]
What do you mean? If you want ```` ```var a = "hello"``` ```` to render like `` `var a = "hello"` then I think it's as simple as:

````js
var marked = require('marked');
var renderer = new marked.Renderer();

renderer.code = renderer.codespan;
marked('```whatever```', { renderer: renderer });
// <code>whatever</code>
````

**Comment by joshbruce** [comment]
#983
