### ISSUE TITLE
Disable markdown for a chunk of code

### ISSUE THREAD

**Issue by mercmobily** [chjj/marked#621]
Hi there,

I was wondering if Marked had a feature where I could write:

```
<div markdown="0">
...
</div>
```

Where anything inside the "div" is left completely untouched.
I need this as I am trying to allow a chain of filter, where first I apply markdown, and then I apply EJS to the file. However, doing so it's impossible since Markdown escapes things.

Thank you!

Merc.

**Comment by mercmobily** [comment]
Sorry to bother... just checking if this was being considered! Thanks...

**Comment by joshbruce** [comment]
#983
