### ISSUE TITLE
Do not convert > into &gt; in code blocks

### ISSUE THREAD

**Issue by mercmobily** [chjj/marked#625]
Hi,

At the moment, in a code block, if you have:

```
def foo
  { :foo => "bar" }
end
```

It gets turned into:

```
def foo
  { :foo =&gt; "bar" }
end
```

Regardless of what `sanitize` is.

In https://github.com/chjj/marked/issues/160#issuecomment-18611040 @scottgonzalez suggested:

```
// Let marked do its normal token generation.
tokens = marked.lexer( content );

// Mark all code blocks as already being escaped.
// This prevents the parser from encoding anything inside code blocks
tokens.forEach(function( token ) {
    if ( token.type === "code" ) {
        token.escaped = true;
    }
});

// Let marked do its normal parsing, but without encoding the code blocks
parsed = marked.parser( tokens );
```

Is there a case were `<code>` blocks should actually be escaped like that, really?

Shouldn't this be the default behaviour, without hacking?
Sorry I would have reopened #160  but couldn't.

Merc.

**Comment by mercmobily** [comment]
Please let us know. There is an open PR for this too... #636

**Comment by joshbruce** [comment]
#983
