### ISSUE TITLE
Long issue & PR backlog

### ISSUE THREAD

**Issue by jden** [chjj/marked#626]
This is a meta-issue. As of 2015-07-21, there are 215 open issues and 96 (!) open PRs. @chjj, are you interested in community help with maintaining marked? Some good first steps might be setting up the repo on CI to attach test pass/fail reports to PRs, triaging open issues / PRs, closing old issues, and asking for more eyes and hands. I'm happy to help with any of the above if you'd like.

**Comment by rgbkrk** [comment]
Hey @jden, see #618.

**Comment by jden** [comment]
@rgbkrk thanks :) I'll close this as a dupe.
