### ISSUE TITLE
New Lines and Paragraphs aren't recognized

### ISSUE THREAD

**Issue by robrothedev** [chjj/marked#631]
I seem to be having an issue with new lines and paragraphs.  The markdown itself will show two lines between content, but the marked content only shows one line.  I have breaks: true in the options.  Is this a bug or am I missing something?

**Comment by robrothedev** [comment]
On another note, I did notice that <br> tags are accepted, so maybe the intention is to use break tags for new lines?

**Comment by chjj** [comment]
`breaks: true` still isn't entirely accurate to how GFM does it. It's a neglected feature right now. I think there is a PR open for it that I might take a look at.
