### ISSUE TITLE
Extra row and a cell in table

### ISSUE THREAD

**Issue by dogancelik** [chjj/marked#637]
```
| a | b | c |
|:-:|:-:|:-:|
```

Turns to this (on Github):

| a | b | c |
| :-: | :-: | :-: |

In marked, it turns to this:

![bug](https://cloud.githubusercontent.com/assets/486818/9064429/22faa10e-3ad5-11e5-98af-d27a1f049622.png)

marked HTML output:

``` html
<table>
<thead>
<tr>
<th style="text-align:center">a</th>
<th style="text-align:center">s</th>
<th style="text-align:center"></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center"></td>
</tr>
</tbody>
</table>
```

**Comment by joshbruce** [comment]
#980
