### ISSUE TITLE
Headings are no longer working since 0.3.4

### ISSUE THREAD

**Issue by ascholz81** [chjj/marked#642]
The headings function is creating headings correctly.

v0.3.3
"##My Heading" 

v0.3.4 and up
"## My Heading"

**Comment by chjj** [comment]
I can't remember the exact issue, but someone made a PR requiring GFM to require a space after. I revised the code a bit (maybe it caused a mixup?). So, original markdown still allows no space after the hash, but GFM requires one.

I can't for the life of me remember the specifics, but if it's wrong, here's a temporary fix you can use:

```
marked.Lexer.rules.gfm.heading = marked.Lexer.rules.normal.heading;
marked.Lexer.rules.tables.heading = marked.Lexer.rules.normal.heading;
marked('##foo');
```

This is a simple 1-character fix in the heading rule if it's wrong:

##Testing Heading

**Comment by chjj** [comment]
Looks like GFM does not allow `##Heading`.

**Comment by nilgradisnik** [comment]
@chjj Please be careful reviewing such PRs that break backwards compatibility.
If necessary, bump the minor or major version for npm package. This rule broke many headings for everyone doing `npm install` in the last week or so.

**Comment by bmneely** [comment]
@chjj please reconsider re-opening this issue. GFM does allow for `##Header` in (though strangly not in comments) in repo content: https://github.com/bmneely/spartacus/blob/master/README.md

**Comment by getaaron** [comment]
Would also like to see this reopened. Breaking functionality like this should be intentional, following the guidelines of semantic versioning.

Down the road it might be nice to transition to Commonmark, which has a better defined spec, but this change unexpectedly broke some functionality.

**Comment by FuDesign2008** [comment]
I think @bmneely is right and would also like to see this reopened.

**Comment by getaaron** [comment]
Thanks @fudesign2008
