### ISSUE TITLE
Tabs within code block are converted to 4 spaces?

### ISSUE THREAD

**Issue by reggi** [chjj/marked#644]
You can see I have to code blocks one with a two space indentation and one with a tab. The tab is oddly converted to 4 spaces.

`````` javascript
var marked = require('marked')
var Promise = require('bluebird')
var markedAsync = Promise.promisify(marked)
var markdown = [
  '```js',
  'if (true) {',
  '   console.log(\'word spaces\')',
  '}',
  '```',
  '```js',
  'if (true) {',
  ' console.log(\'word tabs\')',
  '}',
  '```'
].join('\n')
console.log(JSON.stringify(markdown))
markedAsync(markdown)
.then(function (html) {
  console.log(JSON.stringify(html))
})
``````

`````` javascript
"```js\nif (true) {\n  console.log('word spaces')\n}\n```\n```js\nif (true) {\n\tconsole.log('word tabs')\n}\n```"
``````

``` javascript
"<pre><code class=\"lang-js\">if (true) {\n  console.log(&#39;word spaces&#39;)\n}\n</code></pre>\n<pre><code class=\"lang-js\">if (true) {\n    console.log(&#39;word tabs&#39;)\n}\n</code></pre>\n"
```

**Comment by mbovel** [comment]
Same problem here. I think this is definitely a bug: code blocks should not be modified in any way. That's the behaviour promoted by [CommonMark](http://spec.commonmark.org/0.23/#indented-code-blocks).

[Discount](https://github.com/Orc/discount) and [Pandoc](http://pandoc.org), however, also seem to convert tabs to spaces.

**Comment by joshbruce** [comment]
#983

**Comment by Feder1co5oave** [comment]
You're right, commonmark says that. However, marked heavily relies on the fact that everything is indented with spaces. Code blocks, list, blockquotes...

**Comment by vixalien** [comment]
If it is not possible to let tabs remain the same, atleast allow the user the select the number of spaces they want.

**Comment by UziTech** [comment]
@vixalien you can convert them before you send the markdown to marked.
```js
marked.parse(markdown.replace(/\t/g, '  '))
```
