### ISSUE TITLE
Preserve new lines (\n) within a <code> block

### ISSUE THREAD

**Issue by reggi** [chjj/marked#645]
How do I preserve new lines (\n) within a `<code>` block?

`````` js
var marked = require('marked')
var Promise = require('bluebird')
var markedAsync = Promise.promisify(marked)

var markdown = [
  '```js',
  'if (true) {',
  '  console.log(\'word spaces\')',
  '}',
  '',
  '',
  '',
  '```'
].join('\n')

console.log(markdown)
markedAsync(markdown)
.then(console.log)
``````

And the output:

``````
```js
if (true) {
  console.log('word spaces')
}



```
<pre><code class="lang-js">if (true) {
  console.log(&#39;word spaces&#39;)
}
</code></pre>
``````

However if there are spaces then a character, the empty lines are available.

`````` javascript
var markdown = [
  '```js',
  'if (true) {',
  '  console.log(\'word spaces\')',
  '}',
  '',
  '',
  '',
  '```'
].join('\n')

console.log(markdown)
markedAsync(markdown)
.then(console.log)
``````

Here's the output

``````
```js
if (true) {
  console.log('word spaces')
}


x
```
<pre><code class="lang-js">if (true) {
  console.log(&#39;word spaces&#39;)
}


x
</code></pre>
``````

**Comment by chrisdrackett** [comment]
I'm not sure if this is the same problem, but I'm also not getting new lines when using a code block with `gym` on:

input:

![input](https://s3.amazonaws.com/f.cl.ly/items/3B0G0R41011f0R1n1t1i/Screen%20Shot%202015-09-02%20at%202.36.01%20PM.png)

output:

```<div> <span>test</span> </div> ```

expected output:

```
<div>
    <span>test</span>
</div>
```

**Comment by ChiChou** [comment]
https://github.com/chjj/marked/blob/38f1727ffee0820975677027b8968bc1954e6637/lib/marked.js#L764

This project simply render inline code and code block as the same. It's a serious bug.

**Comment by joshbruce** [comment]
#983

**Comment by Feder1co5oave** [comment]
This is still a bug.
http://spec.commonmark.org/0.28/#example-98

**Comment by Feder1co5oave** [comment]
Fixed
