### ISSUE TITLE
Cannot parse GFM table

### ISSUE THREAD

**Issue by novacrazy** [chjj/marked#647]
I'm trying to render this markdown:

``` markdown
# Page Title
-----------------------------------

<div class="columns">
    <div class="one-half column">
        ![Page logo][logo]

        **LOCATION AND DATE!**
        October 12 & 13, 2013
        County Fairgrounds

        [Click here](/flyer.pdf) for our show flyer.

        [Click here](/map.htm) for Directions and map

    </div>
    <div className="one-half column">

        | Club Officers | Position       |
        |---------------|----------------|
        | Person 1      | President      |
        | Person 2      | Vice President |
        | Person 3      | Treasurer      |
        | Person 4      | Secretary      |


    </div>
</div>

[logo]: /static/img/dist/logo.jpg?width=200&height=287
```

And marked fails to parse the GFM table while it is within the code blocks. If the table is by itself then it's fine, but used with anything else and it fails and just converts it to a paragraph.

My options look like this:

``` javascript
code = marked( code, {
        breaks:     true,
        smartypants: true,
        langPrefix: '',
        gfm:        true,
        sanitize:   true,
        xhtml:      true,
        tables:     true,
        sanitizer:  markdown.sanitizer,
        highlight:  function( code, lang ) {
            return highlight.highlight( lang, code, true ).value;
        },
        renderer:   renderer
    } );
```

where sanitizer is a function that does nothing except mark a flag then return the code, and the custom renderer is almost exactly the same as the original, just with a few CSS classes added into the code. Highlight.js is also used.

And regarding Highlight.js, if I take out the little bit of HTML and leave the table indented, marked will pass `undefined` to the `highlight` function, even though there are no code blocks in the above markdown. 

I've also tried `pedantic` mode and it doesn't change anything.

This is a major issue, and I'll have to look for an alternative markdown library if this persists. 

Here is an image of what it looks like rendered:
![qgl6xom](https://cloud.githubusercontent.com/assets/4708645/9365413/0988e908-4677-11e5-99c8-9f9c650a7884.png)

Obviously the image and links don't exist since I changed them for privacy reasons, but the table should still be rendered correctly.

**Comment by minwe** [comment]
Anything within HTML tag will be ignored by markdown parser.

You should move the table out of the HTML tag.

You can add wrapper by customizing table renderer, https://github.com/chjj/marked#overriding-renderer-methods.

**Comment by joshbruce** [comment]
#980
