### ISSUE TITLE
rename sanitize and add hook for URL sanitization

### ISSUE THREAD

**Issue by benjamin-atkin** [chjj/marked#65]
Sanitize doesn't do all that's required for sanitized HTML. One thing that's important when accepting user input is to sanitize URLs.

The following JavaScript:

``` javascript
var marked = require('marked');
marked.setOptions({sanitize: true})
console.log(marked("<a href=\"javascript:alert('test')\"></a>\n\n[click me!][1]\n\n[1]: javascript:alert('test')"))
```

Will output the following HTML:

``` html
<p>&lt;a href=&quot;javascript:alert(&#39;test&#39;)&quot;&gt;&lt;/a&gt;

</p>
<p><a href="javascript:alert(&#39;test&#39;)">click me!</a>

</p>
```

I think the sanitize option would be better named `escapeMarkup`.

To solve the URL problem, I think a good path would be to have an URL filter function in the options, with a conservative URL filter as the default.

**Comment by alexcjohnson** [comment]
It appears that since this discussion `sanitize: true` has been updated to remove `javascript:` links, but it lets `data:text/html;base64` links pass, which can *also* be used to execute javascript.

**Comment by scjody** [comment]
The best way to sanitize links is to _whitelist_ desired schemes, usually just `http:` and `https:`.  People invent new schemes all the time and you can't be sure that they're all implemented securely or don't have unforeseen consequences.

**Comment by joshbruce** [comment]
#984
