### ISSUE TITLE
Remove preferGlobal

### ISSUE THREAD

**Issue by monolithed** [chjj/marked#652]
```
➜ npm install
npm WARN prefer global jsdoc@3.3.2 should be installed with -g

├─┬ jsdoc@3.3.2
│ ├── marked@0.3.5
```

Could you remove [`"preferGlobal": true`](https://github.com/chjj/marked/blob/master/package.json#L9)?
It's no any sense and bad practice as well.

**Comment by MichielDeMey** [comment]
The CLI requires to be installed globally, hence the warning.

**Comment by monolithed** [comment]
@MichielDeMey, so why it should be installed globally?

**Comment by MichielDeMey** [comment]
Otherwise your system won't be able to recognize the CLI, unless you add your project's `node_modules` folder to your `$PATH` variable.

When installing it locally
```
➜ npm i marked
npm WARN prefer global marked@0.3.5 should be installed with -g
marked@0.3.5 node_modules/marked
➜ marked
zsh: command not found: marked
```

When installing it globally
```
➜ npm i -g marked
marked@0.3.5 node_modules/marked
➜ marked -o output.html
// works!
```

**Comment by monolithed** [comment]
I see what you mean, but I don't see any sense to install it globally.
Why the package should be installed globally?

**Comment by MichielDeMey** [comment]
It doesn't have to be installed globally to use the library, but it has to be if you plan to use the CLI.
Hence it's just a warning and not an error.

**Comment by monolithed** [comment]
> but it has to be if you plan to use the CLI.

There's an line in `package.json` for that:

```
 "bin": "./bin/marked"
``

**Comment by MichielDeMey** [comment]
That line won't tell NPM to symlink it to the `$PATH`.

From the NPM package.json specification:
```
On install, npm will symlink that file into prefix/bin for global installs, or ./node_modules/.bin/ for local installs.
```

So commands like
```
cat content.md | marked -o output.html
```
won't work if you install it locally, but will work if you install it globally.

**Comment by monolithed** [comment]
> won't work if you install it locally, but will work if you install it globally.

I see what you mean, but why it should be preferred for all users?

Npm does not recommend installing packages as root:

> Using sudo with npm is Very Not Recommended. Anyone can publish anything, and package installations can run arbitrary scripts." 

It was explained later in more detail as:

>  Option 4: HOLY COW NOT RECOMMENDED!! You can just use sudo all the time for everything, and ignore the incredibly obnoxious warnings telling you that you're insane for doing this.

[Why is evil?](http://blog.millermedeiros.com/node-js-protip-avoid-global-test-runners/)

How many users prefer this method of installation of ?
Do know who uses this package? [1165 packages](https://www.npmjs.com/package/marked)!
I don't want to see the warnings :kissing:

**Comment by MichielDeMey** [comment]
You should definitely NOT install anything as sudo.
This tool does not force you to install it using the sudo command, so I don't see the issue.

There is a difference between
```
sudo npm i -g marked
```

and

```
npm i -g marked
```

The former is not recommended like you said since it gives npm packages sudo powers.

If you can't install global npm packages without running sudo then your npm environment is bugged and you should solve it.

Check out SO on how to solve it.
http://stackoverflow.com/questions/19352976/npm-modules-wont-install-globally-without-sudo

Apart from that, no one is forcing you to install it globally and it will work just fine when installing it locally.
The warning is just there for those who wish to use the CLI, if you don't need it you may safely disregard the warning.

**Comment by monolithed** [comment]
> if you don't need it you may safely disregard the warning.
I don't want see this warning, because there're no any reason for it. 
Can you answer my question, why it should be preferred for all users?
It's really strange.

**Comment by joeyfromspace** [comment]
To use a cli mode, it is recommended to install packages globally. This is because you most likely do not have or want to add the node_modules folder for marked to your system $PATH variable.

If you do not want to use cli mode then don't install globally and ignore the message. 

The warning is meant for people who are expecting to use cli mode since there may be issues in doing so unless the package is installed globally.

**Comment by monolithed** [comment]
>The warning is meant for people who are expecting to use cli mode since there may be issues in doing so unless the package is installed globally.

Did you see README.md?

```
npm install marked --save
```

Why not:
```
npm install marked -g
```

it's confused!

I want to find out why this method of installation is preferred for all users and not documented. 
If someone wants to use the cli, let them read the doc :yum:

**Comment by monolithed** [comment]
doesn't happen in npm v3 https://github.com/npm/npm/issues/1648

**Comment by tcurdt** [comment]
I do see this with npm 3.5.3 and I also think the warning unwarranted.
If people want to use the CLI then they should install it globally.
No point of having a warning for people who are using it just as a library.

**Comment by wprl** [comment]
Many engineers require no warnings or errors during installation of a project.  They can cause confusion, especially to less technical people who may think there was an install error.  Global dependencies can also make deployment more complicated.  In my opinion `preferGlobal` should be deprecated.  

Is there anything preventing working around the issue with `$PATH`, like running with `./node_modules/.bin/marked`?  If not, perhaps splitting the cli component into its own module a la grunt-cli would allow us to prevent the superfluous warning message in our projects…

~My 2¢

**Comment by jasonkarns** [comment]
Agreed that this module should not preferGlobal. Even as a cli, it should be used locally with `$(npm bin)` or via an npm run-script. (these are the recommended ways to use CLIs within a project; unless the utility is intentionally not associated with a project, like a scaffold-generators for instance)
