### ISSUE TITLE
difference between github and marked GFM implementation

### ISSUE THREAD

**Issue by pacahon** [chjj/marked#654]
Example:

``````
1. First item:
    ```python
   >>> class Descr:
   ... def __get__(self, instance, owner):
   ... print(owner)
   ...
   `(REPEAT 3 TIMES)
2. second item
``````

github render it's like this:
1. First item:
   `python
   >>> class Descr:
   ... def __get__(self, instance, owner):
   ... print(owner)
   ...
   `
2. second item

But in `marked` - all fine. Any suggestions?

**Comment by Feder1co5oave** [comment]
Not sure what the question is, here.

**Comment by pacahon** [comment]
Me neither 👍
