### ISSUE TITLE
What would be the preferred method to add target="_blank" to links?

### ISSUE THREAD

**Issue by julmot** [chjj/marked#655]

**Comment by julmot** [comment]
@chjj

**Comment by drmuey** [comment]
lol, I missed this issue wehn searching. I have apull request in that does this: See issue 657

**Comment by julmot** [comment]
:+1: When will it be available @chjj?

**Comment by julmot** [comment]
Push!? @chjj @drmuey

**Comment by adam-lynch** [comment]
@julmot in the meantime, just use a custom renderer with your own link method.

**Comment by romanpitak** [comment]
Render links to external hosts with `target="_blank"`: https://github.com/romanpitak/pfm

Just a suggestion...

**Comment by julmot** [comment]
@adam-lynch Could you please describe how?

@romanpitak A URL to a different subdomain would be also a different host but should be handled like an internal link.

**Comment by romanpitak** [comment]
@julmot **you are right** and that's why it was just a suggestion. I wrote the extension just to suite my own needs.

**Comment by hardware** [comment]
@julmot :

```javascript
var marked   = require('marked');
var renderer = new marked.Renderer();

marked.setOptions({
  ...
});

renderer.link = function( href, title, text ) {
  return '<a target="_blank" href="'+ href +'" title="' + title + '">' + text + '</a>';
}

marked( message, { renderer:renderer });
```

**Comment by DelvarWorld** [comment]
And for the es6-y (and lazy):

    const renderer = new marked.Renderer();
    renderer.link = ( href, title, text ) => `<a target="_blank" href="${ href }" title="${ title }">${ text }</a>`;

**Comment by julmot** [comment]
I just want to suggest the following: `{:target="_blank"}` at the end of the link in markdown ([Reference](http://stackoverflow.com/a/4705645/3894981))

**Comment by KingScooty** [comment]
+1 for the @julmot is suggesting!
I'm surprised `{:target="_blank"}` doesn't already work!

**Comment by joshbruce** [comment]
#984

**Comment by andreasvirkus** [comment]
Same thing as @csytan's method, but with a small tweak to only modify the anchor element when we're linking to an external host :3 

```
const renderer = new marked.Renderer();
const linkRenderer = renderer.link;
renderer.link = (href, title, text) => {
  const localLink = href.startsWith(`${location.protocol}//${location.hostname}`);
  const html = linkRenderer.call(renderer, href, title, text);
  return localLink ? html : html.replace(/^<a /, `<a target="_blank" rel="noreferrer noopener nofollow" `);
};
const html = marked(markdown, { renderer });
```

**Comment by curran** [comment]
Related https://github.com/markedjs/marked/issues/144

**Comment by qertis** [comment]
Please support the attribute 
```
{:target="_blank"}
```

**Comment by jeffoxd** [comment]
Late, but putting here to let everyone know (in case someone going through the pain i am now):

> Same thing as [@csytan](https://github.com/csytan)'s method, but with a small tweak to only modify the anchor element when we're linking to an external host :3
> 
> const renderer = new marked.Renderer();
> const linkRenderer = renderer.link;
> renderer.link = (href, title, text) => {
>   const localLink = href.startsWith(`${location.protocol}//${location.hostname}`);
>   const html = linkRenderer.call(renderer, href, title, text);
>   return localLink ? html : html.replace(/^<a /, `<a target="_blank" rel="noreferrer noopener nofollow" `);
> };
> const html = marked(markdown, { renderer });

**doesn't** work if you're putting it in `marked.use({ renderer })` to allow your whole app/thing to use your fancy new renderer (as in you can just `marked.parse(html)` anywhere :(

It will result in `Uncaught TypeError: this.parser is undefined` error

I made some modifications, in my `marked.ts` (make sure to import it in your main file like `index.ts` or `main.tsx` etc.):
```
import { marked, Tokens } from "marked";

// modified https://github.com/markedjs/marked/issues/655#issuecomment-712380889
const renderer = {
  link({ href, title, text }: Tokens.Link): string {
    const localLink = href.startsWith(
      `${location.protocol}//${location.hostname}`
    );

    // to avoid title="null"
    if (title === null) {
      return localLink
        ? `<a href="${href}">${text}</a>`
        : `<a target="_blank" rel="noreferrer noopener" href="${href}">${text}</a>`;
    }
    return localLink
      ? `<a href="${href}" title="${title}">${text}</a>`
      : `<a target="_blank" rel="noreferrer noopener" href="${href}" title="${title}">${text}</a>`;
  },
};

marked.use({ renderer });

export default marked;
```

cheers~
