### ISSUE TITLE
Add a config option of whether or not to open links in a new tab or not?

### ISSUE THREAD

**Issue by drmuey** [chjj/marked#657]
default can be false to preserve the current default behavior, it just needs a way to keep certain comments/notes from taking folks offsite when they need to remain (e.g. post comments or ticket notes).

something like:

`marked.setOptions({ "linksInNewTab" : true });`

**Comment by drmuey** [comment]
NTS: https://github.com/chjj/marked/blob/master/lib/marked.js#L882

**Comment by drmuey** [comment]
Pull request: #659

**Comment by joshbruce** [comment]
#984
