### ISSUE TITLE
Different DOM structure for inline/fenced code blocks

### ISSUE THREAD

**Issue by gaui** [chjj/marked#667]
With GFM, both inline code blocks and fenced code blocks provide the following DOM structure:

    <p><code>...</code></p>

Inline code block:

    `code`

Fenced codeblock:

    ```
    code
    ```

I would like to style the inline code block differently with CSS than the fenced code block.

How can I do this? There's no way to target the inline code block.

**Comment by fnky** [comment]
What options are you using? It should produce
```
<pre><code>...</code><pre>
```

for fenced/block codes, and

```<p><code>...</code>></p>```

for inline code. For styling you can select `code` for inline and `pre code` for code blocks.

**Comment by gaui** [comment]
It produces in both cases `<p><code>... </code></p>`

I'm using default options.

**Comment by fnky** [comment]
Can you give an example of your code and markdown?

**Comment by gaui** [comment]
Here is a screenshot. I'm using `marked()` without any options so it's using default options. As you can see there is no difference between inline code block and a fenced code block.

![image](https://cloud.githubusercontent.com/assets/477881/10418721/2f4a479e-7053-11e5-8378-2dcbb4370e6c.png)

**Comment by fnky** [comment]
This is actually correct behaviour in GFM. It's required to have a newline (`\n`) character after start fence (except you can provide a language extension after start fence)

```md
```\n
Fenced code block\n
```
```

becomes

```
<pre><code>Fenced code block</code></pre>
```

and

```
```Fenced code block```
```

becomes

```
<p><code>Fenced code block</code></p>
```

The reason is that inline code uses single back ticks so further unescaped back ticks will be ignored in the output.

**Comment by gaui** [comment]
@fnky Thank you very much. Problem solved. :)
