### ISSUE TITLE
Adding captions/titles to tables

### ISSUE THREAD

**Issue by amlwwalker** [chjj/marked#674]
Hi, 
Loving this library by the way.

I am trying to add a title/caption to a table. At first i tried to add a `[title/caption here]` as the last line of the table, however that didn't work. Then I tried to center a line of text below the table with `->content here<-` - which is the common way to center text from markdown. 

Any suggestions of how I can do either of the above in marked?

Out of interest, can I add markdown features? For instance, I love this: http://bramp.github.io/js-sequence-diagrams/ and I want to be able to call upon it from markdown...
Thanks

**Comment by joshbruce** [comment]
See #980
