### ISSUE TITLE
how to get/set original text

### ISSUE THREAD

**Issue by whisper-bye** [chjj/marked#679]
```html
<script>
document.getElementById('content').innerHTML = marked("~~hello~~");
</script>
```

how to get/set original text?? like "\~~hello~~"
thx~

**Comment by Feder1co5oave** [comment]
You simply can't. You need to take care yourself of saving the original markdown code you parsed.
In your code, the string "~~hello~~" exists only as a literal string in that javascript block, and is lost afterwards.
