### ISSUE TITLE
Header processes differently on client and server

### ISSUE THREAD

**Issue by willrstern** [chjj/marked#687]
using `marked.min.js`:
- `marked("- #1 fan")` -> `<ul>\n<li>#1 fan</li>\n</ul>\n`

using marked via npm
- `marked("- #1 fan")` -> `<ul>\n<li><h1 id="1-fan">1 fan</h1>\n</li>\n</ul>\n`

**Comment by Feder1co5oave** [comment]
Have you tried updating your npm package? According to https://www.npmjs.com/package/marked it is updated to the last version available here, which includes https://github.com/ledsun/marked/commit/1df58933c788c9a673b35b4463cca8e4a48e51aa that introduced the different behaviour you're seeing.

**Comment by ankitduseja** [comment]
+1 And the version I am using is 0.3.5 installed from npm. It is generating id's for h tags.

**Comment by joshbruce** [comment]
See #981
