### ISSUE TITLE
Port to .NET

### ISSUE THREAD

**Issue by jez9999** [chjj/marked#688]
This seems like the kind of thing that I want, but how about porting it to .NET?  I don't want to run a node.js server on my machine just to render some markdown, and .NET would be pretty portable because of Mono.

Failing that, is there anything out there like marked but for .NET?

**Comment by aaroncalderon** [comment]
Can you use it in the browser as explained in the [README.md](https://github.com/chjj/marked/blob/master/README.md#browser)?

>
### Browser
>
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Marked in the browser</title>
  <script src="lib/marked.js"></script> <!-- .js file for browser implementation -->
</head>
<body>
  <div id="content"></div>
  <script>
    document.getElementById('content').innerHTML =
      marked('# Marked in browser\n\nRendered by **marked**.');
  </script>
</body>
</html>
```

Look at the [`lib/marked.js`](https://github.com/chjj/marked/blob/master/lib/marked.js) file.

Regards.

**Comment by joshbruce** [comment]
Closing as out of scope and stale.
