### ISSUE TITLE
Apostrophes render incorrectly/differently depending on context, breaking most JS

### ISSUE THREAD

**Issue by benwasser** [chjj/marked#698]
With sanitize set to false, apostrophes will still be sanitized depending on other content in the input.

To recreate, render the following line with {sanitize: false}:

``` html
<div>
   <script>console.log('test1')</script>
</div>
```

Apostrophes will convert to `&#39;`

I don't think this is the intended behavior because rendering `<script>console.log('test1')</script>` (without the div tags) does not convert the apostrophes.

**Comment by Feder1co5oave** [comment]
Is there any particular reason you wrap a script element into a div like that?
`marked` is designed to parse markdown (inline) content in html tokens:
~~~
$ marked
<div>
	_is this bold?_
</div>
^D
<div>
    <em>is this bold?</em>
</div>
~~~
unless the top html element is either `script`, `pre` or `style`. Or, unless you've specified the `pendantic` option:
~~~
$ marked --pedantic
<div>
   <script>console.log('test1')</script>
</div>
^D
<div>
   <script>console.log('test1')</script>
</div>
~~~
Unfortunately, `pedantic` triggers full compliance with the old `markdown.pl`, which may not be what you desire.

**Comment by Feder1co5oave** [comment]
I think this was answered @joshbruce

**Comment by joshbruce** [comment]
Concur. No follow up from poster so far. Will tag @benwasser directly, just in case. Closing pending follow-up from creator.
