### ISSUE TITLE
Links to Markdown files

### ISSUE THREAD

**Issue by idleberg** [chjj/marked#701]
Would you consider an option to convert all links to Markdown files to HTML files? We're using Markdown for our documentation, linking to other Markdown files that are part of this. It would be useful if we could convert these links when generating HTML files.

**Comment by Feder1co5oave** [comment]
Use a custom renderer for links.

**Comment by stevenMouret** [comment]
If this custom renderer already exist, I will take it ;)

**Comment by joshbruce** [comment]
Closing as resolved. See #956
