### ISSUE TITLE
Add versioning to the files

### ISSUE THREAD

**Issue by haringsrob** [chjj/marked#713]
Hi,

Would be nice to see the version number in atleast the .js files.

This allows systems to use specific version checks.

Regards,

**Comment by prewk** [comment]
Isn't the information you're looking for already available in git?

**Comment by haringsrob** [comment]
It would be nice if for example "marked.min.js" contains: version 3.5.0

**Comment by prewk** [comment]
I'd recommend you to use npm, your `package.json` will tell you what version you have currently (or `npm list --depth=0 | grep marked`)

**Comment by joshbruce** [comment]
Closing as answered.
