### ISSUE TITLE
The highlight.js demo is invalid.

### ISSUE THREAD

**Issue by taadis** [chjj/marked#716]
```
marked.setOptions({
  highlight: function (code) {
    return require('highlight.js').highlightAuto(code).value;
  }
});
```

highlight is invalid in the html page display.

**Comment by sebastianjonasson** [comment]
neither works for me.

**Comment by sebastianjonasson** [comment]
Actually, it did work by adding the css manually.

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/styles/default.min.css">

**Comment by joshbruce** [comment]
#983
