### ISSUE TITLE
feature request: add image attributes like pandoc

### ISSUE THREAD

**Issue by amueller** [chjj/marked#720]
It would be great to have extended image attributes as in pandoc:

https://github.com/jgm/pandoc/commit/244cd5644b44f43722530379138bd7bb9cbace9b

In particular for sizing the image.

I'm using jupyter notebooks, which uses marked for rendering in-browser and pandoc for rendering everything else. Having as big an overlap of features between the two would be great.

**Comment by amueller** [comment]
or should I do that on my side considering #339?

**Comment by spacedawwwg** [comment]
+1

**Comment by joshbruce** [comment]
#989
