### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by vongohren** [chjj/marked#724]
With this many issues and PRs, I wonder if the project still lives when its 7 months since last update?

**Comment by lferreirawork** [comment]
+1

**Comment by webbedspace** [comment]
The project not being worked on is not an "issue" with the code, and posting observations like these to the issue tracker is just cluttering it up. If you want to ask the maintainer about this project's future, please just contact him directly.

**Comment by Snorlock** [comment]
@webbedspace i feel that it's important to raise the issue to make other who probably are thinking the same aware of whats happening. I have many times seeked the issuetracker to see if this question have been asked and if a response have been made. Sometimes this issue can spark the contribution spirit in someone who will fork the project and keep it maintained there. Its all about sheeding light on an issue with the repository.

**Comment by anaran** [comment]
:+1:

**Comment by allenfantasy** [comment]
@Snorlock Good point. And since this project's last commit would be nearly 7 months ago ( and 127 PRs  waiting to be merged ), it's easy to doubt that if this project is still on the track.

**Comment by Snorlock** [comment]
Yeah I believ it myself, but I want a comment from @chjj

**Comment by sn3p** [comment]
+1

**Comment by 75lb** [comment]
i'd say this project is dead.. 

can anyone recommend a reliable fork to switch to? If not, does anyone have a day or two free to create one and work through the pile of outstanding PRs?

**Comment by imcaffrey** [comment]
:+1:

**Comment by JCMais** [comment]
@75lb  Not a fork, but https://github.com/markdown-it/markdown-it is the most active markdown plugin for js right now, it was a fork of https://github.com/jonschlinkert/remarkable.

**Comment by leocaseiro** [comment]
How about https://github.com/showdownjs/showdown?

**Comment by wifiextender** [comment]
The Code doesn't age.

**Comment by Guichaguri** [comment]
@wifiextender So you should use Windows 95 :)

**Comment by gabrielcsapo** [comment]
@wifiextender it is kind of sad that now there is a code vulnerability in it and we can't get that fixed. Is there an ability to move this to another maintainer? npm rights and such.

**Comment by gabrielcsapo** [comment]
@chjj vscode is using this and they are moving away from it because of lack of movement on the project...

**Comment by akuma** [comment]
+

**Comment by tcurdt** [comment]
Please see https://github.com/chjj/marked/issues/756

**Comment by vongohren** [comment]
Closing for cleanup
