### ISSUE TITLE
Perhaps it is time to consider a secondary maintainer of this repo?

### ISSUE THREAD

**Issue by SimonCropp** [chjj/marked#727]

**Comment by Andifeind** [comment]
+1

I'm using marked in all my projects an I hope it is not dead. A second maintainer would be great.

**Comment by noraj1337** [comment]
Project is dying (https://github.com/chjj/marked/issues/724), please add a maintainers !

**Comment by noraj1337** [comment]
This issue seems more active:
` Please do a call for maintainers #756`
https://github.com/chjj/marked/issues/756

**Comment by matt-** [comment]
Its not a maintainers issue. Many are merged into the master branch and waiting to be published.

**Comment by noraj1337** [comment]
@matt- you're right. @chjj seems to only works on [bcoin](https://github.com/bcoin-org/bcoin) now. That's why is switched to markdown it instead. That is active and support [CommonMark](http://commonmark.org/).

**Comment by matt-** [comment]
As  a maintainer and would love to see this project live, but there is really no point in diving in to the backlog if we can get them out.

**Comment by joshbruce** [comment]
See #956
