### ISSUE TITLE
Bug in parsing of headers

### ISSUE THREAD

**Issue by eGavr** [chjj/marked#729]
Hi!

I have such a markdown:

``` md
#h1

####### h2
```

Calling of `marked.lexer` returns such tokens

``` js
{ type: 'paragraph', text: '#h1' }
{ type: 'paragraph', text: '####### h2' }
```

But `github` displays `h1` and `h2` as headings, not as `paragraph`.

This case works fine in `0.3.3` and is broken since `0.3.4`.

Thank you!

**Comment by edsadr** [comment]
having the same issue in 0.3.6

**Comment by joshbruce** [comment]
See #981

**Comment by Feder1co5oave** [comment]
Only up to 6 hashes are allowed for headings, so `####### h2` is not valid.
You always need space between the # and the text.

**Comment by joshbruce** [comment]
Surprised I didn't catch the no space part of this...I did with the hashtag submission though; so, at least I'm not completely slacking. ;)
