### ISSUE TITLE
Feature Request: A renderer that emits markdown

### ISSUE THREAD

**Issue by prasannavl** [chjj/marked#731]
Currently, it only has a html renderer, but doesn't have a renderer that emits markdown from the tokens. A markdown renderer would be very useful to make this feature complete.

**Comment by Feder1co5oave** [comment]
Why would you implement a markdown-to-markdown coverter, if I may ask? And what is preventing you from implementing such a renderer?

**Comment by sebastienbarre** [comment]
Hey, was wondering if you found a solution? The markdown-to-markdown workflow is useful if you want to parse some Markdown, and automatically update some contents, but bring it back to Markdown. Say, to update a README.md file automatically, given some knowledge about the project.

**Comment by prasannavl** [comment]
@sebastienbarre, yup, that's exactly what I needed it for at the time of filing the issue. Unfortunately though, I didn't have the time to create a custom renderer. So, I ended up using complex regexes in the update phase to solve my particular need. But that was only since the scope of what I needed was limited and well defined in nature.

**Comment by sebastienbarre** [comment]
@prasannavl a good soul just pointed out `remark`.

Here is how it can be done. The below example insert a TOC in your Markdown.

```javascript
const markdown = require('remark-parse');
const report = require('vfile-reporter');
const stringify = require('remark-stringify');
const toc = require('remark-toc');
const unified = require('unified');

const example = `
# Alpha
## Table of Contents
## Bravo
### Charlie
## Delta
`;
unified()
  .use(markdown)
  .use(toc)
  .use(stringify)
  .process(example, (err, file) => {
    console.error(report(err || file));
    console.log(file.toString());
  });
```
which will output:
```
# Alpha
## Table of Contents
-   [Bravo](#bravo)
    -   [Charlie](#charlie)
-   [Delta](#delta)
## Bravo
### Charlie
## Delta
```

**Comment by prasannavl** [comment]
@sebastienbarre `remark` looks pretty neat. Thanks for sharing. :) 
As to the issue, I guess it'll just have remain as it is, for now.

**Comment by joshbruce** [comment]
See #956 - Closing as solved by the snippet. Currently we are focusing on revising and fixing issues with the Markdown to HTML conversion. There is something to be said for having the ability to provide a move object-based model to the renderer to then generate HTML, but not the priority right now.
