### ISSUE TITLE
the Math.random call is confusing; please explain

### ISSUE THREAD

**Issue by alice0meta** [chjj/marked#733]
https://github.com/chjj/marked/blob/18fb6a639a4a77dd59650879bcad10d833c40067/lib/marked.js#L747

**Comment by alice0meta** [comment]
oh, I figured it out, you're unique-ifying for spam harvesters

then this issue is a request for you to add a brief comment saying such, for future people :)

**Comment by Feder1co5oave** [comment]
The function name and doc ("mangle links") sound pretty self-explanatory to me, to be honest. Additional comments may be appreciated, though.
