### ISSUE TITLE
Did this can convert html to markdown code?

### ISSUE THREAD

**Issue by DirtyHao** [chjj/marked#737]
Did this can convert html to markdown code?

**Comment by popatop15** [comment]
I am also interested in converting the html back to markdown format.

**Comment by joshbruce** [comment]
See #956 

@matt- and @UziTech: Does Markdown not do this today?

**Comment by UziTech** [comment]
I don't believe marked can do this. You may want to look in to [html-md](https://www.npmjs.com/package/html-md)
