### ISSUE TITLE
Using the # sign

### ISSUE THREAD

**Issue by nelsonlho** [chjj/marked#744]
Doesn't seem like # is working as expected, but everything else seems to work.
I have also included bootstrap

Any idea?

http://codepen.io/nelsonlho/pen/GZBmVG?editors=1111

**Comment by scott-m-sarsfield** [comment]
@nelsonlho 

(I'm not affiliated, but...)

I tried your link and got a 404.  Is your pen still active?  (Or did you resolve your issue?)

**Comment by nelsonlho** [comment]
this is really weird.  Let me replicate what I did again, and place a new issue if necessary.  Closing this for now.  Thanks
