### ISSUE TITLE
adding custom rules at runtime

### ISSUE THREAD

**Issue by ciel** [chjj/marked#750]
I am using marked to render Markdown in an application, but I have a situation where I want to create some 'custom' renderings - similar to the way `gimmicks` are used in [md-wiki](http://dynalon.github.io/mdwiki/#!index.md).

I want to add some custom rules, such as the following;

```
[!alert:warning] > some text goes here as a warning
[!alert:success] > some text goes here as success
```

And have it render output like...

```
<blockquote class="alert warning">Some text goes here as a warning</blockquote>
<blockquote class="alert success">Some text goes here as success</blockquote>
```

I've seen that I can do this in `marked` by adding to the `rules` on the `block` literal, but this requires me to hard-code them into the actual library. Is there a way to add a rule to marked at runtime, that can allow me to leave the core library alone?

**Comment by rhauteki** [comment]
You could use the [overriding methods](https://github.com/chjj/marked#overriding-renderer-methods) to change the way a link is rendered depending on the link text just like md-wiki does.

**Comment by rubencodes** [comment]
I think instead of overriding an existing method, what OP wants is to define a custom rule.
e.g. All existing rules should stay the same, but maybe `{ some text }` has a custom behavior.

**Comment by joshbruce** [comment]
The focus right now is to correct for targeted specifications before revisiting extensibility.

See #956
