### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by AkashKG** [chjj/marked#758]
Uncaught TypeError: Cannot read property 'replace' of undefined

**Comment by jek10** [comment]
Same error here.

**Comment by CandiW** [comment]
Just got the same error....

**Comment by ghettosoak** [comment]
Me too!

**Comment by silverlight513** [comment]
I just got this error but from some quick debugging it happens when you pass `undefined` to the marked function. Check the variable you're sending to be converted by the marked processor.
