### ISSUE TITLE
Expanding relative links

### ISSUE THREAD

**Issue by tallesl** [chjj/marked#762]
Is there any support for expanding relative links to absolute ones?

[Looks like I'm not the first in need of such feature](https://github.com/optimizely/marked#changes-in-the-fork). I ended up setting [&lt;base&gt;](http://stackoverflow.com/q/1889076) in the document, but this brings some issues of its own.

**Comment by joshbruce** [comment]
Believe this was submitted as a PR; therefore, will be part of a future release. Closing.
