### ISSUE TITLE
[FEATURE REQUEST] Add Typescript Definition

### ISSUE THREAD

**Issue by DerekTBrown** [chjj/marked#766]
An increasing number of developers are using Typings.  There is currently an externally-developed Typings file for Marked at DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/marked/marked.d.ts), but I am not sure how how well maintained it is.  It would be great to simply include that definition in the official marked package to ensure it is kept up to date.

**Comment by joshbruce** [comment]
Reference project does not appear to exist. Not enough details in description to know what's being requested.

Please see #956 and comment here if still interested in this capability.

**Comment by jhpratt** [comment]
@joshbruce I'm still looking for up-to-date typings. The current type declaration is located [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/marked), and the header comment indicates it's current as of 0.4.0.

**Comment by UziTech** [comment]
I think that would be a great thing for the community to maintain. Our goal is to make marked self sufficient, and do one thing great (change markdown to HTML). We don't want to keep up with typescript, flow, and all future typing systems.

If you want to make sure it is up to date you could maintain them yourself.

**Comment by joshbruce** [comment]
@jhpratt: Agree with @UziTech on this one. If this became part of Marked it would be well beyond the 2.0 release, which might be a ways off depending on the community.
