### ISSUE TITLE
[FEATURE REQUEST] Add comment syntax

### ISSUE THREAD

**Issue by cchan** [chjj/marked#769]
Perhaps something like `!` at the beginning of the line (not counting whitespace) can exclude the content from the HTML completely, unlike the `<!-- -->` syntax.

```
- Item One
!- Item Two
- Item Three
```

should compile to

```
<ul>
<li>Item One</li>
<li>Item Three</li>
</ul>
```

**Comment by cchan** [comment]
Apparently I'm wrong; `<!-- -->` doesn't do that; it becomes escaped text.

**Comment by joshbruce** [comment]
Closing as comments are not supported by the two specifications being targeted.

See #956
