### ISSUE TITLE
Prevent images from wrapping in paragraph tags

### ISSUE THREAD

**Issue by sn3p** [chjj/marked#773]
I'm rendering images inside a `<figure>` element like this:

```js
var renderer = new marked.Renderer();

renderer.image = function (href, title, alt) {
  var out = '<figure>';
  out += '<img src="' + href + '" alt="' + alt + '">';
  if (title) {
    out += '<figcaption>' + title + '</figcaption>';
  }
  out += '</figure>';
  return out;
};

marked.setOptions({
  gfm: true,
  renderer: renderer
});
```

Figure elements are block level, but markdown wraps the output inside a`<p>`:

```html
<p><figure><img src="http://someimage.png" alt="">...</figure></p>
```

But this is not valid HTML and renders like this: 

```html
<p></p>
<figure><img src="http://someimage.png" alt="">...</figure>
<p></p>
```

I found out that lexers have a `paragraph` type, but I'm not sure how to set these:

```js
var token = marked.lexer('![](http://someimage.png)')
// [{
//   text: "![](http://someimage.png)",
//   type: "paragraph"
// }]

marked.parser(token)
// "<p><figure><img src="http://someimage.png" alt=""></figure></p>"
```

**How to prevent a renderer method getting wrapped in a paragraph element?**

**Comment by Feder1co5oave** [comment]
There's no easy way to do this: you're trying to render a markdown inline element (an image) into an html block element (a figure).
A hack a could think of is to override the `paragraph` renderer too, in such a way that when the inline content is just a `<figure>` (outputted by your image renderer), it is not wrapped in `<p>` tags:

```javascript
renderer = new marked.Renderer;
renderer.paragraph = function(text) {
    if (text.startsWith('<figure') && text.endsWith('</figure>'))
        return text;
    else
        return '<p>' + text + '</p>';
}
```

I've not tested this.
