### ISSUE TITLE
v-if to false results in "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by AdrianB93** [chjj/marked#776]
If there is markdown area within a div that has had a `v-if` that goes from true to false, it results in a `"Cannot read property 'replace' of undefined."` because the element is no longer in the DOM. This filter is not aware of this.

eg)

```
<div v-if="showArea">
    <div v-html="$root.active_editor.content | marked"></div>
</div>
```

While that example would easily be solved with a `v-show`, my use case has variations of properties in each item, and the `v-if` contents can handle each different variation depending on a `type` in the computed property `active_item`.

**Comment by AdrianB93** [comment]
#758

**Comment by Feder1co5oave** [comment]
This is specific to Vue.js (which I do not know). Just make sure that `marked` be called upon a string, even an empty one, if needed. It seems that at times that `$root.active_editor.content` becomes undefined.

**Comment by Feder1co5oave** [comment]
Maybe take a look at #752 ?
