### ISSUE TITLE
Using Marked without npm?

### ISSUE THREAD

**Issue by kittykatattack** [chjj/marked#777]
Hello!

Can anyone explain how to use Marked without requiring it as npm module?
For example, I would like to just link to the `min.js` file and do something like this:

    var marked = ....then whatever I need to do to initialize the marked object;

What should the above code look like?

**Comment by RyanZim** [comment]
@kittykatattack Are you running your JS in node.js? If so, you can do:
```
var marked = require('./relative/path/to/marked.min.js');
```

**Comment by RyanZim** [comment]
@kittykatattack If this resolves things for you, please close this issue. Thanks!
