### ISSUE TITLE
h1 tags work differently in github than they do here even with gfm: true

### ISSUE THREAD

**Issue by joncodo** [chjj/marked#784]
#Hello 

Turns into `"<p>#Hello</p>\n"`

But # Hello 

Turns into `"<h1 id=\"hello-world\">Hello</h1>\n"`

In github, you can make a markdown H1 tag with either #Hello or # Hello (Note the space) and it will treat it the same way.

**Comment by Feder1co5oave** [comment]
Not true:

# Hello

#Hello

**Comment by matt-** [comment]
I agree with @Feder1co5oave this works exactly the same as Github and works as expected.
