### ISSUE TITLE
Multiline Issues

### ISSUE THREAD

**Issue by D14RAP** [chjj/marked#785]
Using the below code where the php echo is echoing markdown from a database it doesn't output unless the content has only a single line.

`<div id="utility-description"></div>
                            <script>
                                $("#utility-description").html(marked("<?php echo $utility["description"]; ?>"));
                            </script>`

**Comment by joshbruce** [comment]
Closing.

Given that you are using PHP for server-side rendering, not JS and aren't doing client-side rendering, believe this issue is out of scope for Marked. Recommend using:

"graham-campbell/markdown": "^8.0"

Which uses https://github.com/thephpleague/commonmark.
