### ISSUE TITLE
Blockquote not rendering

### ISSUE THREAD

**Issue by whimsicaldreamer** [chjj/marked#790]
I dont know why but the blockquotes are not being rendered.
I type `> text` and while sending this message my PHP side converts it to `&gt; text`. When fetched on the client side I get `>text` as the display while the HTML rendered is `<p>&gt; block</p>`

**Comment by inventionsbyhamid** [comment]
I have the same issue. Unfortunately I even tried showdown.js and it also doesn't render blockquote. I double checked I am using correct syntax for blockquote. Any fixes?

**Comment by whimsicaldreamer** [comment]
Probable fix is setting a proper css for the blockquote tag.

**Comment by inventionsbyhamid** [comment]
The problem is on my side and not in the library. I have some escaping/unescaping characters issue when using marked on dynamic text. Just tested 'document.getElementById('content').innerHTML = marked('> Test');` and it worked.

**Comment by tangxiangmin** [comment]
I have found the same question! By the suggest of upstairs, I fixed the problem by 
```
// html
<div class="item-bd" id="content"></div>
<pre id="tmp" style="display: none">{{$article['content']}}</pre>

// js
document.getElementById('content').innerHTML = marked(document.getElementById('tmp').innerText);
```
Use <pre></pre>to save the raw markdown and then transform the content to html, it takes effect in my blog.  Hope it can help others.

**Comment by TangMonk** [comment]
same issue

**Comment by leoyli** [comment]
This issue should be closed.  Since that's the issue is from the user not the lib itself.  Remember to replace your string using `.replace(/&gt;+/g, '>')` before put it into `marked()`.

**Comment by Feder1co5oave** [comment]
@joshbruce this is not related to marked

**Comment by joshbruce** [comment]
@Feder1co5oave: Thanks! I don't think I even saw this ticket before.
