### ISSUE TITLE
Feature Request: Option to escape curly brackets in codeblocks

### ISSUE THREAD

**Issue by georgeedwards** [chjj/marked#791]
As discussed [here](http://stackoverflow.com/questions/39077150/invalid-html-unexpected-closing-tag-code/39077180), if a code block contains `{` or `}`, it can cause issues with front end frameworks. It would be really useful to set an option to auto-escape brackets in the code block. i.e.

``````
```
    @import { url(&#39;~/platform.css&#39;) };
```
``````

=>

```
<code>
{{'@import { url(&#39;~/platform.css&#39;) };'}}
</code>
```

**Comment by georgeedwards** [comment]
Possibly a better approach would be to parse and curly brackets in code blocks as `&#123;` and `&#125;`?

**Comment by joshbruce** [comment]
#983
