### ISSUE TITLE
Unreliable code block rendering

### ISSUE THREAD

**Issue by georgeedwards** [chjj/marked#792]
I have two code blocks in my markdown string. This doesn't parse properly:

``````
```bash
tns platform add ios
```
``````

However, this one does:

``````
```bash
cd sample-Groceries
```
``````

These are the two results:

```
<code>bash
tns platform add android</code>

<pre><code class="lang-bash">cd sample-Groceries
</code></pre>
```

They are both in the same string, processed at the same time of the same machine...

Here you can see the whole file, [markdown](https://gist.githubusercontent.com/georgeedwards/ad0a2951138bf26ed16a98625086ffcc/raw/78bdcb5677ec1d38a5fc61a713a43e48f1e90cbf/markdown.md) and [html](https://gist.github.com/georgeedwards/acbf175c678f39dac3beb012034ee42a)

**Comment by Feder1co5oave** [comment]
I have no problem parsing both. Provide your complete source please.

**Comment by MohammadYounes** [comment]
I have a similar issue using v0.3.6, for example:

```
<h1> H1 </h1>
<h2> H2 </h2>

```html
<h1> H1 </h1>
<h2> H2 </h2>
``` 
<h1> H1 </h1>
Some content
```

Would produce:

```html
<h1> H1 </h1>
<h2> H2 </h2>

<code>html
&lt;h1&gt; H1 &lt;/h1&gt;
&lt;h2&gt; H2 &lt;/h2&gt;</code>

<h1> H1 </h1>

<p>Some content</p>
```

But if you add a matching `h2` after the code block:

```
<h1> H1 </h1>
<h2> H2 </h2>

```html
<h1> H1 </h1>
<h2> H2 </h2>
``` 
<h1> H1 </h1>
<h2> H2 </h2>

Some content
```

The problem goes away and you'll get a correct code block:

```html
<p><h1> H1 </h1></p>
<h2> H2 </h2>

<pre><code class="lang-html">&lt;h1&gt; H1 &lt;/h1&gt;
&lt;h2&gt; H2 &lt;/h2&gt;
</code></pre>
<p><h1> H1 </h1></p>
<h2> H2 </h2>

<p>Some content</p>
```

https://runkit.com/5834c46bd8fb6400141ac375/58c98b8b927973001429a666

**Comment by joshbruce** [comment]
#983
