### ISSUE TITLE
Outputting IDs into html when they are not needed

### ISSUE THREAD

**Issue by jesus-cortex** [chjj/marked#806]
Hi,

Using marked in command line and having this markdown file

`# This is a test`

if I run marked test.md -o test.html this is what I get:

`<h1 id="this-is-a-test">This is a test</h1>`

Why is id="this-is-a-test" there? What option should I use to prevent that behaviour?

**Comment by aaronpk** [comment]
This is usually seen as desired behavior, in order to easily provide anchor links to sections based on the header text.

**Comment by sneakernets** [comment]
is this still in the code? I desperately need a parser that has this feature.

**Comment by joshbruce** [comment]
#981

**Comment by joshbruce** [comment]
@sneakernets: I believe it is.
