### ISSUE TITLE
render tables within list items

### ISSUE THREAD

**Issue by grant-g** [chjj/marked#811]
Marked explicitly will not render a table within a list item.  Test snippet:
1. item 1
   
   | aaa | bbb |
   | --- | --- |
   | ccc | ddd |
2. item 2

I think I've read in the past that this was done to satisfy some markdown compatibility test, though I can't find this now.

This is a request to reconsider this decision.  We've been affected by this behavior several times, and a table within a list item is not an unusual pattern.  GitHub is willing to render tables within items.  How about marked?

**Comment by Feder1co5oave** [comment]
Wow, I didn't even know this!
Fact is, list and table regex are already pretty complex as it is...

**Comment by joshbruce** [comment]
See #980
