### ISSUE TITLE
Top level marked.min.js out of sync with lib/marked.js

### ISSUE THREAD

**Issue by reedspool** [chjj/marked#815]
minified file edited "a year ago", while lib/marked.js was edited 2 months ago.

**Comment by jankeesvanandel** [comment]
We see the same thing, making the release more or less useless for us. Is it possible to re-release it?

**Comment by Framartin** [comment]
The `marked.min.js` file should be updated very quickly. **This is a high priority issue**. I'm seeing **a lot** of FLOSS using this file without knowing that they are vulnerable to #592. This issue is creating XSS in all of them.

Please @chjj update it!

**Comment by rugk** [comment]
Any news?

**Comment by joshbruce** [comment]
Fixed in latest release, I believe.
