### ISSUE TITLE
Formatting seems hit or miss

### ISSUE THREAD

**Issue by ddproxy** [chjj/marked#820]
I'm using leafdocs which uses marked to parse markdown in documentation.

I find that formatting from tables, code blocks, and lists are all hit or miss. Sometimes they generate close enough html or don't pick up the formatting at all.

### Example:
```
Several CDN's have Leaflet.Draw available.

| CDN and type   |   URI            |
| -------------- | ---------------- |
| unpkg css| https://unpkg.com/leaflet-draw@0.4.1/dist/leaflet.draw.css |
| unpkg js | https://unpkg.com/leaflet-draw@0.4.1/dist/leaflet.draw.js |
| cdnjs css| https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.0/leaflet.draw.css |
| cdnjs js | https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.0/leaflet.draw.js |
```

Obviously expect it to parse into...

Several CDN's have Leaflet.Draw available.

| CDN and type   |   URI            |
| -------------- | ---------------- |
| unpkg css| https://unpkg.com/leaflet-draw@0.4.1/dist/leaflet.draw.css |
| unpkg js | https://unpkg.com/leaflet-draw@0.4.1/dist/leaflet.draw.js |
| cdnjs css| https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.0/leaflet.draw.css |
| cdnjs js | https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.0/leaflet.draw.js |

but it formats as

```
| CDN and type | URI | | -------------- | ---------------- | | cdnjs css| https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.0/leaflet.draw.css | | cdnjs js | https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.0/leaflet.draw.js |
```

Is there anything or anyone else having similar issues? Also, is there a way to 'debug' or verbosely identify what's going on while parsing?

https://github.com/Leaflet/Leafdoc/issues/21

**Comment by nreese** [comment]
You have to add a newline before the table starts. The problem I am having is styling the table. Where is the css?

```
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Marked in the browser</title>
  <script src="marked.js"></script>
</head>
<body>
  <div id="content"></div>
  <script>
    const txt = `
# Marked in browser
Rendered by **marked**

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |`
    document.getElementById('content').innerHTML =
      marked(txt);
  </script>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/373691/27230091-57792d2e-526b-11e7-925e-988c3d69848b.png)

**Comment by faheel** [comment]
@nreese To get GitHub-like styling, use [github-markdown-css](https://github.com/sindresorhus/github-markdown-css).

**Comment by Feder1co5oave** [comment]
Working as expected / solved. @joshbruce
