### ISSUE TITLE
Infinite loop with newline character

### ISSUE THREAD

**Issue by webfella** [chjj/marked#824]
I'm seeing an issue where parsing a string with a newline character in combination with the inline option creates an infinite loop (it works fine with the default settings)

The error is `Uncaught Error: Infinite loop on byte: 10`

With an example being `window.marked(stringWithCharacter, { inline: true });`

**Comment by Feder1co5oave** [comment]
This could have been interesting, unfortunately no input sample was given so we'll never know
 @joshbruce

**Comment by joshbruce** [comment]
Fair. Closing. @webfella: Repost, if possible, and give more details regarding expectation versus result.
