### ISSUE TITLE
They might add the option to add color to the text.

### ISSUE THREAD

**Issue by hypernova7** [chjj/marked#825]
So you can change the color of the text using a syntax or command, so you can change the color text either in bold, in italics or in titles h1, h2, h3, etc. And also for links. Something like this: *{#f66} hello* or **{blue} hello** or also #{red} title. it would be a good idea.

**Comment by jounisah** [comment]
Markdown syntax has no support for text color.

**Comment by hypernova7** [comment]
Yes, I know. But how could you customize it to be able to add that option. What would be the best way to do it and personalize it my way. Basically I want to do something similar like bbcode, but with the markdown syntax.

**Comment by joshbruce** [comment]
Given the specifications being targeted this seems out of scope.

Regarding your question, I do not believe there would be a way to do it without going beyond even the original intent of Markdown.
