### ISSUE TITLE
Does not Handle Markdown Escapes In Link Href

### ISSUE THREAD

**Issue by mjbvz** [chjj/marked#829]
From https://github.com/Microsoft/vscode/issues/14968

Marked does not seem to properly handle markdown escapes inside of links. Only the link text itself is properly handled, the `title` and `href` are not:

```js
var marked = require('marked');
marked('[text\\.](http://example\\.com "\\.title")')
```

produces:

```
<p><a href="http://example\.com" title="\.title">text.</a></p>
```

**Comment by joshbruce** [comment]
#984

**Comment by Feder1co5oave** [comment]
Related to #229.

Must review escaping of special and not-special characters via backslashes in various parts of the document. Should take a look at the `escape` inline rule, but some escaping problems exist in parts which are not inline-parsed, such as link titles.

http://spec.commonmark.org/0.28/#backslash-escapes

**Comment by Feder1co5oave** [comment]
See

https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Btext%5C.%5D(http%3A%2F%2Fexample%5C.com+%22%5C.title%22)
