### ISSUE TITLE
Escaping "|" in table

### ISSUE THREAD

**Issue by tamlok** [chjj/marked#831]
How to display a `|` in the table? I tried to use `` `|` ``, but failed. Hoedown, another markdown renderer could handle it correctly! Thanks very much!

**Comment by xcatliu** [comment]
@Shazoo, one fallback way is to use html tag:

```html
<code>&#124;</code>
```

**Comment by noraj1337** [comment]
https://github.com/chjj/marked/issues/595

**Comment by joshbruce** [comment]
See #980
