### ISSUE TITLE
New line not work

### ISSUE THREAD

**Issue by CosmaVito** [chjj/marked#835]
New line inside paragraph not work.
![immagine](https://cloud.githubusercontent.com/assets/14861632/21295069/35ddac54-c54d-11e6-9816-c9761fb68f4e.png)

Instead if i put two spaces after the new line i have the correct result...

![immagine](https://cloud.githubusercontent.com/assets/14861632/21295071/405d5b66-c54d-11e6-8f33-be53290cc2b0.png)

why this strange behavior??

Has anyone found a solution?Thanks :)

**Comment by joallard** [comment]
The latest Commonmark spec says to put a `\` at the end of the line, but I'm not sure it's implemented here

**Comment by j16180339887** [comment]
Have you set `breaks: true`？

**Comment by Jayde-Im** [comment]
I had a same problem, but @j16180339887 's comment helped! Thanks :D
I should've read configurations thoroughly

**Comment by Feder1co5oave** [comment]
Solved @joshbruce

**Comment by MaheshSasidharan** [comment]
> Have you set `breaks: true`？

Thanks @joeky888. This worked for me. 

`marked(markdown, { breaks: true })`

**Comment by styfle** [comment]
You can read the full set of options on the [USING_ADVANCED docs page](https://marked.js.org/#/USING_ADVANCED.md).

**Comment by shawn-mty** [comment]
`marked.parse( someString, { breaks: true })`

**Comment by SpyrexDE** [comment]
Settings `breaks: true` doesn't work for me:
```
console.log(content);
console.log(marked.parse(content, { breaks: true, gfm: true }));
```
gives me
```
# This is a title\nLorem ipsum dolor sit amet, consectetur adipiscing elit.
<h1>This is a Title\nLorem ipsum dolor sit amet, consectetur adipiscing elit.</h1>
```
