### ISSUE TITLE
Address issues found in test/index.js [Opened by bitHound]

### ISSUE THREAD

**Issue by dudeman805** [chjj/marked#843]
bitHound discovered 46 LintIssues, and 2 ComplexFunctions in [test/index.js](https://github.com/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/index.js). For details go to [bitHound](https://www.bithound.io/github/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/index.js).

**Comment by matt-** [comment]
Although arguably it should.. this project does not have a lint file or any rules setup. How can you report "lint issues" without having agreed on lint rules?
