### ISSUE TITLE
Ignore some characters

### ISSUE THREAD

**Issue by badbye** [chjj/marked#845]
Is it possible to do some configuration to ignore some characters? For example, forbidden to use the `_` character.

I am using Mathjax to render the latex equations, however sometimes `marked` convert `$x_1y_1$` to `$x<em>1y</em>1$`.

**Comment by badbye** [comment]
I find the rules of `em` and try to edit it, however it does not work. 
```
> marked.InlineLexer.rules.em
/^\b_((?:__|[\s\S])+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/

> marked.InlineLexer.rules.em = /^\*((?:\*\*|[\s\S])+?)\*(?!\*)/

> marked('_hi_')
"<p><em>hi</em></p>
"
```

**Comment by badbye** [comment]
Alright, I see. Here is my solution:

```
> marked.InlineLexer.rules.gfm.em = /^\*((?:\*\*|[\s\S])+?)\*(?!\*)/

> marked('_hi_')
"<p>_hi_</p>
"
```

Please let me know if there is a better solution.

**Comment by Jiang-Xuan** [comment]
you want to output '_' char ?
you can escape some char.
for example:

    marked('\_hi\_')

**Comment by Jiang-Xuan** [comment]
@badbye 
If you edit `marked.InlineLexer.rules.em` to `/^\*((?:\*\*|[\s\S])+?)\*(?!\*)/`.

`_marked_` can not to generate `em` element

**Comment by Feder1co5oave** [comment]
It's as if you asked the C compiler to not parse plus signs, they're part of the language and they have semantics too.

**Comment by joshbruce** [comment]
See #936 - closing as covered by another issue or request. Integrating math.
