### ISSUE TITLE
Snyk Security Failure

### ISSUE THREAD

**Issue by knoxcard** [chjj/marked#848]
Failing Snyk Test

✗ High severity vulnerability found on marked@0.3.6
- desc: Cross-site Scripting (XSS) via Data URIs
- info: https://snyk.io/vuln/npm:marked:20170112
- from: node_services@1.0.0 > npm-shrinkwrap@6.0.2 > msee@0.1.2 > marked@0.3.6
Fix: None available. Consider removing this dependency.

**Comment by knoxcard** [comment]
Holy Snykes!

**Comment by matt-** [comment]
Why open another issue when the url you posted has a link to the PR with the fix? 

This has already been addressed. Waiting for a version bump and push. https://github.com/chjj/marked/pull/844

**Comment by knoxcard** [comment]
So everyone else is aware, that's why.

**Comment by matt-** [comment]
Please don't open bug tickets for issues you know are already merged.
-- 
../matt
