### ISSUE TITLE
在单下划线或者是单星号中转义单下划线或单星号会导致转义失效

### ISSUE THREAD

**Issue by Jiang-Xuan** [chjj/marked#853]
## 在单下划线或者是单星号中转义单下划线或单星号会导致转义失效

    marked('_cma\\_ed_')
    // output
    "<p>_mark<em>ed</em></p>"
    marked('*cma\\*rked*')
    // output
    "<p><em>mark</em>ed*</p>"

我认为是这个正则导致了问题的产生：

    em: /^\b_((?:[^_]|__)+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/

应该在单下划线或者是单星号的匹配中允许转义字符`\_`、`\*`的出现。

**Comment by maicss** [comment]
666, 给外国人提issue也用中文，简直屌。

**Comment by hechuanhua** [comment]
笑尿

**Comment by osoc** [comment]
有贴出代码，应该没有关系。不需要看文字，只需要看代码。

**Comment by joshbruce** [comment]
I do apologize. Cannot read. Closing. Please comment again, if desired.
