### ISSUE TITLE
leave HTML code as is

### ISSUE THREAD

**Issue by Pomax** [chjj/marked#855]
Right now, marked will convert this:
```
...
<div className="note">
## take note:
the following text *should* be taken into account
</div>
...
```
into this:
```
...
<div className="note">
## take note:
the following text *should* be taken into account
</div>
...
```
that is to say: it doesn't convert it at all. It treats the `<div>` as somehow being meaningful syntax rather than "just text without any markdown syntax rules that match it" and so it refuses to convert the content of that div,  despite the fact that markdown has no divs: it's just inert text that needs to be preserved.

**Comment by nerai** [comment]
Correct me if I'm wrong, but I believe you have to have empty between `##` and any html code.

**Comment by nerai** [comment]
First of all, to have a better chance of this working, you should put an empty line between the `div`s and any markdown. However, as far as I know, this library does not implement the required feature, sadly.

But: This library does implement this for `span`s instead of `div`s. That may be sufficient as a workaround for you. (It even works without the empty lines I mentioned, which I guess is nonstandard, not sure.)

```
<span>
# a
- 1
- 2
</span>
```

**Comment by matt-** [comment]
A lot of specs (actually almost all) do have "raw" html tags like divs:   http://spec.commonmark.org/0.27/#example-119 and GFM

That said I believe it is correct that in a code block \`\`\`  it should return the html encoded version of this as http://spec.commonmark.org/0.27/#example-88 describes

**Comment by nerai** [comment]
@matt- Those are just `...`, not  ```

I've looked into this some more. First of all, I'm still not sure if this library is supposed to be implementing commonmark. If it does not, then not converting markup within divs is standard behavior as far as I know, and the case would be moot.

I got some interesting results when I tested this again. Inserting OP's example literally, I could not reproduce the problem:

![1](https://cloud.githubusercontent.com/assets/1230531/23461502/7f493068-fe8a-11e6-9e12-12599f74c51e.png)

But when I remove the trailing `...`, I get only a partial result:

![2 2](https://cloud.githubusercontent.com/assets/1230531/23461567/bbdce722-fe8a-11e6-8241-2885dcf923fd.png)

More tests:

```
<div style="background:red">
## x
</div>
.
```
yields
![3](https://cloud.githubusercontent.com/assets/1230531/23461748/6c25a92a-fe8b-11e6-84d7-b49349a61731.png)

And

```
<div style="background:red">
## x
</div>

.
```
yields
![4](https://cloud.githubusercontent.com/assets/1230531/23461790/9dc2f4ec-fe8b-11e6-96bc-b2b687b0def0.png)

This behavior looks wrong to me. Am I missing anything obvious?

**Comment by Pomax** [comment]
The original code was for terseness, using something more spaced out like 
```
regular markdown content

<div className="note">

## take note:

the following text *should* be taken into account

</div>

more regular markdown content
```
generates:
```
<p>regular markdown content</p>
<div className="note">

## take note:

the following text <em>should</em> be taken into account

</div>

<p>more regular markdown content</p>
```
with the content of the div somehow treated as "I should skip over this" by the library. The real trick isn't whether it should always do one thing or another, this should be something one can toggle, where calling something like:
```
const converted = marked(content, { passoverHTML: true });
```
makes it copy HTML tags verbatim without doing anything to them, and without recognizing content between some `<x>` and corresponding `</x>` as anything other than "more text to be converted as markdown". 
```

**Comment by omnilord** [comment]
I am running into an issue where if the first line of the markdown is an HTML tag, it treats the first line as though it's wrapped in ```.  This can be fixed by putting an empty new line before the HTML tag, BUT because there is a leading new line, it also inserts a `<br/>` tag which throws off the spacing for the rest of the display.

**Comment by joshbruce** [comment]
#985
