### ISSUE TITLE
Question about js\n syntax

### ISSUE THREAD

**Issue by ee7klt** [chjj/marked#860]
in this example var markdownString = '```js\n console.log("hello"); \n```'; what is the syntax `js\n`?
i tried looking in all the markdown docs but didn't see this.
all i know is that if i try to use a code block using triple backticks, marked just converts it to `<code></code>` without any added classes so i cannot get syntax highlighting, however if i prefix all the code with js\n, the appropriate highlight class is added. any ideas?

**Comment by trezy** [comment]
That's the language identifier and then a new line character. The `js` just tells the parser that this code block is supposed to be Javascript. The `\n` is an escape character for newlines that will be rendered appropriately by the browser.

**Comment by Feder1co5oave** [comment]
@joshbruce not marked related
