### ISSUE TITLE
Cross-site Scripting (XSS) via Data URIs - snyk notifications

### ISSUE THREAD

**Issue by knoxcard** [chjj/marked#863]
✗ High severity vulnerability found on marked@0.3.6
- desc: Cross-site Scripting (XSS) via Data URIs
- info: https://snyk.io/vuln/npm:marked:20170112
- from: node_services@1.0.0 > marked@0.3.6
Fix: None available. Consider removing this dependency.

✗ High severity vulnerability found on marked@0.3.6
- desc: Cross-site Scripting (XSS) via Data URIs
- info: https://snyk.io/vuln/npm:marked:20170112
- from: node_services@1.0.0 > msee@0.1.2 > marked@0.3.6
Fix: None available. Consider removing this dependency.

✗ High severity vulnerability found on marked@0.3.6
- desc: Cross-site Scripting (XSS) via Data URIs
- info: https://snyk.io/vuln/npm:marked:20170112
- from: node_services@1.0.0 > npm-shrinkwrap@6.0.2 > msee@0.1.2 > marked@0.3.6
Fix: None available. Consider removing this dependency.

**Comment by matt-** [comment]
https://github.com/chjj/marked/commit/cd2f6f5b7091154c5526e79b5f3bfb4d15995a51

**Comment by matt-** [comment]
I am keeping this one open until the change is pushed, but I wanted to rename the ticket to make it more search friendly.

**Comment by matt-snider** [comment]
This seems important enough to cut a new release for. Any reason that isn't being done?

**Comment by stramel** [comment]
@chjj @matt- @paulirish Any word on getting a tag for this fix?

**Comment by the-t-in-rtf** [comment]
0.3.7 finally came out, and did include the previous submitted fixes.  Unfortunately, there's still one high-severity vulnerability that is supposed to be addressed by [the upcoming 0.3.9 release](https://github.com/chjj/marked/pull/958).

**Comment by joshbruce** [comment]
Believe 0.3.9 corrects all these issues. Please confirm and comment, if incorrect.
