### ISSUE TITLE
Extend parser or renderer

### ISSUE THREAD

**Issue by dekhanov-vladislav-yumasoft** [chjj/marked#865]
Is it possible to extend parser or renderer in this lib somehow? I like this lib and i just had a wish to add support of video in my project but didn't find the way to extend parser or even renderer.

**Comment by jjljyn** [comment]
@dekhanov-vladislav-yumasoft Hey, did you find any way to extend parser? I want to create my own custom manner and I don't want to override anyone.

**Comment by joshbruce** [comment]
Closing for now. See #956 - Concentrated on XSS vulnerabilities. Now concentrating on bug fixes - submit PRs to help out. Then probably going to work on extending.
