### ISSUE TITLE
Why `"preferGlobal": true,` in package.json

### ISSUE THREAD

**Issue by ryuran** [chjj/marked#870]
Hello here.

One of my project dependency depend to marked, so I have a warning in my log during a npm install
```
npm WARN prefer global marked@0.3.6 should be installed with -g
```

Why `"preferGlobal": true,` in package.json ?
https://github.com/chjj/marked/blob/master/package.json#L9

**Comment by antgonzales** [comment]
+1

**Comment by jnordberg** [comment]
+1 this is a library module first and a cli util second

**Comment by Feder1co5oave** [comment]
+1

**Comment by joshbruce** [comment]
@matt- and @UziTech - Thoughts?

**Comment by UziTech** [comment]
duplicate #652 

I agree

[preferGlobal is deprecated anyways](https://docs.npmjs.com/files/package.json#preferglobal)

**Comment by joshbruce** [comment]
Do we have a PR that removes this from the package.json

**Comment by UziTech** [comment]
#768

**Comment by joshbruce** [comment]
Merged.
