### ISSUE TITLE
How to disable tags <h1>, <hr> etc..? Generally, how to disable a particular tag?

### ISSUE THREAD

**Issue by Dzhakhar** [chjj/marked#871]
It's possible?

**Comment by Feder1co5oave** [comment]
See https://github.com/chjj/marked/issues/420#issuecomment-44746538

**Comment by joshbruce** [comment]
Most likely this would be part of the 0.5.0 milestone. We are focusing on fixing defects to cover the two primary specifications supported by Marked. Closing to consolidate. If you would like to see this functionality please submit a PR based on the guidelines in #956 - and it can be flagged for the 0.5.0 milestone. Thank you.
