### ISSUE TITLE
Change or disable plain link renderer

### ISSUE THREAD

**Issue by Redsandro** [chjj/marked#873]
When writing a link inline without markdown formatting, such as http://www.google.com, it will automatically become a link. Can I change this behavior (I only want it rendered when prepended by `^` or `\s`), or alternatively, disable this feature?

I've tried overriding `autolink` in the renderer but it doesn't seem to change anything.

**Comment by chadoh** [comment]
@chjj I would be willing to help with this issue, if you give me a pointer on how to accomplish it.

**Comment by joshbruce** [comment]
#984
