### ISSUE TITLE
Add option to reset reference links in lexer

### ISSUE THREAD

**Issue by MadLittleMods** [chjj/marked#877]
Add some way to reset reference links in the lexer.

In order to achieve some better isolation when processing multiple pieces of markdown, we want to reset the link references in between runs otherwise references used in a previous message can leak to subsequent messages.

Currently when using the `Lexer`, we are achieving this by resetting an internal variable. But I'd rather just pass in an officially documented option to the lexer that would reset whenever it lexes. Here is an example of how we are currently resetting the lexing reference links:

```js
const marked  = require('gitter-marked');
const lexer = new marked.Lexer();

function processMarkdown() {
  // Reset any references
  lexer.tokens = [];
  lexer.tokens.links = {};

  const tokens = lexer.lex(text);
  const renderer = new marked.Renderer();
  const parser = new marked.Parser({ renderer: renderer });
  return parser.parse(tokens);
}
```

---

### Example

```md
[foo][1]

[1]: https://google.com/
```

```md
arr[1]
```

Without resetting references, the second piece of markdown will have the linked `1` reference leaked to it.

```html
arr<a href="https://google.com/" rel="nofollow" target="_blank" class="link">1</a>
```

---

 - https://github.com/gitterHQ/gitter-markdown-processor/pull/7
 - https://github.com/gitterHQ/gitter/issues/1041

**Comment by joshbruce** [comment]
#984
