### ISSUE TITLE
table no work

### ISSUE THREAD

**Issue by dyf2015** [chjj/marked#881]
```
why this is no work:
参数说明
参数 | 参数类型|说明
---|---|---
maindata|JSON|主表数据集合

and this is work:
参数说明

参数 | 参数类型|说明
---|---|---
maindata|JSON|主表数据集合
```

**Comment by dyf2015** [comment]
![Uploading F49D0753-E86C-4FAC-A961-CCFA8B5289CC.png…]()

**Comment by tekul** [comment]
I guess the simplest answer is that tables are a github extension to markdown, and that's also how they work in github, as you can see:

why this is no work:
参数说明
参数 | 参数类型|说明
---|---|---
maindata|JSON|主表数据集合

and this is work:
参数说明

参数 | 参数类型|说明
---|---|---
maindata|JSON|主表数据集合

Is there some reason why it matters in your application?

**Comment by joshbruce** [comment]
See #980
