### ISSUE TITLE
Is there a way to disable the autolink?

### ISSUE THREAD

**Issue by NoahDragon** [chjj/marked#882]
I would like to disable the feature of auto link. Is there a way to do so?

Thanks in advance.

**Comment by SamBrishes** [comment]
Hello,

you can overwrite each renderer method by using the [Renderer](https://github.com/chjj/marked#renderer) object. 

The following example would not autlink `https://github.com/chjj/marked/` but still auto-links `[GitHub](https://github.com/chjj/marked/)`.

```javascript
var render = new marked.Renderer();
render.link = function(href, title, text){
    if(this.options.sanitize){
        try{
            var prot = decodeURIComponent(unescape(href))
                .replace(/[^\w:]/g, '')
                .toLowerCase();
        } catch(e) {
            return "";
        }
        if(prot.indexOf('javascript:') === 0 || prot.indexOf('vbscript:') === 0 || prot.indexOf('data:') === 0){
            return ""; 
        }
    }
    
    if(href === text && title == null){
        return href;
    }
    var out = '<a href="' + href + '"';
    if(title){
        out += ' title="' + title + '"';
    }
    out += '>' + text + '</a>';
    return out;
};

marked("https://github.com/chjj/marked", {renderer: render});
// Output: https://github.com/chjj/marked

marked("[GitHub](https://github.com/chjj/marked)", {renderer: render});
// Output: <a href="https://github.com/chjj/marked">GitHub</a>
```

I hope this helps you.

Sincerely,
Sam.

**Comment by NoahDragon** [comment]
Thank you, @SamBrishes 
Exactly what I'm looking for.

**Comment by dwilches** [comment]
Thanks.

I updated it a bit for my use case: I want links that contain a protocol like `https://www.google.com` to behave as links, but things like `www.google.com` not to behave as links:
```typescript
let render = new marked.Renderer();
render.link = function (href, title, text) {
    if (this.options.sanitize) {
        try {
            let prot = decodeURIComponent(unescape(href))
                .replace(/[^\w:]/g, "")
                .toLowerCase();

            if (prot.indexOf("javascript:") === 0 || prot.indexOf("vbscript:") === 0 || prot.indexOf("data:") === 0) {
                return "";
            }
        } catch (e) {
            return "";
        }
    }

    // Only interpret links that contain a protocol
    if (!text.startsWith("http://") && !text.startsWith("https://")) {
        return text;
    }

    return `<a href="${ href }"'>${ text }</a>`;
};
marked.setOptions({ renderer: render });
```

**Comment by jimniels** [comment]
FWIW neither of the solutions above worked for me...

I have a bit of text in markdown that looks like this:

```md
Here's some links:

- www.iosicongallery.com
```

I don't want that `www...` to get turned into a link.

[This suggestion](https://github.com/markedjs/marked/issues/882#issuecomment-291029431):

```js
if(href === text && title == null){
  return href;
}
```

Doesn't work because, by the time the `href` and `text` get to my renderer, they are different, i.e. somewhere marked.js is taking the text `www.iosicongallery.com` in my mardown file and turning it into `{ href: "http://www.iosicongallery.com", text: "www.iosicongallery.com"}`. So that condition doesn't catch my use case.

[This suggestion](https://github.com/markedjs/marked/issues/882#issuecomment-754855376):

```js
// Only interpret links that contain a protocol
if (!text.startsWith("http://") && !text.startsWith("https://")) {
  return text;
}
```

Doesn't work either because it'll turn _all links_ which have been explicitly marked as such in markdown, i.e. `[link](https://...)` into plain text. So it works on my `www.iosicongallery.com` case, but it also strips all my manually specified links in markdown into plain text.

**Comment by UziTech** [comment]
@jimniels

You can try replacing the `url` [tokenizer](https://marked.js.org/using_pro#tokenizer).

```js
marked.use({
  tokenizer: {
    url(src) {
      // disable gfm autolinks
    },
  },
});

marked(`
https://www.example.com

<https://www.example.com>

[www.example.com](https://www.example.com)
`)
```

```html
<p>https://www.example.com</p>
<p><a href="https://www.example.com">https://www.example.com</a></p>
<p><a href="https://www.example.com">www.example.com</a></p>
```

**Comment by jimniels** [comment]
@UziTech does replacing the url tokenizer, as you've denoted, merely disable gfm but _only_ for links? i.e. if I have `{gfm: true}` it'll keep gfm for other elements, just not links?

Also, a preliminary test seems to indicate that this works without me actually doing anything, i.e.

```js
marked.use({
  tokenizer: {
    url(src) {
      // having nothing here disables gfm autolinks
    },
  },
});
```

Does that sound right? I'm a little unsure of the mechanics here...

**Comment by UziTech** [comment]
Yes the `url` tokenizer is just used to create the link tokens for gfm autolinks. The tokenizer is given the `src` and it is supposed to check if there is a gfm autolink at the beginning of `src`. If it returns `undefined` that lets the lexer know that there is no gfm autolink token there.

If you wanted it to detect links sometimes (e.g. only `www.my-website.com`), you would have to check `src` and return the appropriate link token.

```js
marked.use({
  tokenizer: {
    url(src) {
      if (src.startsWith("www.my-website.com")) {
        const text = "www.my-website.com";
        return {
          type: "link",
          raw: text,
          text,
          href: "https://www.my-website.com",
          tokens: [
            {
              type: "text",
              raw: text,
              text
            }
          ]
        };
      }
    },
  },
});
```
