### ISSUE TITLE
How do you put the markdown results in a html template

### ISSUE THREAD

**Issue by modelprinting** [chjj/marked#883]
Forgive the ignorance, I am somewhat new to gulp. This markdown compiles to HTML, but it doesn't include the `<html>` and `<body>` tags or whatever in the results. 

Is the best way to create a html template and use "gulp-file-include" to integrate the markdown into it? Is this considered "the standard way"?

**Comment by joshbruce** [comment]
@UziTech - Not sure this is how Marked is to be used. Isn't Marked a dynamic markdown converter? Not a static output generator...maybe both?

**Comment by UziTech** [comment]
¯\\\_(ツ)\_/¯

I've never used gulp-file-include but couldn't you just include the tags around the output? 

```javascript
`<html><body>${marked(someMarkdown)}</body></html>`
```
