### ISSUE TITLE
Bower.json version mismatch

### ISSUE THREAD

**Issue by jt000** [chjj/marked#893]
[The version is declared in bower.json as 3.4](https://github.com/chjj/marked/blob/master/bower.json#L3), however the current release on bower is 3.6. This causes an error when running `bower install`:
`bower marked#^0.3.6 mismatch Version declared in the json (0.3.4) is different than the resolved one (0.3.6)`

**Comment by joshbruce** [comment]
Believe two Bower updates have been merged; therefore, should be included in a future release...maybe.

See #956
