### ISSUE TITLE
[Bug] Heading works when using the "#" togeter the text

### ISSUE THREAD

**Issue by Plasmmer** [chjj/marked#909]

**Comment by joshbruce** [comment]
#981

**Comment by Feder1co5oave** [comment]
This is per [spec](http://spec.commonmark.org/0.28/#atx-headings).

**Comment by joshbruce** [comment]
Not sure I'm following what's happening here. With Markdown - the space after the hash(es) is what makes it a header (the spec part, I think, unless I missed something somewhere). So, not reopening this one as it seems to be saying that the only way to get a header to render is with a space following the hash, which is as expected.

A non-spaced hash would be a hashtag and might be prone to autolinking of some type, but that's a whole other conversation.
