### ISSUE TITLE
This library is XSS vulnerable

### ISSUE THREAD

**Issue by smithb1994** [chjj/marked#916]
Even with sanitize enabled, data uri are allowing XSS attacks:

`[xss link](data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K)`

A good solution, is to only allow http or https links.

**Comment by matt-** [comment]
This has been reported a few times. The maintainer will not respond to PR's or push new versions. 
 
https://github.com/chjj/marked/issues/863
https://github.com/chjj/marked/issues/869

and pull request https://github.com/chjj/marked/pull/844
