### ISSUE TITLE
extra line breaks not rendering the expected blank lines

### ISSUE THREAD

**Issue by Shawson** [chjj/marked#917]
Hi,

I have a problem where marked doesn't seem to render blank lines?  For example;

```
console.log(marked('I am using __markdown__.\r\n\r\n\r\nhow cool <br>is this', {breaks:true, sanitize:true, gfm:true}));
VM3061:1 <p>I am using <strong>markdown</strong>.</p>
<p>how cool &lt;br&gt;is this</p>
```

I would expect a couple extra <p></p> between those lines?  What am I missing?

Many thanks

**Comment by joshbruce** [comment]
This seems like you are attempting add line breaks to the HTML itself...formatting the HTML, which I don't believe is within scope of the secifications we follow. See #956 

If this functionality is part of those specifications, please let me know.
