### ISSUE TITLE
Unexpected ordered list render result

### ISSUE THREAD

**Issue by ArtemisSaber** [chjj/marked#918]
I'm using marked as markdown parser for my personal blogging site. I found that when treating ordered list it behaves differently on server-side and client-side

* How to produce this problem :  
A client-side real-time markdown previewer like this one:
~~~
        function preview(){
            document.getElementById('Preview').innerHTML = marked($('textarea').val())
        }
~~~
A server-side markdown renderer using default config: 
`var parsedContent = marked(content)`

Use markdown string like the following as input:
`1. This is a markdown string \n * to show that something goes wrong`

* What is expected: 
That string should be rendered like the following both on client-side and server side
~~~
<ol>
    <li>This is a markdown string</li>
    <li>to show that something goes wrong</li>
</ol>
~~~
* What is actually happening:  
That string would render right result on client-side using Chrome browser version 58  
On server, the render result was incorrect, what the server actually gave was:
~~~
<ol>
    <li>This is a markdown string</li>
</ol>
<ul>
    <li>to show that something goes wrong</li>
</ul>
~~~

**Comment by Jiang-Xuan** [comment]
`1. This is a markdown string \n * to show that something goes wrong` is incorrect.

try this:

`1. This is a markdown string \n 2. to show that something goes wrong`

**Comment by ArtemisSaber** [comment]
@Jiang-Xuan It is a viable workaround. However what I'm looking for is not workaround. The key point here is that it treat the same string differently on server or on client

**Comment by Jiang-Xuan** [comment]
Have a look at <https://runkit.com/embed/5byhgmo4b53i>.

**Comment by Jiang-Xuan** [comment]
Perhaps the space behind the '\n' affects the result.

**Comment by ArtemisSaber** [comment]
@Jiang-Xuan Oh great, now we have three kind of output here. My server gave me something strange,now this one is giving out even stranger result

**Comment by joshbruce** [comment]
See #982
