### ISSUE TITLE
Data obtained using Ajax, using marked transformation, `\n` can not be converted, local is OK

### ISSUE THREAD

**Issue by sosout** [chjj/marked#920]
`import marked from 'marked';
const markedText = "# Marked in browser\n\nRendered by **marked**.";
marked(markedText);
"`
This is OK!

However，
`ajax
....
marked(markedText)
`
This is not OK!

**Comment by Feder1co5oave** [comment]
Unclear.

**Comment by Feder1co5oave** [comment]
@joshbruce close this? doesn't look marked-related

**Comment by joshbruce** [comment]
Agreed. Think I was going to ask if there was a transformation happening in the AJAX request. If an object is returned and passed to Marked, probably doesn't know what to do there.
