### ISSUE TITLE
TypeError: src is undefined Please report this to https://github.com/chjj/marked

### ISSUE THREAD

**Issue by dagostinelli** [chjj/marked#927]
OK -- I'm reporting it.

I'm calling this: `var rawMarkup = marked(this.props.some_text, {sanitize: true});`

In some cases, some_text is undefined.  I put a null check now, but maybe it shouldn't crash?  I don't know.

**Comment by BalamChaac** [comment]
I have the same problem here:

I get data from firestore:
<markdown [data]=" (story | async)?.story ">

the text is only = HelloWorld

**Comment by Feder1co5oave** [comment]
Solved by #682

**Comment by joshbruce** [comment]
Closing.
