### ISSUE TITLE
BUMP: Extending Custom Elements

### ISSUE THREAD

**Issue by DerekTBrown** [chjj/marked#928]
There needs to be a way of adding custom elements.  A lot of people are asking about it:

https://github.com/chjj/marked/issues/865 
https://github.com/chjj/marked/pull/821
https://github.com/chjj/marked/issues/60
https://github.com/chjj/marked/issues/57
https://github.com/chjj/marked/pull/35

**Comment by DerekTBrown** [comment]
@chjj doesn't look like anyone is maintaining this project.  Are you looking for someone to help out?

**Comment by matt-** [comment]
Dupe of #865
#821
#60
#57
#35
