### ISSUE TITLE
Check that `src` is a string and throw useful error

### ISSUE THREAD

**Issue by adius** [chjj/marked#934]
Currently it prints `TypeError: src.replace is not a function` if you try to pass a buffer.
Not very helpful.

Not the first who got confused: https://github.com/chjj/marked/issues/867

**Comment by BalamChaac** [comment]
I have the the same problem here, but I get data from firestore

The inserted data is like this

` <markdown [data]=" (story | async)?.story ">`

the markdown text is only: HelloWorld
