### ISSUE TITLE
`img` by itself not recognized as inline html by the renderer 

### ISSUE THREAD

**Issue by whatrocks** [chjj/marked#939]
The renderer is picking up `img` tags wrapped in `div` or `p` tags as inline html, but it does not detect `img` tags by themselves. Is there some way to configure this to detect standalone `img` tags as inline html by the renderer?

**Comment by Feder1co5oave** [comment]
Provide some examples, please.

**Comment by joshbruce** [comment]
See #989 - closing to consolidate
