### ISSUE TITLE
how to access parsed headings separately

### ISSUE THREAD

**Issue by xralphack** [chjj/marked#940]
any way to access parsed headings separately?

I want to make a table of markdown heading in other place.

please help ~

**Comment by Feder1co5oave** [comment]
Take a look at https://github.com/jonschlinkert/markdown-toc

**Comment by joshbruce** [comment]
Most TOCs I've built are a post operation. Parse the Markdown to get the HTML...at this point, we have all the `h` elements. Then queryselect the DOM and built a list. Could be what Markdown-toc is doing. Closing for now.

Flagging for possible inclusion in the 0.5.0 milestone.
