### ISSUE TITLE
Will be intact in this case

### ISSUE THREAD

**Issue by pea3nut** [chjj/marked#942]
```js
var mdSource =`
<div></div><p></p>

# title

text

<div></div>
`;
var Marked =require('marked');
console.log(Marked(mdSource));// will be intact
```

**Comment by joshbruce** [comment]
Are those backticks for defining the string literal?

**Comment by pea3nut** [comment]
Is the backticks means the `?

Yes, It's the ES6 template string.

**Comment by joshbruce** [comment]
I could be wrong as I'm not that intimately familiar with Marked's codebase, but I'm pretty sure Marked, as it stands, does not handle ES6 template strings.

Marked uses regular expressions and I'm not sure if the ES6 template string is interpreted by the renderer/regular expression the same way as a pure string literal. Given some other tickets I've seen, I'm also not sure how much of it is the template string literal versus the inclusion of the HTML tags (think there's a flag to allow HTML tags).

Please try following (this should help to inform whether this is a new feature request, or a defect):

```js
// pure string literal
var mdSource ='
<div></div><p></p>

# title

text

<div></div>
';

// remove HTML tags w/ ES6 template string
var mdSource =`# title

text`;

// remove HTML tags w/ pure string literal
// remove HTML tags w/ ES6 template string
var mdSource ='
# title

text';
```

**Comment by joshbruce** [comment]
#985
