### ISSUE TITLE
marked() unable to render new line(\r\n in case of windows)

### ISSUE THREAD

**Issue by gopalindians** [chjj/marked#948]
```js
document.getElementById('markdown-answer-9').innerHTML = marked("&gt; hanji jai mata di kya kar rahe ho

* gopal
* sharma
* pankush
* majithia"
);

```

after first line, there is a newline character and `marked()` is unable to parse it.
showing error `Uncaught SyntaxError: Invalid or unexpected token`

Marked version: latest
Browser: Chrome
Browser Version: latest
Platform: Windows 8

**Comment by Feder1co5oave** [comment]
This is about javascript code parsing, not a marked error.

**Comment by joshbruce** [comment]
Closing. Comment and request reopen, if necessary.
