### ISSUE TITLE
THIS REPO IS NOT ACTIVE

### ISSUE THREAD

**Issue by UziTech** [chjj/marked#951]
@chjj please respond if this repo is still active.

For anyone looking for an active fork look at [8fold-marked](https://www.npmjs.com/package/8fold-marked)

**Comment by cjh9** [comment]
Good decision

**Comment by joshbruce** [comment]
Reached out to @chjj to see about transferring the project to 8fold. We'll see how that goes.

**Comment by caub** [comment]
Why are you not using markdown-it?

**Comment by joshbruce** [comment]
@caub - Me personally? Because I don't control the Markdown compiler used in https://github.com/sparksuite/simplemde-markdown-editor

I think a lot of us don't actually use Marked directly. Instead, we use other libraries that use Marked.

**Comment by UziTech** [comment]
@joshbruce how is it going with the transfer? Were you able to get ahold of @chjj?

**Comment by joshbruce** [comment]
@UziTech: Haven't heard back. Was just about to put a second email together. Was planning on CCing you on it this time. So, not well, I suppose??

**Comment by caub** [comment]
indeed I see marked in most of my node_modules, I think the best would be to deprecate this lib

and help transitioning like: https://github.com/graphql/graphiql/pull/581/files

**Comment by joshbruce** [comment]
@caub: What we've been trying to do in the meantime is I have a fork the community is starting to use:

https://github.com/8fold/marked

https://www.npmjs.com/package/8fold-marked - it seems to be getting used. Therefore, it seems like there is a significant chunk of the community who want to keep this library alive.

I would prefer to keep the library alive as "marked" instead of "8fold-marked".

**Comment by caub** [comment]
the problem is deeper, I think handling markdown with regexes like marked did, is too limited, too soon (for GFM, etc..)

**Comment by joshbruce** [comment]
That may be. I'm not sure how Marked is limiting compared to alternatives considering the specification for Markdown, Multi-Markdown, and other variations are pretty well established...and spit out the same HTML no matter what...but I'm not building Markdown editors, just using one. Curious to know what you're seeing there. (I don't know what GFM stands for, I do apologize.)

Having said that, this is starting to feel like a "we shouldn't use alkaline batteries" discussion...despite there being thousands of people dependent on alkaline batteries. 

This project is used by a lot of other packages. Those packages are used by a lot of other people and sites. I'm sure some of the packages who depend on it don't know the state of the project, which is arguably on them.

Whether regex is the best approach is not in question at the moment. Instead, the question is: How do we help other people dependent on this package? (Some will just switch to something else...others won't or can't...or don't know @chjj sorta wants to move on from it. Marked has 15,000 stars, 2,000 forks, 300 watchers, 50 contributors, 150 PRs, and 3.5 Million downloads in the last month...almost a million of those in the last week, which is where Markdown-it is for the month.) 

Solve the immediate need, then figure out the long-term strategy; be it moving Marked away from regex, getting everyone off Marked, or whatever.

**Comment by ankon** [comment]
@joshbruce can you enable issues on 8fold/marked then as well please? :)

**Comment by caub** [comment]
@ankon have you tried markdown-it? well, I'll unsubscribe, can't make thousands people migrate to a stable markdown lib alone

**Comment by ankon** [comment]
@caub, no, I haven't. markdown-it might be totally awesome, and certainly has a right to exist. But I don't think you can "make thousands people migrate to a stable markdown lib alone" by just asking that question and assuming that people will jump immediately towards the same conclusions you seem to have reached.

The reason I'm asking to enable issues on 8fold/marked is so that we can start working further on marked. This project is a dependency of a couple of our projects, and right now has issues/PRs that affect us. Spending time to switch libraries is _not_ right now something I'm interested in.

**Comment by caub** [comment]
Well good luck rebuilding a markdown lib

**Comment by joshbruce** [comment]
@ankon: Went ahead and turned on issues - wasn't planning on things going this route. To the best of my knowledge, I still haven't heard anything from @chjj re transferring the base project. Also turned on security vulnerability notifications.

@UziTech: Have you heard anything? Maybe I just missed something.

**Comment by UziTech** [comment]
When I contacted @chjj I cc'd support@npmjs.com as it says in npm's [disputes](https://docs.npmjs.com/misc/disputes) article. NPM did get back to me and asked if I wanted them transfer the marked name. I thought we were getting somewhere with @chjj and wouldn't need their intervention but maybe I was wrong.

Try emailing @chjj and cc support@npmjs.com maybe they can transfer the name and we can just start over with the repo at 8fold/marked.

**Comment by UziTech** [comment]
@joshbruce Should we close this issue now that you can update this repo and the npm package?

**Comment by joshbruce** [comment]
@UziTech: That's a good question. After thinking about it, I tend to agree. 

The ticket clutters the visibility of the other one, and we can always reopen it. Having said that, right now, this is a 30-day time-box for me to see how it goes. This project may actually be at the end of its life, and the focus may need to shift to helping transition and notify other packages and developers transition to something else.

If we (not I by myself) cannot make good strides in our efforts here given the constraints at hand (probably one of the biggest being my limited knowledge), then we'll have to change direction.
