### ISSUE TITLE
Task list can't be resolve,  is there a bug or a feature?

### ISSUE THREAD

**Issue by driftluo** [chjj/marked#952]
when I use in brower, `marked.js` is in `marked` project's `lib` folder
```
<script src="js/marked.js"></script>
```
```
> marked('- [ ] x')
"<ul>
<li>[ ] x</li>
</ul>
"
```
and there is same issue on [https://github.com/8fold/marked](https://github.com/8fold/marked)
@8fold

**Comment by joshbruce** [comment]
Do you mean bower or browser? Not sure I follow exactly what's expected versus what's being received.

**Comment by driftluo** [comment]
browser

**Comment by joshbruce** [comment]
The expectation would be something more like this, yeah:

```html 
<ul>
  <li><input type=”checkbox”><label>Hello</label></li>
</ul>
```

Yeah?

**Comment by driftluo** [comment]
In github, it will be like this:
```html
<ul class="contains-task-list">
  <li class="task-list-item">
  <input class="task-list-item-checkbox" disabled="" id="" type="checkbox"> Hello</li>
</ul>
```

**Comment by joshbruce** [comment]
@driftluo: Thanks for that. Think we would leave out the classes. Basically, give back the input and type. From an HTML perspective, I don't place a lot fo form controls outside of forms; so, is the GitHub markup accessible (what's the experience like for a blind person, for example).

@UziTech: Thoughts?

**Comment by UziTech** [comment]
I'm not sure that would be in scope for this package.

Maybe if we add extensions like [markdown-it](https://github.com/markdown-it/markdown-it). Seems like you would want to use [markdown-it-checkbox](https://github.com/mcecot/markdown-it-checkbox).

**Comment by fboes** [comment]
I added a simple fix for this locally, without altering `marked`:

```javascript
marked('- [ ] x').replace(/(<li>)\[ \](\s)/,'$1<input type="checkbox" />$2')).replace(/(<li>)\[x\](\s)/,'$1<input type="checkbox" checked="checked" />$2');
```

I am also not sure if it is a good thing to change this behavior. Some implementations might depend on how `marked` is currently working (like mine :)).

**Comment by joshbruce** [comment]
See #982
