### ISSUE TITLE
Existence of greater and lower signs in links gives different behaviour.

### ISSUE THREAD

**Issue by jsmonkey** [chjj/marked#954]
Hey guys,

I'm using [markdown-link-extractor](https://github.com/tcort/markdown-link-extractor). And this module uses ur library as a dependency.

After extracting the links, I have different results on each link from amount of invalid links, which triggers the issues and unexpected results in my application.

For example:
Extracting from this piece of markdown
```
[link](http://www.cnn.com>)
```
gives me:
```
http://www.cnn.com&gt;
```
which is right, cuz this link is invalid.

But from this one with lower sign:
```
[link](http://www.cnn.com<)
```
it extracts:
```
http://www.cnn.com
```
which is not true, cuz returned link is valid, but in markdown I still have link with wrong sign.

I think that it's some kind of error with regular expressions in existing codebase of ur module.
Anyways it would be nice to have a fix on that and mb new version of lib where everything works as expected.

Thanks.

**Comment by joshbruce** [comment]
#984

**Comment by Feder1co5oave** [comment]
I think you hit something bad here.
Per commonmark specs, link destinations can be delimited by `<` and `>`, or not.
http://spec.commonmark.org/0.28/#link-destination

From running your examples, I actually obtain the opposite result:
```html
$ bin/marked
[link](http://www.cnn.com>)
[link](http://www.cnn.com<)
^D
<p><a href="http://www.cnn.com">link</a>
<a href="http://www.cnn.com&lt;">link</a></p>
```

Problem is, marked should trim angle brackets at beginning or end of hrefs only if they are both present, whereas the current regex trims any of them. In the second example, it is an opening `<` at the _end_ of the href, so it is kept and escaped.

I suggest marking this as broken @joshbruce
