### ISSUE TITLE
Renderer Text function issues

### ISSUE THREAD

**Issue by taobataoma** [chjj/marked#970]
I add a Renderer text function:
```javascript
renderer.text = function (text) {
        return replaceSomeTags(text);
}
```
If i input 'this_is_test_word', and  i want to replace 'this_is_test_word' to other text, but the params text is not complete, the params is 'this' '_is' '_text' '_word', call the renderer four times,
how can i do? i need replace all content if it include 'this_is_test_word' at once.

thank for your great work!

**Comment by Feder1co5oave** [comment]
underscores have a special meaning in markdown, so you really can't use them freely in your input without escaping them.

**Comment by joshbruce** [comment]
@taobataoma: Before we close as essentially being part of most markdown specifications, please confirm, when using backticks (code blocks) `you_can_use_underscores`.

**Comment by taobataoma** [comment]
@Feder1co5oave @joshbruce  thanks, yes, I already done this work, I rewrite all renderer function to realize my idea. thanks.
