### ISSUE TITLE
Table styling

### ISSUE THREAD

**Issue by neilyoung** [chjj/marked#973]
Is there a way to apply CSS classes to tables w/o having to add own renderers?

I would be able to achieve something like this (according to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

<img width="446" alt="2" src="https://user-images.githubusercontent.com/731020/34055395-49a200f6-e1cf-11e7-8528-15bd1972dcab.png">

but what I get is this:

<img width="266" alt="1" src="https://user-images.githubusercontent.com/731020/34055368-24695370-e1cf-11e7-97ab-590b9b300cec.png">

Code:
```
import React from 'react'
const marked = require('marked')
marked.setOptions({
  gfm:true
})

var table = `
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
`

console.log(marked(table));

export default () => (
  <div dangerouslySetInnerHTML={{ __html: marked(table) }} />
)

```

**Comment by joshbruce** [comment]
@neilyoung: I don't know if you can do with Marked directly. Further, given the specs we are trying to concentrate on (see #956), I'm not sure this is something we want to add at the moment.

Having said that, given how often styles and naming conventions related to them change, what problem are you running into that could not be solved by a CSS selector pattern of some sort. Or, as much as a I hate to say it a `div` you control with the markdown results inside.

Tagging @UziTech and @matt-: What do y'all think about this assessment?

**Comment by UziTech** [comment]
Ya I don't think marked should be concerned with style. The purpose of marked is to take a markdown string and turn it into html. What styles are applied to the html output is up to whoever is displaying it.

If you look at the source code of the table on GitHub it looks the same as the output of marked.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

**Comment by joshbruce** [comment]
Closing. @neilyoung - If you would like to continue the discussion while the ticket is, we can do that. Thanks!

**Comment by neilyoung** [comment]
@joshbruce No, thanks. Every problem solved

**Comment by SohamTilekar** [comment]
> [@joshbruce](https://github.com/joshbruce) No, thanks. Every problem solved

How did You solved that Problem, Give Sol to me

**Comment by neilyoung** [comment]
I honestly don't remember :)

**Comment by chirag1807** [comment]
If anyone have solution, put it here

**Comment by UziTech** [comment]
You can just style with a css stylesheet like

```html
<style>
table {
  /* table styles */
}
th {
  /* header styles */
}
</style>
```

**Comment by chirag1807** [comment]
Thank you @UziTech
