### ISSUE TITLE
Better error messaging when source is undefined

### ISSUE THREAD

**Issue by joshbruce** [chjj/marked#979]
Perhaps add some error reporting for marked() if src ends up undefined 🤔? That way it's pretty clear the issue is not the marked library...

See #969

**Comment by Feder1co5oave** [comment]
My #682 tried to fix this by silently failing (return null), though I agree with you that a more explicit error message can be more helpful as rightfully pointed out here: https://github.com/chjj/marked/pull/682#issuecomment-241874201.

Maybe something along the lines of 
`marked(): input parameter is null/undefined` or
`marked(): input parameter of type <type>, string expected`

?

**Comment by Feder1co5oave** [comment]
Can close this
