### ISSUE TITLE
Optional charset in output

### ISSUE THREAD

**Issue by AlexanderEkdahl** [chjj/marked#99]
I often use marked from the command line to preview markdown documents before posting them on the web. However whenever I am forced to write in a different language the output becomes unreadable.

If I could pass an optional flag to wrap the output in an html block with a charset that would be cool.

If there is any interest at all for such a feature I would gladly fork and create it.

**Comment by sebelk** [comment]
AlexanderEkdahl,

Hi, please could you post how did you make the wrapper?

Thanks in advance!

**Comment by joshbruce** [comment]
Seems to not be a feature request, but a conversation. Due to age, closing.
