### ISSUE TITLE
Undeclared variable `baseUrls` in 0.3.9

### ISSUE THREAD

**Issue by learykara** [chjj/marked#990]
## Expectation

JS code builds without errors.

## Result

Error is thrown by undeclared variable `baseUrls`.

## What was attempted

On the latest version (0.3.9) it appears there is an undeclared variable `baseUrls` that causes an error in `strict` mode:

![image](https://user-images.githubusercontent.com/7073794/34394463-5e6654c4-eafd-11e7-93aa-82df14066eae.png)

**Comment by yumetodo** [comment]
Was this issue resolved by #991 ?

**Comment by joshbruce** [comment]
@yumetodo: It will be, at least to the best of my knowledge. The release has not happened yet - shooting for Monday. See #1001

**Comment by Feder1co5oave** [comment]
Fixed by #991. Close this.
