### ISSUE TITLE
Marked CLI Help Won't Open

### ISSUE THREAD

**Issue by crutchcorn** [chjj/marked#992]
## Expectation
Whern I run `marked --help`, I'd like to see a simple manpage of some kind. Really, just any kind of output. 

## Result

```
marked --help
(node:21012) [DEP0006] DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn man ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by Feder1co5oave** [comment]
I guess you don't have `man` available on your system? is that the cause of the error?

**Comment by crutchcorn** [comment]
On my system (Windows 10), `man` runs:
```
TOPIC
    Windows PowerShell Help System
```

So I'm not sure if that's the problem

**Comment by crutchcorn** [comment]
Actually, the README is missing a significant amount of information as to what the CLI is capable of (input, output, etc etc) so I would refer people experiencing the same issue here:
https://github.com/chjj/marked/blob/master/man/marked.1

**Comment by joshbruce** [comment]
Question, as this seems to be the appropriate place to bring it up.

Marked seems to ultimately be a dual product. An imported library, which I understand and makes sense. And it's also a CLI tool.

What are people using the CLI for exactly? What value does it bring to developers?

**Comment by crutchcorn** [comment]
I'll give you a great example of what I used the CLI for:
I much prefer using Markdown instead of HTML to do document writing and have an incredibly small page that I needed some layout for. So, I quickly wrote up some CSS for the markdown that was generated with the CLI, and boom - done in 10 minutes instead of having to use the library and add much more code to the codebase
